### ISSUE TITLE
Index out of bounds panic in pachd server start-up - v1.3.0

### ISSUE THREAD

**Issue by rrichardson** [pachyderm/pachyderm#1179]
After running pachctl deploy on my AWS hosted k8s cluster. 
The pachd pod goes into CrashLoop on start-up and this is the log

 ```panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x1676b40, 0xc42000a0b0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/pachyderm/pachyderm/src/server/pfs/server.NewBlockAPIServer(0x0, 0x0, 0x40000000, 0xc420014030, 0x6, 0xf, 0x22b9200, 0xc420171600, 0x22b2680)
        /go/src/github.com/pachyderm/pachyderm/src/server/pfs/server/server.go:47 +0x31f
main.do(0x1588360, 0xc420422000, 0x0, 0x0)
        /go/src/github.com/pachyderm/pachyderm/src/server/cmd/pachd/main.go:192 +0xce2
github.com/pachyderm/pachyderm/src/server/vendor/go.pedge.io/env.Main(0x1934190, 0x1588360, 0xc420422000, 0x0, 0x0, 0x0)
        /go/src/github.com/pachyderm/pachyderm/src/server/vendor/go.pedge.io/env/env.go:46 +0x83
main.main()
        /go/src/github.com/pachyderm/pachyderm/src/server/cmd/pachd/main.go:72 +0x98
```

**Comment by rrichardson** [comment]
I altered PACH_ROOT to be 'pach/dir' and got the same result. 

```
    Environment Variables:
      PACH_ROOT:                /pach/dir
      NUM_SHARDS:               1
      STORAGE_BACKEND:          AMAZON
      PACHD_POD_NAMESPACE:      default (v1:metadata.namespace)
      JOB_SHIM_IMAGE:           pachyderm/job-shim:1.3.0
      JOB_IMAGE_PULL_POLICY:    IfNotPresent
      PACHD_VERSION:            1.3.0
      METRICS:                  true
      LOG_LEVEL:                info
```
