### ISSUE TITLE
Double channel close in TestBtrfsFFI

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#130]
Just got this running tests (`make test`). This was on 088a15a91be9a3d9c2abbede2aedf016f93ddfbc

```
--- FAIL: TestBtrfsFFI (4.13s)
panic: close of closed channel [recovered]
        panic: close of closed channel

goroutine 35 [running]:
testing.tRunner.func1(0xc82019e480)
        /usr/local/go/src/testing/testing.go:450 +0x171
google.golang.org/grpc.(*ClientConn).Close(0xc8200cb3f0, 0x0, 0x0)
        /go/src/google.golang.org/grpc/clientconn.go:353 +0x139
github.com/pachyderm/pachyderm/src/pkg/grpctest.(*grpcSuite).TearDownSuite(0xc8200987d0)
        /go/src/github.com/pachyderm/pachyderm/src/pkg/grpctest/grpctest.go:83 +0x91
github.com/stretchr/testify/suite.Run.func1(0x7f5b55685600, 0xc8200987d0)
        /go/src/github.com/stretchr/testify/suite/suite.go:66 +0x75
github.com/stretchr/testify/suite.Run(0xc82019e480, 0x7f5b55685600, 0xc8200987d0)
        /go/src/github.com/stretchr/testify/suite/suite.go:105 +0x68a
github.com/pachyderm/pachyderm/src/pkg/grpctest.Run(0xc82019e480, 0x8, 0xc8200108a0, 0xc820013350)
        /go/src/github.com/pachyderm/pachyderm/src/pkg/grpctest/grpctest.go:25 +0xbe
github.com/pachyderm/pachyderm/src/pfs/server.runTest(0xc82019e480, 0x7f5b55685578, 0xc820010880, 0xca2820)
        /go/src/github.com/pachyderm/pachyderm/src/pfs/server/server_test.go:292 +0xb2
github.com/pachyderm/pachyderm/src/pfs/server.TestBtrfsFFI(0xc82019e480)
        /go/src/github.com/pachyderm/pachyderm/src/pfs/server/server_test.go:53 +0x1c2
testing.tRunner(0xc82019e480, 0x10c53a0)
        /usr/local/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
        /usr/local/go/src/testing/testing.go:561 +0x86d
```

**Comment by jdoliner** [comment]
Alright, I dug into this a bit and this seems to be a bug in grpc. They just changed how `ClientConn` works internally over the last few days. And inspect the code it seems quite possible for the shutdownChan to get closed twice.

Peter you already know these guys and wrote some of grpc, can you chat with them about it?

**Comment by peter-edge** [comment]
It's on our end sort of, I was double-closing a *grpc.ClientConn. They shouldn't have a panic if that happens but separate issue, I'll try to talk to them about it soon. Our code is fixed though.
