### ISSUE TITLE
1.4.1 breaks custom object store backend

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1595]
The 1.4.1 release breaks custom object store backends:

```
➔ pachctl deploy custom --persistent-disk google --object-store s3 ${STORAGE_NAME} ${STORAGE_SIZE} miniotest L16N742EJFHCYQG2134H DMxUvuReC85z4pR08HoN3dbbt5DFH48s/8Nz5983 104.154.85.248:9000 --static-etcd-volume=${STORAGE_NAME}
serviceaccount "pachyderm" created
persistentvolume "etcd-volume" created
persistentvolumeclaim "etcd-storage" created
replicationcontroller "etcd" created
service "etcd" created
service "pachd" created
replicationcontroller "pachd" created
secret "minio-secret" created
➔ watch kubectl get all
➔ kubectl get all
NAME             READY     STATUS             RESTARTS   AGE
po/etcd-p7mdx    1/1       Running            0          1m
po/pachd-ckjth   0/1       CrashLoopBackOff   3          1m

NAME       DESIRED   CURRENT   READY     AGE
rc/etcd    1         1         1         1m
rc/pachd   1         1         0         1m

NAME             CLUSTER-IP     EXTERNAL-IP   PORT(S)                       AGE
svc/etcd         10.3.244.166   <nodes>       2379:30766/TCP                1m
svc/kubernetes   10.3.240.1     <none>        443/TCP                       12m
svc/pachd        10.3.242.244   <nodes>       650:30650/TCP,651:30651/TCP   1m
➔ kubectl logs po/pachd-ckjth
time="2017-04-05T12:45:29Z" level=info 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x15846b3]

goroutine 1 [running]:
github.com/pachyderm/pachyderm/src/server/pkg/obj.TestIsNotExist(0x260eda0, 0xc420335820, 0x28, 0x228)
	/go/src/github.com/pachyderm/pachyderm/src/server/pkg/obj/obj.go:324 +0xd3
github.com/pachyderm/pachyderm/src/server/pfs/server.newObjBlockAPIServer(0xc42000e01b, 0x4, 0x140000000, 0x260eda0, 0xc420335820, 0x0, 0x0, 0xc4205d9c80)
	/go/src/github.com/pachyderm/pachyderm/src/server/pfs/server/obj_block_api_server.go:55 +0x4d
github.com/pachyderm/pachyderm/src/server/pfs/server.newMinioBlockAPIServer(0xc42000e01b, 0x4, 0x140000000, 0x140000000, 0x0, 0x0)
	/go/src/github.com/pachyderm/pachyderm/src/server/pfs/server/obj_block_api_server.go:87 +0x99
github.com/pachyderm/pachyderm/src/server/pfs/server.NewBlockAPIServer(0xc42000e01a, 0x5, 0x140000000, 0xc42000a050, 0x5, 0xc, 0x2610f40, 0xc4200af900, 0x2609e20)
	/go/src/github.com/pachyderm/pachyderm/src/server/pfs/server/server.go:57 +0xc8
main.do(0x175c960, 0xc4200e0000, 0x0, 0x0)
	/go/src/github.com/pachyderm/pachyderm/src/server/cmd/pachd/main.go:184 +0xb78
github.com/pachyderm/pachyderm/src/server/pkg/cmdutil.Main(0x1aecf78, 0x175c960, 0xc4200e0000, 0x0, 0x0, 0x0)
	/go/src/github.com/pachyderm/pachyderm/src/server/pkg/cmdutil/env.go:31 +0x83
main.main()
	/go/src/github.com/pachyderm/pachyderm/src/server/cmd/pachd/main.go:69 +0x6e
➔ 
```

Looks like we need to:

1. Fix this bug.
2. Include a Minio deploy is our planned nightly tests.

**Comment by jonandernovella** [comment]
+1

**Comment by dwhitena** [comment]
As you might have notice @jonandernovella is also experiencing this issue.  It appears that the breaking change was this check:

https://github.com/pachyderm/pachyderm/commit/68ede0dd5070dc857fb0bf29dbd19be331e1fba4
