### ISSUE TITLE
pachd crash upon startup

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1651]
From a user running 1.4.3:

```
2017-04-11T23:50:47Z ERROR error discovering workers: watcher for prefix pachyderm_pps/workers/pipeline-pachsupport-boxes-flatten-v1/ closed for unknown reasons; retrying in 387.742923ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x1695d12]
goroutine 110 [running]:
github.com/pachyderm/pachyderm/src/server/pps/server.(*apiServer).pipelineWatcher.func1(0xc42043bec0, 0xc4201f0748)
        /go/src/github.com/pachyderm/pachyderm/src/server/pps/server/api_server.go:859 +0x1c2
github.com/pachyderm/pachyderm/src/server/pkg/backoff.RetryNotify(0xc420264b40, 0x25dc760, 0xc42043bec0, 0xc420d71f98, 0xc4201f07a8, 0xa3eb25)
        /go/src/github.com/pachyderm/pachyderm/src/server/pkg/backoff/retry.go:35 +0x3f
github.com/pachyderm/pachyderm/src/server/pps/server.(*apiServer).pipelineWatcher(0xc420497540, 0x7f2148cdd360, 0xc420390f80, 0x6)
        /go/src/github.com/pachyderm/pachyderm/src/server/pps/server/api_server.go:897 +0xed
created by github.com/pachyderm/pachyderm/src/server/pps/server.(*apiServer).AddShard
        /go/src/github.com/pachyderm/pachyderm/src/server/pps/server/api_server.go:1573 +0x30f
```

**Comment by derekchiang** [comment]
Might be related:

```
 in 311.310947ms
2017-04-12T00:34:42Z INFO  goro for worker 10.244.4.59 is exiting
2017-04-12T00:34:42Z INFO  goro for worker 10.244.4.60 is exiting
2017-04-12T00:34:42Z INFO  goro for worker 10.244.2.42 is exiting
2017-04-12T00:34:42Z INFO  goro for worker 10.244.0.45 is exiting
2017-04-12T00:34:42Z ERROR error discovering workers: watcher for prefix pachyderm_pps/workers/pipeline-pachsupport-boxes-flatten-v1/ closed for unknown reasons; retrying in 627.662717ms
2017-04-12T00:34:42Z INFO  goro for worker 10.244.0.11 is exiting
2017-04-12T00:34:42Z INFO  goro for worker 10.244.2.8 is exiting
2017-04-12T00:34:42Z INFO  goro for worker 10.244.3.10 is exiting
2017-04-12T00:34:42Z INFO  goro for worker 10.244.3.9 is exiting
2017-04-12T00:34:42Z INFO  goro for worker 10.244.4.13 is exiting
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x1696962]
goroutine 113 [running]:
github.com/pachyderm/pachyderm/src/server/pps/server.(*apiServer).jobWatcher.func1(0xc420278a20, 0xc420511748)
        /go/src/github.com/pachyderm/pachyderm/src/server/pps/server/api_server.go:931 +0x1c2
github.com/pachyderm/pachyderm/src/server/pkg/backoff.RetryNotify(0xc4202b1cb0, 0x25dc760, 0xc420278a20, 0xc421a07f98, 0xc4205117a8, 0xa3ead7)
        /go/src/github.com/pachyderm/pachyderm/src/server/pkg/backoff/retry.go:35 +0x3f
github.com/pachyderm/pachyderm/src/server/pps/server.(*apiServer).jobWatcher(0xc4200bdb80, 0x7f6d811a2a40, 0xc4204ca380, 0x6)
        /go/src/github.com/pachyderm/pachyderm/src/server/pps/server/api_server.go:970 +0xed
created by github.com/pachyderm/pachyderm/src/server/pps/server.(*apiServer).AddShard
        /go/src/github.com/pachyderm/pachyderm/src/server/pps/server/api_server.go:1592 +0x2c9
```

**Comment by derekchiang** [comment]
More logs:

```
panic: send on closed channel
goroutine 270 [running]:
github.com/pachyderm/pachyderm/src/server/pkg/collection.(*readonlyCollection).WatchByIndex.func1.1(0xc420360360, 0xc420627fd0, 0x25dc8e0, 0xc42045f610)
        /go/src/github.com/pachyderm/pachyderm/src/server/pkg/collection/collection.go:392 +0xb3
github.com/pachyderm/pachyderm/src/server/pkg/collection.(*readonlyCollection).WatchByIndex.func1(0xc420360360, 0x25dc8e0, 0xc42045f610, 0xc4203603c0, 0xc4205f0c00, 0x25d2660, 0xc42000e3c0)
        /go/src/github.com/pachyderm/pachyderm/src/server/pkg/collection/collection.go:419 +0x5bc
created by github.com/pachyderm/pachyderm/src/server/pkg/collection.(*readonlyCollection).WatchByIndex
        /go/src/github.com/pachyderm/pachyderm/src/server/pkg/collection/collection.go:439 +0x1b3
```

**Comment by derekchiang** [comment]
Unsure about the first logs, but the two above both happened when we are re-deploying a three-node cluster with a new `pachd` image.
