### ISSUE TITLE
pachd crash in `GetObject`

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1799]
This is from a cluster under heavy load:

```
2017-05-05T22:30:09Z INFO  protorpclog.Call {"service":"CacheServer","method":"Get","request":"group:\"tag\" key:\"2f.887854929027935d576d5915e125fa2f6488377f8134693c0480c7825e1e241048f3e24234fcd626341c2e60516dbbd8405759db5c7ca491fbceba6295177b\" ","duration":"0.000s"}
2017-05-05T22:30:09Z INFO  protorpclog.Call {"service":"CacheServer","method":"Get","request":"group:\"tag\" key:\"2f.887854929027935d576d5915e125fa2f6488377f8134693c0480c7825e1e241048f3e24234fcd626341c2e60516dbbd8405759db5c7ca491fbceba6295177b\" ","duration":"0.000006771s"}
2017-05-05T22:30:09Z INFO  protorpclog.Call {"service":"pfs.BlockAPI.Obj","method":"GetTag","request":"name:\"1a1a3ec2ab62481599a6b9d2e9921ee52b6d8e0682a666555ec95add10a29fe9\" ","duration":"0.000s"}
2017-05-05T22:30:09Z INFO  protorpclog.Call {"service":"pfs.BlockAPI.Obj","method":"GetObject","request":"hash:\"0fb54dcb9f820956deeb334971082b5ab96197634fda5f0dff21a5a128cf0c2dfcc21ae38829935e01903823011f939cfb5943987551e1d4cc36b6bc0b71cccd\" ","duration":"0.000s"}
2017-05-05T22:30:09Z INFO  protorpclog.Call {"service":"pfs.BlockAPI.Obj","method":"InspectObject","request":"hash:\"0fb54dcb9f820956deeb334971082b5ab96197634fda5f0dff21a5a128cf0c2dfcc21ae38829935e01903823011f939cfb5943987551e1d4cc36b6bc0b71cccd\" ","duration":"0.000s"}
2017-05-05T22:30:09Z INFO  protorpclog.Call {"service":"pfs.BlockAPI.Obj","method":"InspectObject","request":"hash:\"0fb54dcb9f820956deeb334971082b5ab96197634fda5f0dff21a5a128cf0c2dfcc21ae38829935e01903823011f939cfb5943987551e1d4cc36b6bc0b71cccd\" ","response":"object:\u003chash:\"0fb54dcb9f820956deeb334971082b5ab96197634fda5f0dff21a5a128cf0c2dfcc21ae38829935e01903823011f939cfb5943987551e1d4cc36b6bc0b71cccd\" \u003e block_ref:\u003c\u003e ","duration":"0.002450161s"}
2017-05-05T22:30:09Z INFO  protorpclog.Call {"service":"pfs.BlockAPI.Obj","method":"call64","request":"hash:\"0fb54dcb9f820956deeb334971082b5ab96197634fda5f0dff21a5a128cf0c2dfcc21ae38829935e01903823011f939cfb5943987551e1d4cc36b6bc0b71cccd\" ","duration":"0.002664378s"}
2017-05-05T22:30:09Z INFO  protorpclog.Call {"service":"pfs.BlockAPI.Obj","method":"call64","request":"name:\"1a1a3ec2ab62481599a6b9d2e9921ee52b6d8e0682a666555ec95add10a29fe9\" ","duration":"0.006571176s"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x16671fd]

goroutine 487901 [running]:
github.com/pachyderm/pachyderm/src/server/pfs/server.(*objBlockAPIServer).GetObject(0xc420aaa200, 0xc430e79ca0, 0x7f7e1f07aa38, 0xc430e79b10, 0x0, 0x0)
        /go/src/github.com/pachyderm/pachyderm/src/server/pfs/server/obj_block_api_server.go:187 +0x14d
github.com/pachyderm/pachyderm/src/server/pfs/server.(*objBlockAPIServer).GetTag(0xc420aaa200, 0xc430e79b00, 0x260fd40, 0xc430e79b10, 0x0, 0x0)
        /go/src/github.com/pachyderm/pachyderm/src/server/pfs/server/obj_block_api_server.go:307 +0x263
github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pfs._ObjectAPI_GetTag_Handler(0x1a26c20, 0xc420aaa200, 0x260e7e0, 0xc45737e820, 0xc42e437610, 0xc4501ed000)
        /go/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pfs/pfs.pb.go:2544 +0x113
github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc420305790, 0x26100a0, 0xc4206dbc00, 0xc4501ed000, 0xc42045a630, 0x266cfa0, 0xc4581d9770, 0x0, 0x0)
        /go/src/github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/server.go:819 +0x7b9
github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420305790, 0x26100a0, 0xc4206dbc00, 0xc4501ed000, 0xc4581d9770)
        /go/src/github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/server.go:909 +0x11fd
github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4202c0e60, 0xc420305790, 0x26100a0, 0xc4206dbc00, 0xc4501ed000)
        /go/src/github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/server.go:478 +0xa9
created by github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /go/src/github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/server.go:479 +0xa1
```

In case the code changes, here's a [permalink](https://github.com/pachyderm/pachyderm/blob/17943c226c18736e53d80414b1eccdb45cc8afe7/src/server/pfs/server/obj_block_api_server.go#L187) to the code as it is right now.

**Comment by sjezewski** [comment]
stale
