### ISSUE TITLE
pachd segfaults if `PutFile` is closed without sending any data

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#1977]
This should probably be a failure case, but presumably shouldn't result in a segfault

Doing
```
pf = pfs.putFile(function() {console.log('putFile complete:', arguments)})
pf.end()
```
Results in
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x166ec62]

goroutine 770 [running]:
github.com/pachyderm/pachyderm/src/server/pfs/server.(*apiServer).PutFile(0xc420409fe0, 0x26595e0, 0xc420135010, 0x0, 0x0)
	/go/src/github.com/pachyderm/pachyderm/src/server/pfs/server/api_server.go:324 +0x2e2
github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pfs._API_PutFile_Handler(0x1a53e20, 0xc420409fe0, 0x2656ee0, 0xc4202bebe0, 0xc42015c610, 0xc420651c00)
	/go/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pfs/pfs.pb.go:2238 +0xba
github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc42042d040, 0x26589e0, 0xc42010e0e0, 0xc420651c00, 0xc4202e6090, 0x26b5b80, 0xc42042abd0, 0x0, 0x0)
	/go/src/github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/server.go:819 +0x7b9
github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc.(*Server).handleStream(0xc42042d040, 0x26589e0, 0xc42010e0e0, 0xc420651c00, 0xc42042abd0)
	/go/src/github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/server.go:909 +0x11fd
github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420134d50, 0xc42042d040, 0x26589e0, 0xc42010e0e0, 0xc420651c00)
	/go/src/github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/server.go:478 +0xa9
created by github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/server.go:479 +0xa1
```

(And GRPC Error code 14 with no further details gets returned to the client)

**Comment by sjezewski** [comment]
stale
