### ISSUE TITLE
Inspect Datum segfault

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#2260]
```
pc inspect-datum 3d966078-8682-408a-b183-0aeb9fbd9ce5 88034d7ead6252cba372d260f469af004f5d986de3c45317ce3aa8817b1b583c
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x21bcad3]

goroutine 1 [running]:
github.com/pachyderm/pachyderm/src/server/pps/pretty.PrintDetailedDatumInfo(0x2fd0700, 0xc420154800, 0xc420596040)
	/home/mjs/clients/auth-consistency/src/github.com/pachyderm/pachyderm/src/server/pps/pretty/pretty.go:217 +0x233
github.com/pachyderm/pachyderm/src/server/pps/cmds.Cmds.func9(0xc4201f8d00, 0x2, 0x2, 0x100f2c8, 0x10)
	/home/mjs/clients/auth-consistency/src/github.com/pachyderm/pachyderm/src/server/pps/cmds/cmds.go:266 +0x225
github.com/pachyderm/pachyderm/src/server/pkg/cmdutil.RunBoundedArgs.func1(0xc4201fe480, 0xc4201f8d00, 0x2, 0x2)
	/home/mjs/clients/auth-consistency/src/github.com/pachyderm/pachyderm/src/server/pkg/cmdutil/cobra.go:35 +0x190
github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra.(*Command).execute(0xc4201fe480, 0xc4201f8320, 0x2, 0x2, 0xc4201fe480, 0xc4201f8320)
	/home/mjs/clients/auth-consistency/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra/command.go:572 +0x22b
github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420193d40, 0xc4201caed0, 0xc4201cae50, 0xc4201caeb0)
	/home/mjs/clients/auth-consistency/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra/command.go:658 +0x339
github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420193d40, 0x0, 0x0)
	/home/mjs/clients/auth-consistency/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra/command.go:617 +0x2b
main.main.func1(0x24d1680, 0xc4201c3dd0)
	/home/mjs/clients/auth-consistency/src/github.com/pachyderm/pachyderm/src/server/cmd/pachctl/main.go:21 +0x42
main.main()
	/home/mjs/clients/auth-consistency/src/github.com/pachyderm/pachyderm/src/server/cmd/pachctl/main.go:25 +0xc3```

**Comment by JoeyZwicker** [comment]
@msteffen I think you were looking at this a while back, but I might be misremembering. Is there anything to do here?

**Comment by sjezewski** [comment]
stale
