### ISSUE TITLE
Segfault in auth code

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#2492]
I seem to get this error periodically, I'm not quite sure what causes it but presumably we should be able to insulate against this segfault and give a more reasonable error.

```
2017-11-01T20:36:30Z INFO pfs.API.CreateRepo {"request":{"repo":{"name":"TestMultipleInputsFromTheSameBranch_data0ece61c0f2b6"}}} 
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x7d4c0c]

goroutine 292 [running]:
github.com/pachyderm/pachyderm/src/server/pkg/collection.runSTM.func1.1(0xc420822480)
        /go/src/github.com/pachyderm/pachyderm/src/server/pkg/collection/transaction.go:92 +0xab
panic(0x19eaa80, 0x2a0e9c0)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc.Invoke(0x7fdcdd777830, 0xc420780210, 0x1c4d5cd, 0x10, 0x1b04100, 0x2a529b8, 0x1b32a00, 0xc420136080, 0x0, 0x0, ...)
        /go/src/github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/call.go:132 +0x2c
github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/auth.(*aPIClient).WhoAmI(0xc420134360, 0x7fdcdd777830, 0xc420780210, 0x2a529b8, 0x0, 0x0, 0x0, 0x5, 0xc420010700, 0xc420480458)
        /go/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/auth/auth.pb.go:752 +0xd2
github.com/pachyderm/pachyderm/src/server/pfs/server.(*driver).createRepo.func1(0x29b4300, 0xc42065ca50, 0xc420822480, 0x7ed93f)
        /go/src/github.com/pachyderm/pachyderm/src/server/pfs/server/driver.go:243 +0x29c
github.com/pachyderm/pachyderm/src/server/pkg/collection.runSTM.func1(0xc420822480, 0x29b4300, 0xc42065ca50, 0xc42065ca00)
        /go/src/github.com/pachyderm/pachyderm/src/server/pkg/collection/transaction.go:100 +0x83
created by github.com/pachyderm/pachyderm/src/server/pkg/collection.runSTM
        /go/src/github.com/pachyderm/pachyderm/src/server/pkg/collection/transaction.go:86 +0x7a
```

**Comment by jdoliner** [comment]
I haven't seen this issue in a long time, and a lot of the code in this area has changed, so I think it's safe to close this, feel free to reopen if you see this again.
