### ISSUE TITLE
malformed pipeline manifest causes a pachd panic

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#2650]
```
2018-01-30T00:21:17Z INFO pps.API.CreatePipeline {"request":{"pipeline":{"name":"user_invalid_submission2LIC2_inference"},"description":"Given any docker image, runs a common entry point for a user's inference model"}} 
2018-01-30T00:21:17Z INFO pps.API.call64 {"duration":0.000050014,"request":{"pipeline":{"name":"user_invalid_submission2LIC2_inference"},"description":"Given any docker image, runs a common entry point for a user's inference model"},"response":null} 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x173aa5d]

goroutine 15241 [running]:
github.com/pachyderm/pachyderm/src/server/pps/server.setPipelineDefaults(0xc4205a4500)
	/go/src/github.com/pachyderm/pachyderm/src/server/pps/server/api_server.go:1569 +0x3d
github.com/pachyderm/pachyderm/src/server/pps/server.(*apiServer).CreatePipeline(0xc4201a0480, 0x7fd3d5300220, 0xc4203c0480, 0xc4208be210, 0x0, 0x0, 0x0)
	/go/src/github.com/pachyderm/pachyderm/src/server/pps/server/api_server.go:1390 +0x4bd
github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pps._API_CreatePipeline_Handler(0x1bd04e0, 0xc4201a0480, 0x7fd3d5300220, 0xc4203c0480, 0xc420232370, 0x0, 0x0, 0x0, 0xc42088bac0, 0xc42088bac8)
	/go/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pps/pps.pb.go:3143 +0x276
github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4200cac80, 0x2a18c60, 0xc4205498c0, 0xc4202c0300, 0xc420348ab0, 0x2a91d40, 0x0, 0x0, 0x0)
	/go/src/github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/server.go:806 +0xab4
github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4200cac80, 0x2a18c60, 0xc4205498c0, 0xc4202c0300, 0x0)
	/go/src/github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/server.go:1003 +0x1528
github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42055e680, 0xc4200cac80, 0x2a18c60, 0xc4205498c0, 0xc4202c0300)
	/go/src/github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/server.go:552 +0x9f
created by github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/server.go:550 +0xa1
```

**Comment by ysimonson** [comment]
This may already be fixed, but putting in the bugs project for verification.
