### ISSUE TITLE
Pipelines incrementally processing stats branch seem to see all content

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2991]
**What happened?**:

Pipeline consuming stats branch incrementally seems to see the entire list of all datums, rather than just the newly added datums, on each run.

**What you expected to happen?**:

That the list of directories (datums) is only those produced ("processed") by the most recent job

**How to reproduce it (as minimally and precisely as possible)?**:

This sets up a pipeline that lists the datums present in a stats commit, and throws an error if it finds datums created in more than one different job:
```
pachctl create-repo input
echo '{
  "pipeline": {
    "name": "test"
  },
  "transform": {
    "cmd": [ "bash", "-c", "cp -r $(ls -d /pfs/*|grep -v /pfs/out) /pfs/out" ]
  },
  "input": {
    "atom": {
      "repo": "input",
      "branch": "master",
      "glob": "**"
    }
  },
  "enable_stats": true
}' | pachctl create-pipeline

echo '{
  "pipeline": {
    "name": "dash__pipeline_stats__test__dash"
  },
  "transform": {
    "image": "gabrielgrant/pach_stats:6c1654ed30a85d0638b8c27def9640bab96ad323",
    "cmd": [ "python", "stats.py" ]
  },
  "input": {
    "atom": {
      "repo": "test",
      "branch": "stats",
      "glob": "/",
      "name": "stats"
    }
  },
  "incremental": true,
  "enable_stats": false
}' | pachctl create-pipeline

echo '1
2
3' | pachctl put-file input master /splitted --split line
echo '1
2
3' | pachctl put-file input master /splitted --split line
```
if you look at the stats pipeline, the first job will succeed:

```
starting to download data
finished downloading data after 358.314193ms
beginning to run user code
datum names:
['fe96cb4e299719c8e2aea4e1710af730af2413a65b6e72902b0cffafef111028', '1be957a46b3a8751c8c324d7decde1570f0792c66840b17f2497693ff2dbafd8', 'ebf37b22f6c53f7f4b71cf28193a5089eaeb1dbaff5d36458f09551deed683e9', '8a31ea85218ad252797785b0f7ef831e2610dc1d81fa822ce8e84104d57dd218']
old jobs:
set()
finished running user code after 1.30192071s
starting to upload output
finished uploading output after 16.535221ms
```
but the second job will fail, showing an assertion error in the python code about the multiple new jobs appearing in the same commit (three times):

```
starting to download data
finished downloading data after 507.728909ms
beginning to run user code
datum names:
['fe96cb4e299719c8e2aea4e1710af730af2413a65b6e72902b0cffafef111028', '924d2c2b24eb72f88f47a80c4437bc6420a6bd1835ea4d1b704f4a9912f021bf', 'f24d8532fca5ade37fb91603313ba7fe68eb6c97733d28be17f8a43a8cd93c96', '1be957a46b3a8751c8c324d7decde1570f0792c66840b17f2497693ff2dbafd8', 'ebf37b22f6c53f7f4b71cf28193a5089eaeb1dbaff5d36458f09551deed683e9', 'f7b3949411ed11556444f36942311f6a36a7d608a351c0faf28a779ea0d1366e', 'c392ffe99398d8eeac1c7c9dbac73ae6841f438b07b735c8e774255a92f2ed8e']
old jobs:
set()
Traceback (most recent call last):
  File "stats.py", line 126, in <module>
    main()
  File "stats.py", line 55, in main
    assert job_id == new_job_id, 'Datum {}: {} != {} -- multiple new jobs present'.format(datum_name, job_id, new_job_id)
AssertionError: Datum 924d2c2b24eb72f88f47a80c4437bc6420a6bd1835ea4d1b704f4a9912f021bf: 84b0215f181444fd9b8bf83ffbdef499 != fb9bf45cec2746abab942ae6dbc7fc77 -- multiple new jobs present
errored running user code after 529.010302ms: error cmd.WaitIO: exit status 1
failed processing datum: error runUserCode: error cmd.WaitIO: exit status 1, retrying in 0s
starting to download data
finished downloading data after 414.864801ms
beginning to run user code
datum names:
['fe96cb4e299719c8e2aea4e1710af730af2413a65b6e72902b0cffafef111028', '924d2c2b24eb72f88f47a80c4437bc6420a6bd1835ea4d1b704f4a9912f021bf', 'f24d8532fca5ade37fb91603313ba7fe68eb6c97733d28be17f8a43a8cd93c96', '1be957a46b3a8751c8c324d7decde1570f0792c66840b17f2497693ff2dbafd8', 'ebf37b22f6c53f7f4b71cf28193a5089eaeb1dbaff5d36458f09551deed683e9', 'f7b3949411ed11556444f36942311f6a36a7d608a351c0faf28a779ea0d1366e', 'c392ffe99398d8eeac1c7c9dbac73ae6841f438b07b735c8e774255a92f2ed8e']
old jobs:
set()
Traceback (most recent call last):
  File "stats.py", line 126, in <module>
    main()
  File "stats.py", line 55, in main
    assert job_id == new_job_id, 'Datum {}: {} != {} -- multiple new jobs present'.format(datum_name, job_id, new_job_id)
AssertionError: Datum 924d2c2b24eb72f88f47a80c4437bc6420a6bd1835ea4d1b704f4a9912f021bf: 84b0215f181444fd9b8bf83ffbdef499 != fb9bf45cec2746abab942ae6dbc7fc77 -- multiple new jobs present
errored running user code after 509.320816ms: error cmd.WaitIO: exit status 1
failed processing datum: error runUserCode: error cmd.WaitIO: exit status 1, retrying in 0s
starting to download data
finished downloading data after 378.683679ms
beginning to run user code
datum names:
['fe96cb4e299719c8e2aea4e1710af730af2413a65b6e72902b0cffafef111028', '924d2c2b24eb72f88f47a80c4437bc6420a6bd1835ea4d1b704f4a9912f021bf', 'f24d8532fca5ade37fb91603313ba7fe68eb6c97733d28be17f8a43a8cd93c96', '1be957a46b3a8751c8c324d7decde1570f0792c66840b17f2497693ff2dbafd8', 'ebf37b22f6c53f7f4b71cf28193a5089eaeb1dbaff5d36458f09551deed683e9', 'f7b3949411ed11556444f36942311f6a36a7d608a351c0faf28a779ea0d1366e', 'c392ffe99398d8eeac1c7c9dbac73ae6841f438b07b735c8e774255a92f2ed8e']
old jobs:
set()
Traceback (most recent call last):
  File "stats.py", line 126, in <module>
    main()
  File "stats.py", line 55, in main
    assert job_id == new_job_id, 'Datum {}: {} != {} -- multiple new jobs present'.format(datum_name, job_id, new_job_id)
AssertionError: Datum 924d2c2b24eb72f88f47a80c4437bc6420a6bd1835ea4d1b704f4a9912f021bf: 84b0215f181444fd9b8bf83ffbdef499 != fb9bf45cec2746abab942ae6dbc7fc77 -- multiple new jobs present
errored running user code after 557.354285ms: error cmd.WaitIO: exit status 1
failed to process datum with error: error runUserCode: error cmd.WaitIO: exit status 1
```

As you can see from the list of datum names (taken by `ls`ing the input directory), it appears as though the second job is having all the datums presented to it, rather than just the new ones

Tested on 1.7.3 and latest master (b67b9870c43cbb5c2f6c806f7c8f1d1ec0e3e85f)

**Comment by jdoliner** [comment]
This is no longer an issue because we no longer have incremental pipelines. I'm wondering if maybe it had to do with the parentage / provenance structure of the stats branch being weird. Going to close this since it's not something we can really work on now. When we do re-add incremental jobs we'll need to make sure stats commits work with them.
