### ISSUE TITLE
'make lint' flakes in CI

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#2998]
Example failure (went away after rerunning the misc tests):
```
Running misc test suite
# golang.org/x/tools/go/internal/gcimporter
../../../golang.org/x/tools/go/internal/gcimporter/iimport.go:540:10: undefined: types.NewInterface2
make: *** [lint] Error 2
```
I wonder if some of our test failures are due to inconsistency in the test environment

**Comment by msteffen** [comment]
I'm starting to wonder if Travis networking is flaky. Two other examples of mysterious test flakes:
```
=== RUN   TestListJobOutput
No config detected. Generating new config...
No UserID present in config. Generating new UserID and updating config at /home/travis/.pachyderm/config.json
--- PASS: TestListJobOutput (17.13s)
=== RUN   TestPipelineEnvVarAlias
--- FAIL: TestPipelineEnvVarAlias (3.86s)
	pachyderm_test.go:5534: No error is expected but got error deleting workers: Get https://10.96.0.1:443/api/v1/namespaces/default/services?labelSelector=pipelineName%3Dpipelineee259dbd4098: unexpected EOF
	pachyderm_test.go:5534: current stack:
		goroutine 14 [running]:
		runtime/debug.Stack(0xc42010f950, 0x163d024, 0x1f)
			/home/travis/.gimme/versions/go1.10beta1.linux.amd64/src/runtime/debug/stack.go:24 +0xa7
		github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pkg/require.fatal(0x17c7b40, 0xc42010f950, 0x0, 0x0, 0x0, 0x163d024, 0x1f, 0xc4202ba680, 0x1, 0x1)
			/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:421 +0xc5
		github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pkg/require.NoError(0x17c7b40, 0xc42010f950, 0x1790180, 0xc4202ba670, 0x0, 0x0, 0x0)
			/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:302 +0x13b
		github.com/pachyderm/pachyderm/src/server.TestPipelineEnvVarAlias(0xc42010f950)
			/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pachyderm_test.go:5534 +0xd1
		testing.tRunner(0xc42010f950, 0x16b4be0)
			/home/travis/.gimme/versions/go1.10beta1.linux.amd64/src/testing/testing.go:774 +0xc4
		created by testing.(*T).Run
			/home/travis/.gimme/versions/go1.10beta1.linux.amd64/src/testing/testing.go:821 +0x2ca
=== RUN   TestMaxQueueSize
--- FAIL: TestMaxQueueSize (2.44s)
	pachyderm_test.go:5579: No error is expected but got error deleting workers: Get https://10.96.0.1:443/api/v1/namespaces/default/services?labelSelector=pipelineName%3Dpipelineee259dbd4098: dial tcp 10.96.0.1:443: connect: connection refused
	pachyderm_test.go:5579: current stack:
		goroutine 15 [running]:
		runtime/debug.Stack(0xc42010fb30, 0x163d024, 0x1f)
			/home/travis/.gimme/versions/go1.10beta1.linux.amd64/src/runtime/debug/stack.go:24 +0xa7
		github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pkg/require.fatal(0x17c7b40, 0xc42010fb30, 0x0, 0x0, 0x0, 0x163d024, 0x1f, 0xc4203500e0, 0x1, 0x1)
			/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:421 +0xc5
		github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pkg/require.NoError(0x17c7b40, 0xc42010fb30, 0x1790180, 0xc4203500d0, 0x0, 0x0, 0x0)
			/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:302 +0x13b
		github.com/pachyderm/pachyderm/src/server.TestMaxQueueSize(0xc42010fb30)
			/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pachyderm_test.go:5579 +0xd1
		testing.tRunner(0xc42010fb30, 0x16b4b88)
			/home/travis/.gimme/versions/go1.10beta1.linux.amd64/src/testing/testing.go:774 +0xc4
		created by testing.(*T).Run
			/home/travis/.gimme/versions/go1.10beta1.linux.amd64/src/testing/testing.go:821 +0x2ca
```
and this from @gabrielgrant :+1:
```
=== RUN   TestPipelineBadImage
No config detected. Generating new config...
No UserID present in config. Generating new UserID and updating config at /home/travis/.pachyderm/config.json
--- FAIL: TestPipelineBadImage (62.85s)
    pachyderm_test.go:5389: No error is expected but got pipeline bad_pipeline_2_59e357ed13e9 should have failed
    pachyderm_test.go:5389: current stack:
        goroutine 10 [running]:
        runtime/debug.Stack(0xc42049ba40, 0x164f924, 0x1f)
            /home/travis/.gimme/versions/go1.10beta1.linux.amd64/src/runtime/debug/stack.go:24 +0xa7
        github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pkg/require.fatal(0x17db880, 0xc42049ba40, 0x0, 0x0, 0x0, 0x164f924, 0x1f, 0xc4200b9010, 0x1, 0x1)
            /home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:421 +0xc5
        github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pkg/require.NoError(0x17db880, 0xc42049ba40, 0x17a3d20, 0xc4200b8fb0, 0x0, 0x0, 0x0)
            /home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:302 +0x13b
        github.com/pachyderm/pachyderm/src/server.TestPipelineBadImage(0xc42049ba40)
            /home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pachyderm_test.go:5389 +0x5b5
        testing.tRunner(0xc42049ba40, 0x16c77d8)
            /home/travis/.gimme/versions/go1.10beta1.linux.amd64/src/testing/testing.go:774 +0xc4
        created by testing.(*T).Run
            /home/travis/.gimme/versions/go1.10beta1.linux.amd64/src/testing/testing.go:821 +0x2ca
```

**Comment by ysimonson** [comment]
I think it makes sense to close this out, since `make lint` hasn't been flaky at least since I've joined. TravisCI's network is definitely flaky, though.

**Comment by jdoliner** [comment]
Yeah, closing, I haven't seen this in a while. Maybe a new version of lint fixed the bug?
