### ISSUE TITLE
Azure deploy fails

### ISSUE THREAD

**Issue by SkinyMonkey** [pachyderm/pachyderm#3063]
**What happened?**:
Deployement following this page fails : http://docs.pachyderm.io/en/latest/deployment/azure.html

Everything seems fine until we check the kubernetes dashboard.

The pachd pod displays the following error:

```
MountVolume.SetUp failed for volume "pachyderm-storage-secret" : secrets "pachyderm-storage-secret" not found 
Readiness probe failed: context deadline exceeded
```

After deleting the pachd pod so it restarts it only displays

```
Readiness probe failed: context deadline exceeded
```

No logs, no previous logs, no way to connect with pachctl.

I tried to scale the pods to see if it was a machine problem.

All three pods on three different machine fail.

**What you expected to happen?**:

I expected the deploy to work out of the box.

**How to reproduce it (as minimally and precisely as possible)?**:

Create a kubernetes cluster with 3 nodes "Standard_DS4_v2" in the "eastus2" zone.
Deploy pachyderm to it.

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Pachyderm CLI version (use `pachctl version`): pachctl version display only the client version : 1.7.4
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): Azure
- OS (e.g. from /etc/os-release): Azure os, i'm not sure wich linux distribution they use
- Others:

**Comment by SkinyMonkey** [comment]
I jut got some logs from a pachd container : 

```time="2018-07-19T23:16:45Z" level=warning msg="TLS enabled but could not stat public cert at /pachd-tls-cert/tls.crt: &amp;{%!e(string=stat) %!e(string=/pachd-tls-cert/tls.crt) %!e(syscall.Errno=2)}" 
time="2018-07-19T23:16:45Z" level=warning msg="TLS enabled but could not stat private key at /pachd-tls-cert/tls.key: &amp;{%!e(string=stat) %!e(string=/pachd-tls-cert/tls.key) %!e(syscall.Errno=2)}" 
time="2018-07-19T23:17:15Z" level=info msg="error starting githook server context deadline exceeded
" 
panic: could not intiailize Pachyderm client in driver: context deadline exceeded
 goroutine 61 [running]:
github.com/pachyderm/pachyderm/src/server/pfs/server.(*driver).getPachClient.func1()
    /go/src/github.com/pachyderm/pachyderm/src/server/pfs/server/driver.go:160 +0x12d
sync.(*Once).Do(0xc420284520, 0xc42047bf88)
    /usr/local/go/src/sync/once.go:44 +0xbe
github.com/pachyderm/pachyderm/src/server/pfs/server.(*driver).getPachClient(0xc420284510, 0x1d98ce0, 0xc4200400b0, 0xc4201d03c0)
    /go/src/github.com/pachyderm/pachyderm/src/server/pfs/server/driver.go:156 +0x50
github.com/pachyderm/pachyderm/src/server/pfs/server.newDriver.func3(0xc420284510)
    /go/src/github.com/pachyderm/pachyderm/src/server/pfs/server/driver.go:144 +0x43
created by github.com/pachyderm/pachyderm/src/server/pfs/server.newDriver
    /go/src/github.com/pachyderm/pachyderm/src/server/pfs/server/driver.go:144 +0x498```

**Comment by SkinyMonkey** [comment]
In case anyone has the same pb:

I recreated everything from scratch using the az command line tool this time.
After trying 5 times through the dashboard, this time it worked.
