### ISSUE TITLE
Trying to create pipeline with no input crashes pachd

### ISSUE THREAD

**Issue by jdelfino** [pachyderm/pachyderm#3106]
**What happened?**:
I tried to create a pipeline with no input section, and pachd crashed.

Relevant log output:
```
2018-08-03T17:52:40Z INFO pps.API.call64 {"duration":0.000066093,"request":{"pipeline":{"name":"jdelfino_test"},"transform":{"image":"index.docker.io/library/busybox:latest","cmd":["sh","-c","echo foo \u003e /pfs/out/bar"]},"parallelism_spec":{"constant":1},"salt":"fd459c624ccc45eab10d9851c1c322a2"},"response":null} []
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xace826]

goroutine 25948 [running]:
github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pps.VisitInput(0x0, 0xc4218ad728)
        /go/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pps/util.go:16 +0x26
github.com/pachyderm/pachyderm/src/server/pps/server.setPipelineDefaults(0xc421332640)
        /go/src/github.com/pachyderm/pachyderm/src/server/pps/server/api_server.go:1928 +0xb6
github.com/pachyderm/pachyderm/src/server/pps/server.(*apiServer).CreatePipeline(0xc420152140, 0x7fc63754a048, 0xc420b06120, 0xc42042d790, 0x0, 0x0, 0x0)
        /go/src/github.com/pachyderm/pachyderm/src/server/pps/server/api_server.go:1743 +0x534
github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pps._API_CreatePipeline_Handler(0x1b8dd60, 0xc420152140, 0x7fc63754a048, 0xc421ab1e30, 0xc420e936c0, 0x0, 0x0, 0x0, 0xc420505460, 0x0)
        /go/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pps/pps.pb.go:3350 +0x241
github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc42025b1e0, 0x1da5020, 0xc42179e480, 0xc421332500, 0xc420b8c060, 0x2a366e0, 0x0, 0x0, 0x0)
        /go/src/github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/server.go:920 +0x848
github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc.(*Server).handleStream(0xc42025b1e0, 0x1da5020, 0xc42179e480, 0xc421332500, 0x0)
        /go/src/github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/server.go:1142 +0x1318
github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4216471d0, 0xc42025b1e0, 0x1da5020, 0xc42179e480, 0xc421332500)
        /go/src/github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/server.go:637 +0x9f
created by github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /go/src/github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/server.go:635 +0xa1
```

**What you expected to happen?**:
pachd to not crash, and return a helpful error message

**How to reproduce it (as minimally and precisely as possible)?**:
Call `create-pipeline` with this input:

```
{
  "pipeline": {
    "name": "test"
  },
  "transform": {
    "image": "index.docker.io/library/busybox:latest",
    "cmd": ["sh", "-c", "echo foo > /pfs/out/bar"]
  },
  "parallelism_spec": {
    "constant": 1
  }
}
```

**Environment?**:
- Pachyderm CLI version (use `pachctl version`): 1.7.4

**Comment by msteffen** [comment]
Closing—just tested this in 1.9.2 and it no longer seems to be an issue
