### ISSUE TITLE
dashboard issue - No idea whats wrong

### ISSUE THREAD

**Issue by suneeta-mall** [pachyderm/pachyderm#3113]
**What happened?**:
Suddenly dashboard stopped working. Showing 
![main](https://user-images.githubusercontent.com/25972660/43808523-cfb0567c-9af0-11e8-8309-ae285964ce7b.png)
![setting](https://user-images.githubusercontent.com/25972660/43808525-d20bc58c-9af0-11e8-8581-299f0fa0b7f7.png)

~/.pachyderm/config.son shows its caching public DNS of EC2 - I am not sure if thats correct as this address may vary Elastic IP should be used. 
```
{
  "user_id": <>",
  "v1": {
    "pachd_address": "ec2-<>.compute.amazonaws.com:30650",
    "session_token": "<>"
  }
}
```
- So I removed thinking thats the problem. No new config is created but the problem persist
- Clear all browser cache, opened in incongnito mode - problem still persist

According to dashboard pod, everything is chugging along fine:
```
172.30.38.252 - - [07/Aug/2018:23:56:59 +0000] "GET /assets/fonts/Bold/OpenSans-Bold.woff2?v=1.1.0 HTTP/1.1" 200 46676 "http://api.<>:30080/assets/pachdash.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" "-"
172.30.38.252 - - [07/Aug/2018:23:56:59 +0000] "GET /assets/MaterialIcons-Regular.woff2 HTTP/1.1" 200 44300 "http://api.<>:30080/assets/vendor.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" "-"
172.30.38.252 - - [07/Aug/2018:23:56:59 +0000] "GET /assets/fonts/Semibold/OpenSans-Semibold.woff2?v=1.1.0 HTTP/1.1" 200 63728 "http://api.<>:30080/assets/pachdash.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" "-"
```

**What you expected to happen?**:
For dashboard to work or at least have a reason for not working

**How to reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:
see problem description 

**Environment?**:
- Kubernetes version (use `kubectl version`): 
- Pachyderm CLI version (use `pachctl version`): 1.7.5
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by gabrielgrant** [comment]
I haven't seen that `Call dropped by load balancing policy` message before, but it seems to be coming from GRPC. From what i can tell, it seems like the specific error message text may actually be a red-herring that is masking a deeper issue (due to a bug in GPRC that propagates error info incorrectly: https://github.com/grpc/grpc/issues/12506). It seems like the deeper issue may be a leak in the node GRPC implementation (node is used to proxy from a websocket connection from the browser to a GRPC connection to pachd): https://github.com/grpc/grpc/issues/11015

Am i correct in understanding that you didn't touch anything on your end, but rather this seemed to just appear suddenly of it's own accord while you were in the middle of using the dash? (that would be consistent with the theory of a leak in the proxy)

Could you please post the output of `kubectl get all` (i'm curious if the grpc proxy is having trouble), and upload the logs of the grpc-proxy container within the dash pod (if you've been using the dash for a while, those can get quite long, so probably best to dump to a file and attach it here)

It would also be useful to confirm whether the requests are getting to pachd at all (if my theory is right, I'd expect them to not be, but it's also possible the error is coming back from pachd). The easiest way to test this would be to look at the pachd logs with the dash open -- you should see regular requests being made (though also just confirming that `pachctl` commands are working while the dash is failing is a pretty good indication that the issue is on the dash side rather than within pachd)

The other thing to try would be to just restart the proxy container/dash pod. If it's just a leak, I'd expect that when it comes back up it would start working again.

**Comment by gabrielgrant** [comment]
Can you also confirm how you're accessing the dash? (`pachctl port-forward`, public IP, custom-configured domain, etc...)

**Comment by suneeta-mall** [comment]
@gabrielgrant I have a good new and a bad news. The bad news is that I had a incident on cluster and had to recreate everything so I have lost the situation that presented the problem. That means I cant get you any more logs. 

As for `kubectl get all` - it was showing all pods were running okay. None of the pods were reporting any issues or were crashing. You are right in saying that pachd was not getting an action from dash at all. I did bounch back all pods (dash, etcd, pachd) everything else worked fine as before but dashboard still showed the problem. 

As for using port-forward, I was using API Server's Public IP but I did try port-forward too in my curiosity. Both behaved just the same - no joys. If I understand it correctly, I will agree with your reasoning but I am not expert about node side of things. 

Now to *good* news, the dashboard is now working. I think I may know why but there is no certainty to it. So I had enterprise token that I activated it dashboard and then from CLI i activated auth. Dashboard (and everything else was happy). But auth was annoying me so I shut it off from CLI meaning I deactivated auth. But I did nothing with dashboard. Before the auth deactivation from CLI Is last I have known dashboard working. (I dont use dashboard as often whilst in active dev). From this point onward dashboard never worked.

I hope you find some clues to the problem but unfortunately I can no longer provide logs. Having said this the cluster frenzy had nothing to do with dashboard.

**Comment by suneeta-mall** [comment]
<img width="1592" alt="screen shot 2018-08-13 at 9 05 08 pm" src="https://user-images.githubusercontent.com/25972660/44028291-bd5bba02-9f3c-11e8-94e1-aae39643ecd6.png">

@gabrielgrant The dashboard issue started happening again .. this time without doing anything to cluster .. nothing at all... I setup brand new cluster and deployed. Everything was good. Added Enterprise token .. still good .. all pipelines works fine.. 

Left it churning for 3 hours .. all process works perfectly file no crash/hang/caught fire etc .. but dashboard has load balancer policy error now..
Heres kube get all log 
```
NAME                                     READY     STATUS    RESTARTS   AGE
pod/dash-6866f58f7f-vp84q                2/2       Running   0          6h
pod/etcd-0                               1/1       Running   0          6h
pod/pachd-67f659cc9c-s7z9z               1/1       Running   3          6h

NAME                                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                   AGE
service/dash                           NodePort    100.68.235.75    <none>        8080:30080/TCP,8081:30081/TCP                             6h
service/etcd                           NodePort    100.69.223.176   <none>        2379:32385/TCP                                            6h
service/etcd-headless                  ClusterIP   None             <none>        2380/TCP                                                  6h
service/pachd                          NodePort    100.67.108.48    <none>        650:30650/TCP,651:30651/TCP,652:30652/TCP,999:30999/TCP   6h


NAME                    DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/dash    1         1         1            1           6h
deployment.apps/pachd   1         1         1            1           6h

NAME                               DESIRED   CURRENT   READY     AGE
replicaset.apps/dash-6866f58f7f    1         1         1         6h
replicaset.apps/pachd-67f659cc9c   1         1         1         6h

NAME                    DESIRED   CURRENT   AGE
statefulset.apps/etcd   1         1         6h
```
I have removed all pipeline pods from logs but they have been happy. The 3 restarts on pachd was because of 'seg fault on inspect-pipeline` that is known issue and @jdoliner fixed it recently. These crashes were before I left it off churning ...

Again, same issue accessing with port-forward or publicIP

**Comment by suneeta-mall** [comment]
Also same as before, neither pachd nor dash pod get any request from browser

**Comment by gabrielgrant** [comment]
So to confirm:

1. the dashboard was working when first deployed
2. you closed it while running jobs within the cluster for a few hours
3. you re-opened it and saw the above errors

Is that correct?

**Comment by suneeta-mall** [comment]
[logs-from-grpc-proxy-in-dash-6866f58f7f-vp84q.txt](https://github.com/pachyderm/pachyderm/files/2285327/logs-from-grpc-proxy-in-dash-6866f58f7f-vp84q.txt)
Ah yea so user container was not getting requests but grpc proxy dumped these errors. Theres also logs
```
    call_id: 1,
     json_data: '{"stack":"Error: Call dropped by load balancing policy\\n    at /usr/src/app/node_modules/grpc/src/node/src/client.js:554:15","message":"Call dropped by load balancing policy","code":2,"metadata":{"_internal_repr":{}}}',
     event: 'error' } }
sending (post-stringify): %s
'{"call_event":{"service_id":1,"call_id":1,"json_data":"{\\"stack\\":\\"Error: Call dropped by load balancing policy\\\\n    at /usr/src/app/node_modules/grpc/src/node/src/client.js:554:15\\",\\"message\\":\\"Call dropped by load balancing policy\\",\\"code\\":2,\\"metadata\\":{\\"_internal_repr\\":{}}}","event":"error"}}'
sending (pbMessage message): { service_create: null,
  service_release: null,
  call_create: null,
  call_event: 
   { call_id: 1,
     service_id: 1,
     event: 'error',
     json_data: '{"stack":"Error: Call dropped by load balancing policy\\n    at ```


The static resources were browser cached I think. I dont get them in private mode or on cache clear

**Comment by mdaniel** [comment]
I am experiencing this behavior on a non-AWS cluster, poured into 3 virtualbox vms, only in my case the dashboard app never boots up at all

Separately, I was going to file an issue about the verbosity of `grpc-proxy` because wow that thing is chatty. I haven't seen a "normal" `grpc-proxy` to know how much of the verbosity is some kind of debug logging, versus BAU logging, but as someone who egresses all container logs into centralized logging, I am especially sensitive to oppressively chatty containers.

**Comment by gabrielgrant** [comment]
@mdaniel yes, definitely agree that the default verbosity of the grpc proxy is waaaay excessive. this will be fixed in the upcoming 1.8 release which should be shipping in a few weeks (i should also be able to cut a one-off release of the proxy image with this fix that you can upgrade to manually if you'd like)

Can you explain exactly what you mean when you say "the dashboard app never boots up at all"? Do you mean the pod itself never boots, or the dash never loads in the browser? if you can show screenshots of what you're seeing in the browser, the browser error console, and any errors being logged in kubernetes, that would be helpful

**Comment by mdaniel** [comment]
> Can you explain exactly what you mean when you say "the dashboard app never boots up at all"? Do you mean the pod itself never boots, or the dash never loads in the browser? 

The latter of the "or": I see the two screenshots in the issue description upon first connection, and never even knew the dashboard was an Enterprise feature because the app never said anything to me except error messages. The chrome messages are approximately as seen in the screenshots above, and the only thing I've ever seen from the `pachd` Pod is `api.segement.io` timeouts doing DNS lookups. The irony of the environment variable `LOG_LEVEL=debug` for that Pod not saying **anything** is not lost on me.

Its `grpc-proxy` friend actually says entirely too much to capture, but the log output attached in that [`logs-from-grpc-proxy-in-dash-6866f58f7f-vp84q.txt`](https://github.com/pachyderm/pachyderm/files/2285327/logs-from-grpc-proxy-in-dash-6866f58f7f-vp84q.txt) a few comments up is also pretty representative -- a wall of grpc silliness, with perhaps some meaningful error messages cleverly hidden therein. If there's a similar `LOG_LEVEL` knob for it, I'd **very much** welcome knowing what it is and what to set it to in order to produce sane output.
