### ISSUE TITLE
De-flake TestAllDatumsAreProcessed

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#3215]
Got a test flake in TestAllDatumsAreProcessed despite making an unrelated change in https://github.com/pachyderm/pachyderm/pull/3214

```
=== RUN   TestAllDatumsAreProcessed
--- FAIL: TestAllDatumsAreProcessed (0.04s)
    pachyderm_test.go:3289: No error is expected but got  pachyderm/1.7.0/pachyderm_pps/jobs/0cf5b6989eb24be891083079521a4d27 not found
    pachyderm_test.go:3289: current stack:
        goroutine 146 [running]:
        runtime/debug.Stack(0xc0000f2500, 0x1745cf9, 0x1f)
        	/home/travis/.gimme/versions/go1.11.1.linux.amd64/src/runtime/debug/stack.go:24 +0xa7
        github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pkg/require.fatal(0x1940000, 0xc0000f2500, 0x0, 0x0, 0x0, 0x1745cf9, 0x1f, 0xc000474750, 0x1, 0x1)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:430 +0xc5
        github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pkg/require.NoError(0x1940000, 0xc0000f2500, 0x1904720, 0xc000474740, 0x0, 0x0, 0x0)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:310 +0x136
        github.com/pachyderm/pachyderm/src/server.TestAllDatumsAreProcessed(0xc0000f2500)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pachyderm_test.go:3289 +0xcf
        testing.tRunner(0xc0000f2500, 0x17c42d8)
        	/home/travis/.gimme/versions/go1.11.1.linux.amd64/src/testing/testing.go:827 +0xbf
        created by testing.(*T).Run
        	/home/travis/.gimme/versions/go1.11.1.linux.amd64/src/testing/testing.go:878 +0x353
```

**Comment by jdoliner** [comment]
Haven't seen any issues from this test in a while, closing.
