### ISSUE TITLE
assets.go causes index out of range if worker image has no slash

### ISSUE THREAD

**Issue by mdaniel** [pachyderm/pachyderm#3457]
**What happened?**:

```
panic: runtime error: index out of range

goroutine 206 [running]:
github.com/pachyderm/pachyderm/src/server/pkg/deploy/assets.AddRegistry(0x0, 0x0, 0xc00005800d, 0x17, 0x0, 0x0)
	src/github.com/pachyderm/pachyderm/src/server/pkg/deploy/assets/assets.go:1577 +0x349
github.com/pachyderm/pachyderm/src/server/pps/server.(*apiServer).workerPodSpec(0xc0002af680, 0xc0001c3800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	src/github.com/pachyderm/pachyderm/src/server/pps/server/worker_rc.go:168 +0x2807
github.com/pachyderm/pachyderm/src/server/pps/server.(*apiServer).createWorkerRc(0xc0002af680, 0xc0001c3800, 0x7, 0x2)
	src/github.com/pachyderm/pachyderm/src/server/pps/server/worker_rc.go:429 +0x7e
github.com/pachyderm/pachyderm/src/server/pps/server.(*apiServer).upsertWorkersForPipeline.func1(0xc000520cc0, 0xc0008c3670)
	src/github.com/pachyderm/pachyderm/src/server/pps/server/master.go:346 +0x3de
github.com/pachyderm/pachyderm/src/server/pkg/backoff.RetryNotify(0xc0007464a0, 0x22904c0, 0xc000520cc0, 0xc0007464e0, 0x1, 0x1)
	src/github.com/pachyderm/pachyderm/src/server/pkg/backoff/retry.go:35 +0x4a
github.com/pachyderm/pachyderm/src/server/pps/server.(*apiServer).upsertWorkersForPipeline(0xc0002af680, 0xc0003f0b60, 0xc0008c3950, 0x1)
	src/github.com/pachyderm/pachyderm/src/server/pps/server/master.go:293 +0xff
github.com/pachyderm/pachyderm/src/server/pps/server.(*apiServer).master.func1(0x0, 0x0)
	src/github.com/pachyderm/pachyderm/src/server/pps/server/master.go:175 +0xb0b
github.com/pachyderm/pachyderm/src/server/pkg/backoff.RetryNotify(0xc000586be0, 0x22904c0, 0xc0003ca240, 0xc000fc5fb8, 0x2a, 0xc00063a300)
	src/github.com/pachyderm/pachyderm/src/server/pkg/backoff/retry.go:35 +0x4a
github.com/pachyderm/pachyderm/src/server/pps/server.(*apiServer).master(0xc0002af680)
	src/github.com/pachyderm/pachyderm/src/server/pps/server/master.go:49 +0x1af
created by github.com/pachyderm/pachyderm/src/server/pps/server.NewAPIServer
	src/github.com/pachyderm/pachyderm/src/server/pps/server/server.go:76 +0x5e0
```

**What you expected to happen?**:

Continue to use the specified worker image unmolested

**How to reproduce it (as minimally and precisely as possible)?**:

```yaml
env:
- name: WORKER_IMAGE
  value: pachyderm_worker:latest
```

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others: I first noticed this in 3d1c3dcd but that just happened to be `master` at the time I pulled it down, it is [apparently still an issue](https://github.com/pachyderm/pachyderm/blob/master/src/server/pkg/deploy/assets/assets.go#L157)

**Comment by mdaniel** [comment]
If I might point out, there's no reason for that method to do _any_ string manipulation if `registry` is empty, so:
```go
func AddRegistry(registry string, imageName string) string {
    if registry == "" {
        return imageName
    }
}
```
although reasonable people can differ about whether calling `AddRegistry` with a blank registry has any meaning, and thus it's the _caller_ who is in error
