### ISSUE TITLE
List job fails with runtime error

### ISSUE THREAD

**Issue by suneeta-mall** [pachyderm/pachyderm#3492]
**What happened?**:
> pachctl list-job     
```                                      
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/pachyderm/pachyderm/src/server/pps/pretty.PrintJobInfo(0x279b180, 0xc0001495f0, 0xc0004eca80)
	/home/jdoliner/go/src/github.com/pachyderm/pachyderm/src/server/pps/pretty/pretty.go:55 +0x8cd
github.com/pachyderm/pachyderm/src/server/pps/cmds.Cmds.func4.2(0xc0004eca80, 0xc0004eca80, 0x0)
	/home/jdoliner/go/src/github.com/pachyderm/pachyderm/src/server/pps/cmds/cmds.go:158 +0x40
github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client.APIClient.ListJobF(0x6a598a0, 0xc00016c048, 0x6a599a0, 0xc00016c0c0, 0x6a59a68, 0xc00016c140, 0x6a59b00, 0xc00016c148, 0x6a59bc0, 0xc00016c158, ...)
	/home/jdoliner/go/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pps.go:276 +0x19c
github.com/pachyderm/pachyderm/src/server/pps/cmds.Cmds.func4(0x381d5e8, 0x0, 0x0, 0x0, 0x0)
	/home/jdoliner/go/src/github.com/pachyderm/pachyderm/src/server/pps/cmds/cmds.go:157 +0x3ee
github.com/pachyderm/pachyderm/src/server/pkg/cmdutil.RunFixedArgs.func1(0xc00050ad80, 0x381d5e8, 0x0, 0x0)
	/home/jdoliner/go/src/github.com/pachyderm/pachyderm/src/server/pkg/cmdutil/cobra.go:20 +0x117
github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra.(*Command).execute(0xc00050ad80, 0x381d5e8, 0x0, 0x0, 0xc00050ad80, 0x381d5e8)
	/home/jdoliner/go/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra/command.go:572 +0x24a
github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000470480, 0xc00017478f, 0x220dff0, 0xc00017508b)
	/home/jdoliner/go/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra/command.go:658 +0x2cc
github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra.(*Command).Execute(0xc000470480, 0x0, 0x0)
	/home/jdoliner/go/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra/command.go:617 +0x2b
main.main.func1(0x25696a0, 0xc00018e700)
	/home/jdoliner/go/src/github.com/pachyderm/pachyderm/src/server/cmd/pachctl/main.go:21 +0x4a
main.main()
	/home/jdoliner/go/src/github.com/pachyderm/pachyderm/src/server/cmd/pachctl/main.go:22 +0xc3
```
**What you expected to happen?**:

**How to reproduce it (as minimally and precisely as possible)?**:
pachyderm: 1.8.3
**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by jdoliner** [comment]
Hi @suneeta-mall, sorry this is affecting you. I think it's a dupe of #3452 which should be fixed as of 1.8.4. Lemme know if that fixes the issue, if not I'll take another look at this.

**Comment by suneeta-mall** [comment]
@jdelfino Nice! thanks for letting me know .. I will try .4 soon .. ta

**Comment by suneeta-mall** [comment]
1.8.4 worked . ta
