### ISSUE TITLE
Pachyderm slows to a crawl after repeated commands to delete all

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#3891]
**What happened?**: I was working on adding tests to the python client library's PPS functionality. Initially, I had designed the tests to call PPS' `DeleteAll` on every test's setup and teardown. Tests would eventually slow to a crawl (or possibly halt entirely) - to the point where I'd give up after a couple of hours.

Rewriting the tests to not lean on `DeleteAll` avoided this issue. Additionally, this does not seem to be a problem (at least in my tests) for PFS' `DeleteAll` - only PPS'.

**What you expected to happen?**: Repeated calls to `DeleteAll` should not slow down.

**How to reproduce it (as minimally and precisely as possible)?**:

The following will run the old version of PPS tests. Tests will begin, but never complete.

```bash
git clone git@github.com:pachyderm/python-pachyderm.git
cd python-pachyderm
git checkout 7bbb237d3619639a6e10c792d19b9569214b2b9f
make init
tox
```

**Anything else we need to know?**: I ran `pachctl debug dump` once the cluster got into this state and looked through the stacktraces. These two in particular stood out to me:

```
goroutine 188 [select, 9 minutes]:
github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/internal/transport.(*Stream).waitOnHeader(0xc000454200, 0x8, 0x217b080)
    src/github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/internal/transport/transport.go:245 +0xcc
github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/internal/transport.(*Stream).RecvCompress(0xc000454200, 0x8d99e2, 0x1eeee20)
    src/github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/internal/transport/transport.go:256 +0x2b
github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc.(*csAttempt).recvMsg(0xc0001d9a20, 0x21bf240, 0xc0007702a0, 0x0, 0x0, 0x0)
    src/github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/stream.go:850 +0x723
github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc.(*clientStream).RecvMsg.func1(0xc0001d9a20, 0x2, 0x2)
    src/github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/stream.go:715 +0x46
github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc.(*clientStream).withRetry(0xc0001e4d80, 0xc00051eeb8, 0xc00051eea8, 0xc0003ccec0, 0xc0006c0220)
    src/github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/stream.go:571 +0x7f
github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc.(*clientStream).RecvMsg(0xc0001e4d80, 0x21bf240, 0xc0007702a0, 0x0, 0x0)
    src/github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/stream.go:714 +0x116
github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc.invoke(0x261eae0, 0xc000c28700, 0x23630df, 0x1e, 0x217b080, 0xc0006625d0, 0x21bf240, 0xc0007702a0, 0xc0003d4000, 0xc000c2afa0, ...)
    src/github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/call.go:73 +0x141
github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc.(*ClientConn).Invoke(0xc0003d4000, 0x261eae0, 0xc000c28700, 0x23630df, 0x1e, 0x217b080, 0xc0006625d0, 0x21bf240, 0xc0007702a0, 0x3d50100, ...)
    src/github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/call.go:37 +0x1b3
github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc.Invoke(0x261eae0, 0xc000c28700, 0x23630df, 0x1e, 0x217b080, 0xc0006625d0, 0x21bf240, 0xc0007702a0, 0xc0003d4000, 0x3d50100, ...)
    src/github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/call.go:60 +0xc1
github.com/pachyderm/pachyderm/src/server/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb.(*leaseClient).LeaseGrant(0xc00000c1f0, 0x261eae0, 0xc000c28700, 0xc0006625d0, 0x3d50100, 0x3, 0x3, 0x9562be, 0xc0001a8580, 0x24051a8)
    src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:3549 +0xd2
github.com/pachyderm/pachyderm/src/server/vendor/github.com/coreos/etcd/clientv3.(*retryLeaseClient).LeaseGrant.func1(0x261eae0, 0xc000c28700, 0x11, 0xc0001cc000)
    src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/coreos/etcd/clientv3/retry.go:220 +0x80
github.com/pachyderm/pachyderm/src/server/vendor/github.com/coreos/etcd/clientv3.(*Client).newRetryWrapper.func1(0x261eae0, 0xc000c28700, 0xc000c28740, 0x40bb00, 0xc000c28740, 0x40)
    src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/coreos/etcd/clientv3/retry.go:93 +0x115
github.com/pachyderm/pachyderm/src/server/vendor/github.com/coreos/etcd/clientv3.(*Client).newAuthRetryWrapper.func1(0x261eae0, 0xc000c28700, 0xc000c28740, 0x40c400, 0x10, 0x2067500)
    src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/coreos/etcd/clientv3/retry.go:117 +0xad
github.com/pachyderm/pachyderm/src/server/vendor/github.com/coreos/etcd/clientv3.(*retryLeaseClient).LeaseGrant(0xc0002307e0, 0x261eae0, 0xc000c28700, 0xc0006625d0, 0x3d50100, 0x3, 0x3, 0x40c468, 0x20, 0x20b7c00)
    src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/coreos/etcd/clientv3/retry.go:219 +0xf6
github.com/pachyderm/pachyderm/src/server/vendor/github.com/coreos/etcd/clientv3.(*lessor).Grant(0xc000256320, 0x261eae0, 0xc000c28700, 0xf, 0x120, 0x118, 0x2318520)
    src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/coreos/etcd/clientv3/lease.go:213 +0x98
github.com/pachyderm/pachyderm/src/server/vendor/github.com/coreos/etcd/clientv3/concurrency.NewSession(0xc000338000, 0xc0003cd548, 0x2, 0x2, 0x2318520, 0x189d701, 0xc0002a1e60)
    src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/coreos/etcd/clientv3/concurrency/session.go:46 +0x307
github.com/pachyderm/pachyderm/src/server/pkg/dlock.(*etcdImpl).Lock(0xc000792120, 0x261eae0, 0xc000c28700, 0xc0002a1e60, 0xc0006c01b0, 0x25ec360, 0xc00004a590)
    src/github.com/pachyderm/pachyderm/src/server/pkg/dlock/dlock.go:42 +0xa2
github.com/pachyderm/pachyderm/src/server/pps/server.(*apiServer).master.func1(0x0, 0x0)
    src/github.com/pachyderm/pachyderm/src/server/pps/server/master.go:60 +0x18b
github.com/pachyderm/pachyderm/src/server/pkg/backoff.RetryNotify(0xc0006828c0, 0x25f3de0, 0xc00071e900, 0xc00051ffb8, 0x2a, 0xc0002686c0)
    src/github.com/pachyderm/pachyderm/src/server/pkg/backoff/retry.go:35 +0x4a
github.com/pachyderm/pachyderm/src/server/pps/server.(*apiServer).master(0xc0001e5680)
    src/github.com/pachyderm/pachyderm/src/server/pps/server/master.go:53 +0x252
created by github.com/pachyderm/pachyderm/src/server/pps/server.NewAPIServer
    src/github.com/pachyderm/pachyderm/src/server/pps/server/server.go:67 +0x3ce
goroutine 244 [chan receive, 17 minutes]:
github.com/pachyderm/pachyderm/src/server/vendor/github.com/coreos/etcd/clientv3/concurrency.waitDelete(0x261eae0, 0xc000641000, 0xc000338000, 0xc000660340, 0x3b, 0x6, 0x0, 0x0)
    src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/coreos/etcd/clientv3/concurrency/key.go:32 +0x1dd
github.com/pachyderm/pachyderm/src/server/vendor/github.com/coreos/etcd/clientv3/concurrency.waitDeletes(0x261eae0, 0xc000641000, 0xc000338000, 0xc00044e1b0, 0x2b, 0x5, 0xc00044e1e0, 0x2b, 0x30)
    src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/coreos/etcd/clientv3/concurrency/key.go:61 +0x1c7
github.com/pachyderm/pachyderm/src/server/vendor/github.com/coreos/etcd/clientv3/concurrency.(*Mutex).Lock(0xc00071ccc0, 0x261eae0, 0xc000641000, 0x233364e, 0x1)
    src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/coreos/etcd/clientv3/concurrency/mutex.go:70 +0x735
github.com/pachyderm/pachyderm/src/server/pkg/dlock.(*etcdImpl).Lock(0xc000786480, 0x261eae0, 0xc000641000, 0xc00014b200, 0xc0006954c0, 0x962ab6, 0x261eb60)
    src/github.com/pachyderm/pachyderm/src/server/pkg/dlock/dlock.go:48 +0x1bf
github.com/pachyderm/pachyderm/src/server/pps/server.(*apiServer).master.func1(0x0, 0x0)
    src/github.com/pachyderm/pachyderm/src/server/pps/server/master.go:60 +0x18b
github.com/pachyderm/pachyderm/src/server/pkg/backoff.RetryNotify(0xc0006b9440, 0x25f3de0, 0xc0004ea300, 0xc00082bfb8, 0x2a, 0xc00071fc20)
    src/github.com/pachyderm/pachyderm/src/server/pkg/backoff/retry.go:35 +0x4a
github.com/pachyderm/pachyderm/src/server/pps/server.(*apiServer).master(0xc0001e5200)
    src/github.com/pachyderm/pachyderm/src/server/pps/server/master.go:53 +0x252
created by github.com/pachyderm/pachyderm/src/server/pps/server.NewAPIServer
    src/github.com/pachyderm/pachyderm/src/server/pps/server/server.go:67 +0x3ce
```

**Environment?**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Pachyderm CLI version (use `pachctl version`):
```
COMPONENT           VERSION                                          
pachctl             1.9.0-7e5839025c45dda6d1189f2679c8de690e5cd7c2   
pachd               1.9.0-7e5839025c45dda6d1189f2679c8de690e5cd7c2   
```
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): docker for mac
- OS (e.g. from /etc/os-release): macOS

**Comment by jdoliner** [comment]
I'm going to move this to medium priority, given that there isn't a really a reason for someone to repeatedly call `delete all` I think it's lower priority than some of our other medium priority issues. Still worrisome though, since there might be other ways to get in this state.

**Comment by ysimonson** [comment]
I think there are other ways to get into this state without repeated calls to delete all, though I don't have a clean, reproducible example. When doing dev work on my laptop (mbp / docker for mac), I have to completely wipe out the cluster every time before deploying at this point, as there's something about s3gateway's conformance tests that seem to trigger the same issue.

**Comment by ysimonson** [comment]
This seems to be improved when upping the memory allocation for the VM from its default of 2gb.
