### ISSUE TITLE
panic deleting deleted pipeline

### ISSUE THREAD

**Issue by danielefranceschi** [pachyderm/pachyderm#3965]
**What happened?**:
Panic (and pachd restart) when deleting an already-deleted pipeline:
```
2019-08-05T14:54:45Z INFO pps.API.func1 {"request":{"pipeline":{"name":"default-nlp"}}} []
2019-08-05T14:54:45Z INFO authclient.API.LogReq {"request":{}} []
2019-08-05T14:54:45Z INFO pfs.API.func1 {"request":{"branch":{"repo":{"name":"__spec__"},"name":"default-nlp"}}} []
2019-08-05T14:54:45Z ERROR pfs.API.InspectBranch {"duration":0.001308371,"error":"/pachyderm_pfs/branches/__spec__/ default-nlp not found","request":{"branch":{"repo":{"name":"__spec__"},"name":"default-nlp"}},"response":null} []
2019-08-05T14:54:45Z INFO pps.API.gopanic {"duration":0.020696716,"request":{"pipeline":{"name":"default-nlp"}},"response":null} []
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1e96b2d]
goroutine 330 [running]:
github.com/pachyderm/pachyderm/src/server/pps/server.(*apiServer).cleanUpSpecBranch(0xc0001ce360, 0xc0002b8ea0, 0xc00067a0a0, 0xb, 0xc0003d58c0, 0x28d4a40)
src/github.com/pachyderm/pachyderm/src/server/pps/server/api_server.go:2345 +0xed
github.com/pachyderm/pachyderm/src/server/pps/server.(*apiServer).deletePipeline(0xc0001ce360, 0xc0002b8ea0, 0xc000ce64e0, 0xc0002b8ea0, 0xc00083b8b8, 0xc00083b8c0)
src/github.com/pachyderm/pachyderm/src/server/pps/server/api_server.go:2364 +0x15b
github.com/pachyderm/pachyderm/src/server/pps/server.(*apiServer).DeletePipeline(0xc0001ce360, 0x29287a0, 0xc000ce64b0, 0xc000ce64e0, 0x0, 0x0, 0x0)
src/github.com/pachyderm/pachyderm/src/server/pps/server/api_server.go:2335 +0x343
github.com/pachyderm/pachyderm/src/client/pps._API_DeletePipeline_Handler.func1(0x29287a0, 0xc000ce64b0, 0x23bc300, 0xc000ce64e0, 0x23bc300, 0xc000ce64e0, 0x0, 0x0)
src/github.com/pachyderm/pachyderm/src/client/pps/pps.pb.go:5882 +0x86
github.com/opentracing-contrib/go-grpc.OpenTracingServerInterceptor.func1(0x29287a0, 0xc000ce64b0, 0x23bc300, 0xc000ce64e0, 0xc000b7c220, 0xc000b7c240, 0x0, 0x0, 0x28cfc60, 0xc00020a3d0)
pkg/mod/github.com/opentracing-contrib/go-grpc@v0.0.0-20180928155321-4b5a12d3ff02/server.go:44 +0x9db
github.com/pachyderm/pachyderm/src/client/pps._API_DeletePipeline_Handler(0x246efc0, 0xc0001ce360, 0x29287a0, 0xc000ce64b0, 0xc0000ee690, 0xc000228020, 0x29287a0, 0xc000ce64b0, 0xc00067a090, 0xf)
src/github.com/pachyderm/pachyderm/src/client/pps/pps.pb.go:5884 +0x158
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00009fc80, 0x29569c0, 0xc000551e00, 0xc000e0c000, 0xc000d32450, 0x3f67448, 0x0, 0x0, 0x0)
pkg/mod/google.golang.org/grpc@v1.21.1/server.go:998 +0x470
google.golang.org/grpc.(*Server).handleStream(0xc00009fc80, 0x29569c0, 0xc000551e00, 0xc000e0c000, 0x0)
pkg/mod/google.golang.org/grpc@v1.21.1/server.go:1278 +0xda6
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0006a2030, 0xc00009fc80, 0x29569c0, 0xc000551e00, 0xc000e0c000)
pkg/mod/google.golang.org/grpc@v1.21.1/server.go:717 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
pkg/mod/google.golang.org/grpc@v1.21.1/server.go:715 +0xa1 
```

**What you expected to happen?**:
Nothing except an error message.

**How to reproduce it (as minimally and precisely as possible)?**:
Create a (long-running) pipeline, delete it via `pachctl` while running, try to delete it again.

**Anything else we need to know?**:
Pipeline's `ReplicationController` has been scaled to 0 but *not deleted*. The same error occurs after manual RC deletion.

**Environment?**:
- Kubernetes version: 1.15.1
- Pachyderm CLI and pachd server version: 1.9.2
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): on-premise k8s via kubeadm
- OS (e.g. from /etc/os-release): Centos7

**Comment by JoeyZwicker** [comment]
hi @danielefranceschi I was easily able to repro this, definitely not a situation where we should be panicing. Thanks for submitting, we'll get it fixed shortly.
