### ISSUE TITLE
Run pipelines crashes pachd and has usability issues

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#3985]
**What happened?**:
Was working to repro a user issue and stumbled across a number of problems with run pipeline.

Passing no commit arguments actually works perfectly fine as expected:

```
JosephZckersMBP:~ joeyzwicker$ pc list job
ID                               PIPELINE STARTED            DURATION  RESTART PROGRESS  DL       UL       STATE
ea2aad2e9bf243a49534eff07d30e911 montage  About a minute ago 3 seconds 0       1 + 0 / 1 371.9KiB 1.283MiB success
0f4f5b49f69848668470d491b79b4ca0 montage  About a minute ago 1 second  0       1 + 0 / 1 79.49KiB 378.6KiB success
036604d05a6b450cac8d2b84cbdac02d edges    About a minute ago 7 seconds 0       2 + 1 / 3 181.1KiB 111.4KiB success
cf3c321294d649788c1d38bf9380ca4f edges    About a minute ago 2 seconds 0       1 + 0 / 1 57.27KiB 22.22KiB success
JosephZckersMBP:~ joeyzwicker$ pc run pipeline edges
JosephZckersMBP:~ joeyzwicker$ pc list job
ID                               PIPELINE STARTED            DURATION           RESTART PROGRESS  DL       UL       STATE
7728b650c5ca4527807326098d5d49d9 montage  1 second ago       Less than a second 0       0 + 1 / 1 0B       0B       success
a250873c4aea4337ad5b5e7a2deee98b edges    1 second ago       Less than a second 0       0 + 3 / 3 0B       0B       success
ea2aad2e9bf243a49534eff07d30e911 montage  About a minute ago 3 seconds          0       1 + 0 / 1 371.9KiB 1.283MiB success
0f4f5b49f69848668470d491b79b4ca0 montage  2 minutes ago      1 second           0       1 + 0 / 1 79.49KiB 378.6KiB success
036604d05a6b450cac8d2b84cbdac02d edges    2 minutes ago      7 seconds          0       2 + 1 / 3 181.1KiB 111.4KiB success
cf3c321294d649788c1d38bf9380ca4f edges    2 minutes ago      2 seconds          0       1 + 0 / 1 57.27KiB 22.22KiB success
```

1. Running what seems to be the correct usage of the command does not correctly spawn a job:
```
JosephZckersMBP:~ joeyzwicker$ pc list commit images@master
REPO   BRANCH COMMIT                           PARENT                           STARTED        DURATION           SIZE
images master 882b339962914e6fb00ceabde1d5cdf4 de9f7d6941ab42a1970b3fc2257280fb 25 minutes ago Less than a second 238.3KiB
images master de9f7d6941ab42a1970b3fc2257280fb <none>                           25 minutes ago Less than a second 57.27KiB
JosephZckersMBP:~ joeyzwicker$ pc run pipeline edges de9f7d6941ab42a1970b3fc2257280fb
JosephZckersMBP:~ joeyzwicker$ pc list job
ID                               PIPELINE STARTED        DURATION           RESTART PROGRESS  DL       UL       STATE
7728b650c5ca4527807326098d5d49d9 montage  20 minutes ago Less than a second 0       0 + 1 / 1 0B       0B       success
a250873c4aea4337ad5b5e7a2deee98b edges    20 minutes ago Less than a second 0       0 + 3 / 3 0B       0B       success
ea2aad2e9bf243a49534eff07d30e911 montage  21 minutes ago 3 seconds          0       1 + 0 / 1 371.9KiB 1.283MiB success
0f4f5b49f69848668470d491b79b4ca0 montage  22 minutes ago 1 second           0       1 + 0 / 1 79.49KiB 378.6KiB success
036604d05a6b450cac8d2b84cbdac02d edges    22 minutes ago 7 seconds          0       2 + 1 / 3 181.1KiB 111.4KiB success
cf3c321294d649788c1d38bf9380ca4f edges    22 minutes ago 2 seconds          0       1 + 0 / 1 57.27KiB 22.22KiB success
```

2. I tried to use what I thought should actually be the correct command (more on this later) and pachd crashed:
```
JosephZckersMBP:~ joeyzwicker$ pc run pipeline edges images@de9f7d6941ab42a1970b3fc2257280fb
JosephZckersMBP:~ joeyzwicker$ pc list job
ERROR: logging before flag.Parse: E0807 17:50:34.474877    2926 portforward.go:391] an error occurred forwarding 30650 -> 650: error forwarding port 650 to pod ed30eb00080614792fba03fbcf5fc280bd9934cf022669df0dfb3c7a5f617f2a, uid : exit status 1: 2019/08/08 00:50:34 socat[10681] E connect(6, AF=2 127.0.0.1:650, 16): Connection refused
```
pachd logs:
```
2019-08-08T00:34:56Z INFO pfs.API.InspectCommit {"duration":0.001070679,"request":{"commit":{"repo":{"name":"__spec__"},"id":"98df737c0fe549adb6d1c424aac161d3"}},"response":{"commit":{"repo":{"name":"__spec__"},"id":"98df737c0fe549adb6d1c424aac161d3"},"branch":{"repo":{"name":"__spec__"},"name":"edges"},"origin":{},"started":{"seconds":1565223826,"nanos":465608665},"finished":{"seconds":1565223826,"nanos":476084572},"size_bytes":165,"subvenance":[{"lower":{"repo":{"name":"edges"},"id":"cd42fe4c551f473199eb95813713503e"},"upper":{"repo":{"name":"edges"},"id":"fe59fa9e903240559bba5263a77d8acd"}},{"lower":{"repo":{"name":"edges"},"id":"d429f054ba834c068f9ed89650b16273"},"upper":{"repo":{"name":"edges"},"id":"c048397b34964c96a6848c84cec40dbb"}},{"lower":{"repo":{"name":"montage"},"id":"809a3db6dcd3499db30d628159b813ec"},"upper":{"repo":{"name":"montage"},"id":"b6b231be65354ea4a38ac151bca882ac"}},{"lower":{"repo":{"name":"edges"},"id":"bd51608c7ab844f590e67566d0eebfbb"},"upper":{"repo":{"name":"edges"},"id":"bd51608c7ab844f590e67566d0eebfbb"}}],"tree":{"hash":"753bc2ae6790dd65a488ae1311d49edf16c6b5e8f3ad9da8e72320a3e5c070ceec807b2b3ecf2b98ab95bfe430b2482bb087bfda6dac1f9604aa591471d36169"}}} []
2019-08-08T00:34:56Z INFO pps.API.gopanic {"duration":0.196072409,"request":{"pipeline":{"name":"edges"},"provenance":[{"commit":{"repo":{"name":"fe59fa9e903240559bba5263a77d8acd"}}}]},"response":null} []
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e98b1d]

goroutine 646 [running]:
github.com/pachyderm/pachyderm/src/server/pps/server.(*apiServer).RunPipeline(0xc0000cbc20, 0x29287a0, 0xc0006e6930, 0xc000a106c0, 0x0, 0x0, 0x0)
	src/github.com/pachyderm/pachyderm/src/server/pps/server/api_server.go:2593 +0x4bd
github.com/pachyderm/pachyderm/src/client/pps._API_RunPipeline_Handler.func1(0x29287a0, 0xc0006e6720, 0x23a6da0, 0xc000a106c0, 0x23a6da0, 0xc000a106c0, 0x0, 0x0)
	src/github.com/pachyderm/pachyderm/src/client/pps/pps.pb.go:5936 +0x89
github.com/opentracing-contrib/go-grpc.OpenTracingServerInterceptor.func1(0x29287a0, 0xc0006e6720, 0x23a6da0, 0xc000a106c0, 0xc000781400, 0xc000781420, 0x0, 0x0, 0x28cfc60, 0xc0001c6490)
	pkg/mod/github.com/opentracing-contrib/go-grpc@v0.0.0-20180928155321-4b5a12d3ff02/server.go:44 +0x9db
github.com/pachyderm/pachyderm/src/client/pps._API_RunPipeline_Handler(0x246efc0, 0xc0000cbc20, 0x29287a0, 0xc0006e6720, 0xc00001c9b0, 0xc00000d6e0, 0x29287a0, 0xc0006e6720, 0xc0009c2580, 0x31)
	src/github.com/pachyderm/pachyderm/src/client/pps/pps.pb.go:5938 +0x158
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000336600, 0x29569c0, 0xc0008f9800, 0xc0008f6600, 0xc0005b60f0, 0x3f67490, 0x0, 0x0, 0x0)
	pkg/mod/google.golang.org/grpc@v1.21.1/server.go:998 +0x470
google.golang.org/grpc.(*Server).handleStream(0xc000336600, 0x29569c0, 0xc0008f9800, 0xc0008f6600, 0x0)
	pkg/mod/google.golang.org/grpc@v1.21.1/server.go:1278 +0xda6
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0008fa850, 0xc000336600, 0x29569c0, 0xc0008f9800, 0xc0008f6600)
	pkg/mod/google.golang.org/grpc@v1.21.1/server.go:717 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
	pkg/mod/google.golang.org/grpc@v1.21.1/server.go:715 +0xa1
```

3. The syntax for run pipeline seems inconsistent and confusing in a number of ways. 
- Help docs say `pachctl run pipeline <pipeline> [commits...] [flags]`. I dont think we have anything else in the API where you just pass commitID instead of `<repo>@<commit or branch>`. IMO it should clearly be `run pipeline edges images@1234` or `run pipeline montage images@1234 edges@5678`. Also, the current syntax as is can't really work with branches, can it? What would `run pipeline montage master^` mean since we're not specifying a repo?
- Help docs say:
```
		# Reprocess the pipeline "filter" on the data from commits a23e4 and bf363
		$ pachctl run pipeline filter a23e4 and bf363
```
but there clearly shouldn't be an "and" in the actual command. It's easy enough to fix this when we fix the syntax and rest of the run pipeline help docs. Just making a note of it here. Also, it clearly shouldn't say `Reprocess the pipeline "filter"` because run pipeline does not "reprocess"
- Help docs should clarify that the `<repo>@<commit or branch>` is the input repos to the pipeline. While yes, it's obvious that that makes logical sense, both myself and a user independently made the mistake of using a commitID from the output repo. This is just a minor docs thing, but #5 below will also help. 
-  Help docs should note that for any input commits that are not specified, run pipeline defaults to using HEAD of master.

4. Speaking of....Run pipeline should have a `--reprocess` flag. Otherwise run pipeline on any previously successful job does nothing. I understand there might be implementation complications of this feature, but we have enough evidence now that this is what users _think_ `run pipeline` should be doing -- it's probably reasonable for that not to be the default, but should be an option. 

5. If I use invalid arguments such as specifying a commit or pipeline that doesn't exist, the command should clearly error, but right now just fails silently (or causes the panic above in some cases):
```
# there is no such pipeline as edges@...
joeyzwicker$ pc run pipeline edges@fe59fa9e903240559bba5263a77d8acd

# there is no commit fe59... on repo edges
$ pc run pipeline edges fe59fa9e903240559bba5263a77d8acd
```

6. Just a question: what does run pipeline do if called on a spout, which has no inputs? If called on a pipeline with cron inputs, running against the most recent tick seems consistent, but I would imagine the most expected behavior for users would be that, alternatively, this could serve as a way to do a "manual tick", which users have asked for. 

**What you expected to happen?**:

**How to reproduce it (as minimally and precisely as possible)?**:
Opencv and then do the above steps. 

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.9.2
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by JoeyZwicker** [comment]
@adelelopez does https://github.com/pachyderm/pachyderm/pull/4060 address some or all of this things in this issue as well?

**Comment by adelelopez** [comment]
Yes

**Comment by nitinjainsj** [comment]
@adelelopez Have we addressed all the issues here? If yes, let's close this issue.

**Comment by adelelopez** [comment]
I think we've addressed everything except for point number 4.
