### ISSUE TITLE
TestSpout yields occasional consistency error in CI

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#4226]
--- FAIL: TestSpout (103.06s)
    --- PASS: TestSpout/SpoutBasic (20.72s)
    --- PASS: TestSpout/SpoutOverwrite (19.45s)
    --- PASS: TestSpout/SpoutProvenance (41.78s)
    --- PASS: TestSpout/ServiceSpout (20.14s)
    pachyderm_test.go:9440: No error is expected but got consistency error: the commit 151e98e7618b45048ca7aaecc277508e in repo pipelineservicespout3a4bb4a2f50e could not be found while checking subvenance for provenance-subvenance duality (=>)
    pachyderm_test.go:9440: current stack:
        goroutine 2569 [running]:
        runtime/debug.Stack(0xc0000d4300, 0x1e93f7b, 0x1f)
        	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/runtime/debug/stack.go:24 +0x9d
        github.com/pachyderm/pachyderm/src/client/pkg/require.fatal(0x22112e0, 0xc0000d4300, 0x0, 0x0, 0x0, 0x1e93f7b, 0x1f, 0xc00041f810, 0x1, 0x1)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:442 +0xbf
        github.com/pachyderm/pachyderm/src/client/pkg/require.NoError(0x22112e0, 0xc0000d4300, 0x218fd80, 0xc00041f7f0, 0x0, 0x0, 0x0)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:310 +0x119
        github.com/pachyderm/pachyderm/src/server.TestSpout(0xc0000d4300)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pachyderm_test.go:9440 +0x385
        testing.tRunner(0xc0000d4300, 0x1f2a308)
        	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/testing/testing.go:909 +0xc9
        created by testing.(*T).Run
        	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/testing/testing.go:960 +0x350

**Comment by msteffen** [comment]
Just saw this again with TestSpoutMarker:
```
--- FAIL: TestSpout (137.16s)
    --- PASS: TestSpout/SpoutBasic (21.17s)
    --- PASS: TestSpout/SpoutOverwrite (19.76s)
    --- PASS: TestSpout/SpoutProvenance (43.36s)
    --- PASS: TestSpout/ServiceSpout (20.09s)
    --- PASS: TestSpout/SpoutMarker (31.37s)
    pachyderm_test.go:9671: No error is expected but got consistency error: the commit d78c5645df5d4657b2f5c84714d27e23 in repo pipelinespoutdownstream3eb6baf0a02a could not be found while checking subvenance for provenance-subvenance duality (=>)
    pachyderm_test.go:9671: current stack:
        goroutine 3813 [running]:
        runtime/debug.Stack(0xc0001da300, 0x200190e, 0x1f)
        	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/runtime/debug/stack.go:24 +0x9d
        github.com/pachyderm/pachyderm/src/client/pkg/require.fatal(0x23b4fe0, 0xc0001da300, 0x0, 0x0, 0x0, 0x200190e, 0x1f, 0xc000726990, 0x1, 0x1)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:442 +0xbf
        github.com/pachyderm/pachyderm/src/client/pkg/require.NoError(0x23b4fe0, 0xc0001da300, 0x2329aa0, 0xc000726970, 0x0, 0x0, 0x0)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:310 +0x119
        github.com/pachyderm/pachyderm/src/server.TestSpout(0xc0001da300)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pachyderm_test.go:9671 +0x3e8
        testing.tRunner(0xc0001da300, 0x20a3358)
        	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/testing/testing.go:909 +0xc9
        created by testing.(*T).Run
        	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/testing/testing.go:960 +0x350
```

**Comment by msteffen** [comment]
@adelelopez I assigned this to you because you're the spouts expert, but I'm not sure how big a deal this is in the grand scheme of things
