### ISSUE TITLE
segfault after update on stopped pipeline

### ISSUE THREAD

**Issue by suneeta-mall** [pachyderm/pachyderm#4273]
On 1.9.7,

Stop a pipeline and attempt to update stopped pipeline. After this any attempt to work with any pipelines leads to following segfault
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x264c40a]

goroutine 1 [running]:
github.com/pachyderm/pachyderm/src/server/pps/cmds.pipelineHelper(0xc000000000, 0x2abec9d, 0x9, 0x0, 0x0, 0x7ffeefbff5d3, 0x2f, 0x40dbd00, 0x0, 0x0)
	src/server/pps/cmds/cmds.go:836 +0x25a
github.com/pachyderm/pachyderm/src/server/pps/cmds.Cmds.func10(0xc0006027a0, 0x0, 0x2, 0x40dbdc8, 0xc000543d68)
	src/server/pps/cmds/cmds.go:466 +0x84
github.com/pachyderm/pachyderm/src/server/pkg/cmdutil.RunFixedArgs.func1(0xc000600d80, 0xc0006027a0, 0x0, 0x2)
	src/server/pkg/cmdutil/cobra.go:24 +0x136
github.com/spf13/cobra.(*Command).execute(0xc000600d80, 0xc000602720, 0x2, 0x2, 0xc000600d80, 0xc000602720)
	/home/jdoliner/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20160607124346-1238ba19d24b/command.go:572 +0x247
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000ded80, 0x2b8aeb0, 0x40dbfa8, 0x2b8aeb8)
	/home/jdoliner/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20160607124346-1238ba19d24b/command.go:658 +0x2be
github.com/spf13/cobra.(*Command).Execute(...)
	/home/jdoliner/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20160607124346-1238ba19d24b/command.go:617
main.main.func1(0x0, 0x0)
	src/server/cmd/pachctl/main.go:20 +0x4c
main.main()
	src/server/cmd/pachctl/main.go:21 +0xbb
```

**Comment by jdoliner** [comment]
The code that's segfaulting here is:

```golang
		if ctx, ok := extended.StartAnyExtendedTrace(client.Ctx(), "/pps.API/CreatePipeline", request.Pipeline.Name); ok {
			client = client.WithCtx(ctx)
		}
```

it seems unlikely that this is due to state in pachd since this code occurs before it sends any requests. It might be something weird going on with the trace system @msteffen would know more about that. But the simplest explanation is that the `pipeline` section of the pipeline spec isn't being set, is that possible?

**Comment by izapolsk** [comment]
the issue is still present in 1.12.4. 
I can easily reproduce it by running 

1. `pachctl stop pipeline push2db`
2. `pachctl update pipeline -f push2db.pipeline`
3. ```
git:(dev) ✗ pachctl run pipeline push2db add-mappings@7eff3de0b04845ebac007e174208bf21
upstream connect error or disconnect/reset before headers. reset reason: connection termination
```

And the following I see in logs of crashed pachd

```
2021-03-09T16:55:20Z INFO pfs.API.InspectCommit {"duration":0.00162093,"request":{"commit":{"repo":{"name":"add-mappings"},"id":"7eff3de0b04845ebac007e174208bf21"}},"response":{"commit":{"repo":{"name":"add-mappings"},"id":"7ef]
2021-03-09T16:55:20Z INFO pps.API.gopanic {"duration":0.018330475,"request":{"pipeline":{"name":"push2db"},"provenance":[{"commit":{"repo":{"name":"add-mappings"},"id":"7eff3de0b04845ebac007e174208bf21"},"branch":{"repo":{"name":"ad]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x27f3031]

goroutine 525072 [running]:
github.com/pachyderm/pachyderm/src/server/pps/server.(*apiServer).RunPipeline(0xc000326480, 0x330c8e0, 0xc0010192c0, 0xc00193aaa0, 0x0, 0x0, 0x0)
        /app/src/server/pps/server/api_server.go:3401 +0x8d1
github.com/pachyderm/pachyderm/src/client/pps._API_RunPipeline_Handler.func1(0x330c8e0, 0xc001019110, 0x2dcd0a0, 0xc00193aaa0, 0x2dcd0a0, 0xc00193aaa0, 0x0, 0x0)
        /app/src/client/pps/pps.pb.go:6998 +0x8b
github.com/opentracing-contrib/go-grpc.OpenTracingServerInterceptor.func1(0x330c8e0, 0xc001019110, 0x2dcd0a0, 0xc00193aaa0, 0xc0021c2280, 0xc0021c22a0, 0x0, 0x0, 0x328ea40, 0xc0003057b0)
        /go/pkg/mod/github.com/opentracing-contrib/go-grpc@v0.0.0-20180928155321-4b5a12d3ff02/server.go:44 +0xa31
github.com/pachyderm/pachyderm/src/client/pps._API_RunPipeline_Handler(0x2ed8660, 0xc000326480, 0x330c8e0, 0xc001019110, 0xc00094d320, 0xc000696520, 0x330c8e0, 0xc001019110, 0xc000b96d80, 0x5d)
        /app/src/client/pps/pps.pb.go:7000 +0x150
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000682780, 0x332a540, 0xc001730600, 0xc0017f4900, 0xc0008d0510, 0x472f430, 0x0, 0x0, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1024 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc000682780, 0x332a540, 0xc001730600, 0xc0017f4900, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1313 +0xd34
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0011f4400, 0xc000682780, 0x332a540, 0xc001730600, 0xc0017f4900)
        /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:722 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:720 +0xa5

```

**Comment by izapolsk** [comment]
@mindthevirt, there is plenty of memory and there is no memory pressure on the cluster.
this pipeline has parallelism set to 10 and also it has standby=true.

I reproduced this issue with this and other pipelines up to 10 times. 
the issue occurs every time when I  run `pachctl run pipeline` on stopped pipeline. it seems update pipeline isn't necessary.
