### ISSUE TITLE
Calling `DeleteRepo` without arguments triggers a panic

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#4279]
I'm assuming this is a bug, because even though it's a bad gRPC call, we probably shouldn't ever panic pachd.

```
2019-10-30T18:07:39Z INFO pfs.API.DeleteRepo {"request":{}} []
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1ea5c79]

goroutine 31422 [running]:
github.com/pachyderm/pachyderm/src/server/pkg/collection.runSTM.func1.1(0xc0003d24e0)
	src/github.com/pachyderm/pachyderm/src/server/pkg/collection/transaction.go:113 +0xb3
panic(0x21b6520, 0x420e750)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/pachyderm/pachyderm/src/server/pfs/server.(*driver).deleteRepo(0xc0002f8780, 0xc000d86180, 0x0, 0xc00087e700, 0x24554e0, 0xc00087e4e0)
	src/github.com/pachyderm/pachyderm/src/server/pfs/server/driver.go:953 +0xa9
github.com/pachyderm/pachyderm/src/server/pfs/server.(*apiServer).DeleteRepoInTransaction(0xc00026f880, 0xc000d86180, 0xc00087e720, 0xc00087e720, 0x0)
	src/github.com/pachyderm/pachyderm/src/server/pfs/server/api_server.go:137 +0x92
github.com/pachyderm/pachyderm/src/server/pkg/transactionenv.(*directTransaction).DeleteRepo(0xc0005c8b50, 0xc00087e4e0, 0x40c301, 0xc0005c8b50)
	src/github.com/pachyderm/pachyderm/src/server/pkg/transactionenv/env.go:191 +0x79
github.com/pachyderm/pachyderm/src/server/pfs/server.(*apiServer).DeleteRepo.func3(0x2a02300, 0xc0005c8b50, 0x2371540, 0x2324401)
	src/github.com/pachyderm/pachyderm/src/server/pfs/server/api_server.go:146 +0x3a
github.com/pachyderm/pachyderm/src/server/pkg/transactionenv.(*TransactionEnv).WithTransaction.func1(0xc000d86180, 0xc000d86180, 0xc000494070)
	src/github.com/pachyderm/pachyderm/src/server/pkg/transactionenv/env.go:308 +0x6b
github.com/pachyderm/pachyderm/src/server/pkg/transactionenv.(*TransactionEnv).WithWriteContext.func1(0x2a0ff60, 0xc000494070, 0xc0003d24e0, 0xc000d9bfa8)
	src/github.com/pachyderm/pachyderm/src/server/pkg/transactionenv/env.go:325 +0x160
github.com/pachyderm/pachyderm/src/server/pkg/collection.runSTM.func1(0xc0003d24e0, 0x2a0ff60, 0xc000494070, 0xc00087e570, 0x40c300)
	src/github.com/pachyderm/pachyderm/src/server/pkg/collection/transaction.go:121 +0x83
created by github.com/pachyderm/pachyderm/src/server/pkg/collection.runSTM
	src/github.com/pachyderm/pachyderm/src/server/pkg/collection/transaction.go:107 +0x86
```

**Comment by ysimonson** [comment]
It seems like it's a common pattern in our codebase (at least among PFS endpoints) to not check if request arguments are nil. I'm not sure what the right way forward is, as it may be a large amount of work to clean this up.

**Comment by ysimonson** [comment]
Here's a couple of other examples of dereferencing nil values:

* `InspectBranch` [passes `request.Branch`](https://github.com/pachyderm/pachyderm/blob/8521ac2916116c00a9c53aba9eb91f527206c916/src/server/pfs/server/api_server.go#L310), which is a pointer [that is not nil-checked before being used.](https://github.com/pachyderm/pachyderm/blob/master/src/server/pfs/server/driver.go#L2638)
* `ListBranch` [passes `request.Repo`](https://github.com/pachyderm/pachyderm/blob/master/src/server/pfs/server/api_server.go#L323), which is a pointer [that is not nil-checked before being used.](https://github.com/pachyderm/pachyderm/blob/master/src/server/pfs/server/driver.go#L212)
