### ISSUE TITLE
panic: failed to initialize pach client: context deadline exceeded

### ISSUE THREAD

**Issue by suman724** [pachyderm/pachyderm#4437]
**What happened?**:
I tried to install pachyderm on my on-prem kubernetes cluster. All the pods come up successfully execpt pachd. The logs on the pachd pod shows the following.

```
goroutine 367 [running]:
github.com/pachyderm/pachyderm/src/server/pkg/serviceenv.(*ServiceEnv).GetPachClient(0xc000175450, 0x2ad81a0, 0xc0007c4400, 0xc0007c4400)
        src/github.com/pachyderm/pachyderm/src/server/pkg/serviceenv/service_env.go:171 +0x11a
github.com/pachyderm/pachyderm/src/server/pps/server.(*apiServer).master.func1(0x0, 0x0)
        src/github.com/pachyderm/pachyderm/src/server/pps/server/master.go:58 +0xe5
github.com/pachyderm/pachyderm/src/server/pkg/backoff.RetryNotify(0xc000974040, 0x2a99520, 0xc000776000, 0xc00064dfb8, 0x2a, 0x0)
        src/github.com/pachyderm/pachyderm/src/server/pkg/backoff/retry.go:35 +0x4a
github.com/pachyderm/pachyderm/src/server/pps/server.(*apiServer).master(0xc0002aeb40)
        src/github.com/pachyderm/pachyderm/src/server/pps/server/master.go:52 +0x20a
created by github.com/pachyderm/pachyderm/src/server/pps/server.NewAPIServer
        src/github.com/pachyderm/pachyderm/src/server/pps/server/server.go:67 +0x3d4

```
**What you expected to happen?**:
I expected pachd pod to start without errors

**How to reproduce it (as minimally and precisely as possible)?**:

Pre-created persistent volume using the following:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 100Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.92.254
    path: "/data/disk02/nfs/kube-pv/"

```

Generate the deployment manifests using the following command.
`pachctl deploy custom --persistent-disk aws --object-store s3 any-string 10 pachyderm 'someuser' 'randompassword' '192.168.92.254:9000' --static-etcd-volume nfs-pv --dry-run > pachyderm.json
`

Made changes to the deployment manifest to use the pv nfs-pv pre-created and applied the manifest on kubernetes using the following:

`kubectl apply -f pachyderm.json`

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
` kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T07:10:00Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:49:28Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}`

- Pachyderm CLI and pachd server version (use `pachctl version`):

```
pachctl version
COMPONENT           VERSION
pachctl             1.9.9
could not connect to pachd at "grpc://192.168.92.250:30650": context deadline exceeded

```

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): On-prem deployment on 2 bare metal servers
- OS (e.g. from /etc/os-release): 

```
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

```

- Others:
Minio is running a Linux node (also Centos) outside of Kubernetes cluster. Minio version - 

- Complete deployment manifest: Removed the username and password used with minio

```

 cat orig.json.sanitized
{
        "kind": "ServiceAccount",
        "apiVersion": "v1",
        "metadata": {
                "name": "pachyderm",
                "namespace": "default",
                "creationTimestamp": null,
                "labels": {
                        "app": "",
                        "suite": "pachyderm"
                }
        }
}

{
        "kind": "ClusterRole",
        "apiVersion": "rbac.authorization.k8s.io/v1",
        "metadata": {
                "name": "pachyderm",
                "namespace": "default",
                "creationTimestamp": null,
                "labels": {
                        "app": "",
                        "suite": "pachyderm"
                }
        },
        "rules": [
                {
                        "verbs": [
                                "get",
                                "list",
                                "watch"
                        ],
                        "apiGroups": [
                                ""
                        ],
                        "resources": [
                                "nodes",
                                "pods",
                                "pods/log",
                                "endpoints"
                        ]
                },
                {
                        "verbs": [
                                "get",
                                "list",
                                "watch",
                                "create",
                                "update",
                                "delete"
                        ],
                        "apiGroups": [
                                ""
                        ],
                        "resources": [
                                "replicationcontrollers",
                                "services"
                        ]
                },
                {
                        "verbs": [
                                "get",
                                "list",
                                "watch",
                                "create",
                                "update",
                                "delete"
                        ],
                        "apiGroups": [
                                ""
                        ],
                        "resources": [
                                "secrets"
                        ],
                        "resourceNames": [
                                "pachyderm-storage-secret"
                        ]
                }
        ]
}

{
        "kind": "ClusterRoleBinding",
        "apiVersion": "rbac.authorization.k8s.io/v1",
        "metadata": {
                "name": "pachyderm",
                "namespace": "default",
                "creationTimestamp": null,
                "labels": {
                        "app": "",
                        "suite": "pachyderm"
                }
        },
        "subjects": [
                {
                        "kind": "ServiceAccount",
                        "name": "pachyderm",
                        "namespace": "default"
                }
        ],
        "roleRef": {
                "apiGroup": "",
                "kind": "ClusterRole",
                "name": "pachyderm"
        }
}


{
        "kind": "PersistentVolumeClaim",
        "apiVersion": "v1",
        "metadata": {
                "name": "etcd-storage",
                "namespace": "default",
                "creationTimestamp": null,
                "labels": {
                        "app": "etcd",
                        "suite": "pachyderm"
                }
        },
        "spec": {
                "accessModes": [
                        "ReadWriteOnce"
                ],
                "resources": {
                        "requests": {
                                "storage": "10Gi"
                        }
                },
                "volumeName": "nfs-pv",
                "dataSource": null
        },
        "status": {}
}

{
        "kind": "Deployment",
        "apiVersion": "apps/v1",
        "metadata": {
                "name": "etcd",
                "namespace": "default",
                "creationTimestamp": null,
                "labels": {
                        "app": "etcd",
                        "suite": "pachyderm"
                }
        },
        "spec": {
                "replicas": 1,
                "selector": {
                        "matchLabels": {
                                "app": "etcd",
                                "suite": "pachyderm"
                        }
                },
                "template": {
                        "metadata": {
                                "name": "etcd",
                                "namespace": "default",
                                "creationTimestamp": null,
                                "labels": {
                                        "app": "etcd",
                                        "suite": "pachyderm"
                                }
                        },
                        "spec": {
                                "volumes": [
                                        {
                                                "name": "etcd-storage",
                                                "persistentVolumeClaim": {
                                                        "claimName": "etcd-storage"
                                                }
                                        }
                                ],
                                "containers": [
                                        {
                                                "name": "etcd",
                                                "image": "quay.io/coreos/etcd:v3.3.5",
                                                "command": [
                                                        "/usr/local/bin/etcd",
                                                        "--listen-client-urls=http://0.0.0.0:2379",
                                                        "--advertise-client-urls=http://0.0.0.0:2379",
                                                        "--data-dir=/var/data/etcd",
                                                        "--auto-compaction-retention=1",
                                                        "--max-txn-ops=10000",
                                                        "--max-request-bytes=52428800",
                                                        "--quota-backend-bytes=8589934592"
                                                ],
                                                "ports": [
                                                        {
                                                                "name": "client-port",
                                                                "containerPort": 2379
                                                        },
                                                        {
                                                                "name": "peer-port",
                                                                "containerPort": 2380
                                                        }
                                                ],
                                                "resources": {
                                                        "limits": {
                                                                "cpu": "1",
                                                                "memory": "2G"
                                                        },
                                                        "requests": {
                                                                "cpu": "1",
                                                                "memory": "2G"
                                                        }
                                                },
                                                "volumeMounts": [
                                                        {
                                                                "name": "etcd-storage",
                                                                "mountPath": "/var/data/etcd"
                                                        }
                                                ],
                                                "imagePullPolicy": "IfNotPresent"
                                        }
                                ]
                        }
                },
                "strategy": {}
        },
        "status": {}
}

{
        "kind": "Service",
        "apiVersion": "v1",
        "metadata": {
                "name": "etcd",
                "namespace": "default",
                "creationTimestamp": null,
                "labels": {
                        "app": "etcd",
                        "suite": "pachyderm"
                }
        },
        "spec": {
                "ports": [
                        {
                                "name": "client-port",
                                "port": 2379,
                                "targetPort": 0
                        }
                ],
                "selector": {
                        "app": "etcd"
                },
                "type": "NodePort"
        },
        "status": {
                "loadBalancer": {}
        }
}

{
        "kind": "Service",
        "apiVersion": "v1",
        "metadata": {
                "name": "pachd",
                "namespace": "default",
                "creationTimestamp": null,
                "labels": {
                        "app": "pachd",
                        "suite": "pachyderm"
                },
                "annotations": {
                        "prometheus.io/port": "9091",
                        "prometheus.io/scrape": "true"
                }
        },
        "spec": {
                "ports": [
                        {
                                "name": "api-grpc-port",
                                "port": 650,
                                "targetPort": 0,
                                "nodePort": 30650
                        },
                        {
                                "name": "trace-port",
                                "port": 651,
                                "targetPort": 0,
                                "nodePort": 30651
                        },
                        {
                                "name": "api-http-port",
                                "port": 652,
                                "targetPort": 0,
                                "nodePort": 30652
                        },
                        {
                                "name": "saml-port",
                                "port": 654,
                                "targetPort": 0,
                                "nodePort": 30654
                        },
                        {
                                "name": "api-git-port",
                                "port": 999,
                                "targetPort": 0,
                                "nodePort": 30999
                        },
                        {
                                "name": "s3gateway-port",
                                "port": 600,
                                "targetPort": 0,
                                "nodePort": 30600
                        }
                ],
                "selector": {
                        "app": "pachd"
                },
                "type": "NodePort"
        },
        "status": {
                "loadBalancer": {}
        }
}

{
        "kind": "Deployment",
        "apiVersion": "apps/v1",
        "metadata": {
                "name": "pachd",
                "namespace": "default",
                "creationTimestamp": null,
                "labels": {
                        "app": "pachd",
                        "suite": "pachyderm"
                }
        },
        "spec": {
                "replicas": 1,
                "selector": {
                        "matchLabels": {
                                "app": "pachd",
                                "suite": "pachyderm"
                        }
                },
                "template": {
                        "metadata": {
                                "name": "pachd",
                                "namespace": "default",
                                "creationTimestamp": null,
                                "labels": {
                                        "app": "pachd",
                                        "suite": "pachyderm"
                                },
                                "annotations": {
                                        "iam.amazonaws.com/role": ""
                                }
                        },
                        "spec": {
                                "volumes": [
                                        {
                                                "name": "pach-disk"
                                        },
                                        {
                                                "name": "pachyderm-storage-secret",
                                                "secret": {
                                                        "secretName": "pachyderm-storage-secret"
                                                }
                                        }
                                ],
                                "containers": [
                                        {
                                                "name": "pachd",
                                                "image": "pachyderm/pachd:1.9.9",
                                                "ports": [
                                                        {
                                                                "name": "api-grpc-port",
                                                                "containerPort": 650,
                                                                "protocol": "TCP"
                                                        },
                                                        {
                                                                "name": "trace-port",
                                                                "containerPort": 651
                                                        },
                                                        {
                                                                "name": "api-http-port",
                                                                "containerPort": 652,
                                                                "protocol": "TCP"
                                                        },
                                                        {
                                                                "name": "peer-port",
                                                                "containerPort": 653,
                                                                "protocol": "TCP"
                                                        },
                                                        {
                                                                "name": "api-git-port",
                                                                "containerPort": 999,
                                                                "protocol": "TCP"
                                                        },
                                                        {
                                                                "name": "saml-port",
                                                                "containerPort": 654,
                                                                "protocol": "TCP"
                                                        }
                                                ],
                                                "env": [
                                                        {
                                                                "name": "PACH_ROOT",
                                                                "value": "/pach"
                                                        },
                                                        {
                                                                "name": "ETCD_PREFIX"
                                                        },
                                                        {
                                                                "name": "NUM_SHARDS",
                                                                "value": "16"
                                                        },
                                                        {
                                                                "name": "STORAGE_BACKEND",
                                                                "value": "AMAZON"
                                                        },
                                                        {
                                                                "name": "STORAGE_HOST_PATH"
                                                        },
                                                        {
                                                                "name": "WORKER_IMAGE",
                                                                "value": "pachyderm/worker:1.9.9"
                                                        },
                                                        {
                                                                "name": "IMAGE_PULL_SECRET"
                                                        },
                                                        {
                                                                "name": "WORKER_SIDECAR_IMAGE",
                                                                "value": "pachyderm/pachd:1.9.9"
                                                        },
                                                        {
                                                                "name": "WORKER_IMAGE_PULL_POLICY",
                                                                "value": "IfNotPresent"
                                                        },
                                                        {
                                                                "name": "PACHD_VERSION",
                                                                "value": "1.9.9"
                                                        },
                                                        {
                                                                "name": "METRICS",
                                                                "value": "true"
                                                        },
                                                        {
                                                                "name": "LOG_LEVEL",
                                                                "value": "info"
                                                        },
                                                        {
                                                                "name": "BLOCK_CACHE_BYTES",
                                                                "value": "1G"
                                                        },
                                                        {
                                                                "name": "IAM_ROLE"
                                                        },
                                                        {
                                                                "name": "NO_EXPOSE_DOCKER_SOCKET",
                                                                "value": "false"
                                                        },
                                                        {
                                                                "name": "PACHYDERM_AUTHENTICATION_DISABLED_FOR_TESTING",
                                                                "value": "false"
                                                        },
                                                        {
                                                                "name": "PACHD_POD_NAMESPACE",
                                                                "valueFrom": {
                                                                        "fieldRef": {
                                                                                "apiVersion": "v1",
                                                                                "fieldPath": "metadata.namespace"
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "PACHD_MEMORY_REQUEST",
                                                                "valueFrom": {
                                                                        "resourceFieldRef": {
                                                                                "containerName": "pachd",
                                                                                "resource": "requests.memory",
                                                                                "divisor": "0"
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "EXPOSE_OBJECT_API",
                                                                "value": "false"
                                                        },
                                                        {
                                                                "name": "GOOGLE_BUCKET",
                                                                "valueFrom": {
                                                                        "secretKeyRef": {
                                                                                "name": "pachyderm-storage-secret",
                                                                                "key": "google-bucket",
                                                                                "optional": true
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "GOOGLE_CRED",
                                                                "valueFrom": {
                                                                        "secretKeyRef": {
                                                                                "name": "pachyderm-storage-secret",
                                                                                "key": "google-cred",
                                                                                "optional": true
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "MICROSOFT_CONTAINER",
                                                                "valueFrom": {
                                                                        "secretKeyRef": {
                                                                                "name": "pachyderm-storage-secret",
                                                                                "key": "microsoft-container",
                                                                                "optional": true
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "MICROSOFT_ID",
                                                                "valueFrom": {
                                                                        "secretKeyRef": {
                                                                                "name": "pachyderm-storage-secret",
                                                                                "key": "microsoft-id",
                                                                                "optional": true
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "MICROSOFT_SECRET",
                                                                "valueFrom": {
                                                                        "secretKeyRef": {
                                                                                "name": "pachyderm-storage-secret",
                                                                                "key": "microsoft-secret",
                                                                                "optional": true
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "MINIO_BUCKET",
                                                                "valueFrom": {
                                                                        "secretKeyRef": {
                                                                                "name": "pachyderm-storage-secret",
                                                                                "key": "minio-bucket",
                                                                                "optional": true
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "MINIO_ENDPOINT",
                                                                "valueFrom": {
                                                                        "secretKeyRef": {
                                                                                "name": "pachyderm-storage-secret",
                                                                                "key": "minio-endpoint",
                                                                                "optional": true
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "MINIO_ID",
                                                                "valueFrom": {
                                                                        "secretKeyRef": {
                                                                                "name": "pachyderm-storage-secret",
                                                                                "key": "minio-id",
                                                                                "optional": true
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "MINIO_SECRET",
                                                                "valueFrom": {
                                                                        "secretKeyRef": {
                                                                                "name": "pachyderm-storage-secret",
                                                                                "key": "minio-secret",
                                                                                "optional": true
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "MINIO_SECURE",
                                                                "valueFrom": {
                                                                        "secretKeyRef": {
                                                                                "name": "pachyderm-storage-secret",
                                                                                "key": "minio-secure",
                                                                                "optional": true
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "MINIO_SIGNATURE",
                                                                "valueFrom": {
                                                                        "secretKeyRef": {
                                                                                "name": "pachyderm-storage-secret",
                                                                                "key": "minio-signature",
                                                                                "optional": true
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "AMAZON_REGION",
                                                                "valueFrom": {
                                                                        "secretKeyRef": {
                                                                                "name": "pachyderm-storage-secret",
                                                                                "key": "amazon-region",
                                                                                "optional": true
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "AMAZON_BUCKET",
                                                                "valueFrom": {
                                                                        "secretKeyRef": {
                                                                                "name": "pachyderm-storage-secret",
                                                                                "key": "amazon-bucket",
                                                                                "optional": true
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "AMAZON_ID",
                                                                "valueFrom": {
                                                                        "secretKeyRef": {
                                                                                "name": "pachyderm-storage-secret",
                                                                                "key": "amazon-id",
                                                                                "optional": true
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "AMAZON_SECRET",
                                                                "valueFrom": {
                                                                        "secretKeyRef": {
                                                                                "name": "pachyderm-storage-secret",
                                                                                "key": "amazon-secret",
                                                                                "optional": true
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "AMAZON_TOKEN",
                                                                "valueFrom": {
                                                                        "secretKeyRef": {
                                                                                "name": "pachyderm-storage-secret",
                                                                                "key": "amazon-token",
                                                                                "optional": true
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "AMAZON_VAULT_ADDR",
                                                                "valueFrom": {
                                                                        "secretKeyRef": {
                                                                                "name": "pachyderm-storage-secret",
                                                                                "key": "amazon-vault-addr",
                                                                                "optional": true
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "AMAZON_VAULT_ROLE",
                                                                "valueFrom": {
                                                                        "secretKeyRef": {
                                                                                "name": "pachyderm-storage-secret",
                                                                                "key": "amazon-vault-role",
                                                                                "optional": true
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "AMAZON_VAULT_TOKEN",
                                                                "valueFrom": {
                                                                        "secretKeyRef": {
                                                                                "name": "pachyderm-storage-secret",
                                                                                "key": "amazon-vault-token",
                                                                                "optional": true
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "AMAZON_DISTRIBUTION",
                                                                "valueFrom": {
                                                                        "secretKeyRef": {
                                                                                "name": "pachyderm-storage-secret",
                                                                                "key": "amazon-distribution",
                                                                                "optional": true
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "CUSTOM_ENDPOINT",
                                                                "valueFrom": {
                                                                        "secretKeyRef": {
                                                                                "name": "pachyderm-storage-secret",
                                                                                "key": "custom-endpoint",
                                                                                "optional": true
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "RETRIES",
                                                                "valueFrom": {
                                                                        "secretKeyRef": {
                                                                                "name": "pachyderm-storage-secret",
                                                                                "key": "retries",
                                                                                "optional": true
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "TIMEOUT",
                                                                "valueFrom": {
                                                                        "secretKeyRef": {
                                                                                "name": "pachyderm-storage-secret",
                                                                                "key": "timeout",
                                                                                "optional": true
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "UPLOAD_ACL",
                                                                "valueFrom": {
                                                                        "secretKeyRef": {
                                                                                "name": "pachyderm-storage-secret",
                                                                                "key": "upload-acl",
                                                                                "optional": true
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "REVERSE",
                                                                "valueFrom": {
                                                                        "secretKeyRef": {
                                                                                "name": "pachyderm-storage-secret",
                                                                                "key": "reverse",
                                                                                "optional": true
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "PART_SIZE",
                                                                "valueFrom": {
                                                                        "secretKeyRef": {
                                                                                "name": "pachyderm-storage-secret",
                                                                                "key": "part-size",
                                                                                "optional": true
                                                                        }
                                                                }
                                                        },
                                                        {
                                                                "name": "MAX_UPLOAD_PARTS",
                                                                "valueFrom": {
                                                                        "secretKeyRef": {
                                                                                "name": "pachyderm-storage-secret",
                                                                                "key": "max-upload-parts",
                                                                                "optional": true
                                                                        }
                                                                }
                                                        }
                                                ],
                                                "resources": {
                                                        "limits": {
                                                                "cpu": "1",
                                                                "memory": "3G"
                                                        },
                                                        "requests": {
                                                                "cpu": "1",
                                                                "memory": "3G"
                                                        }
                                                },
                                                "volumeMounts": [
                                                        {
                                                                "name": "pach-disk",
                                                                "mountPath": "/pach"
                                                        },
                                                        {
                                                                "name": "pachyderm-storage-secret",
                                                                "mountPath": "/pachyderm-storage-secret"
                                                        }
                                                ],
                                                "readinessProbe": {
                                                        "exec": {
                                                                "command": [
                                                                        "/pachd",
                                                                        "--readiness"
                                                                ]
                                                        }
                                                },
                                                "imagePullPolicy": "IfNotPresent"
                                        }
                                ],
                                "serviceAccountName": "pachyderm"
                        }
                },
                "strategy": {}
        },
        "status": {}
}

{
        "kind": "Service",
        "apiVersion": "v1",
        "metadata": {
                "name": "dash",
                "namespace": "default",
                "creationTimestamp": null,
                "labels": {
                        "app": "dash",
                        "suite": "pachyderm"
                }
        },
        "spec": {
                "ports": [
                        {
                                "name": "dash-http",
                                "port": 8080,
                                "targetPort": 0,
                                "nodePort": 30080
                        },
                        {
                                "name": "grpc-proxy-http",
                                "port": 8081,
                                "targetPort": 0,
                                "nodePort": 30081
                        }
                ],
                "selector": {
                        "app": "dash",
                        "suite": "pachyderm"
                },
                "type": "NodePort"
        },
        "status": {
                "loadBalancer": {}
        }
}

{
        "kind": "Deployment",
        "apiVersion": "apps/v1",
        "metadata": {
                "name": "dash",
                "namespace": "default",
                "creationTimestamp": null,
                "labels": {
                        "app": "dash",
                        "suite": "pachyderm"
                }
        },
        "spec": {
                "selector": {
                        "matchLabels": {
                                "app": "dash",
                                "suite": "pachyderm"
                        }
                },
                "template": {
                        "metadata": {
                                "name": "dash",
                                "namespace": "default",
                                "creationTimestamp": null,
                                "labels": {
                                        "app": "dash",
                                        "suite": "pachyderm"
                                }
                        },
                        "spec": {
                                "containers": [
                                        {
                                                "name": "dash",
                                                "image": "pachyderm/dash:0.5.48",
                                                "ports": [
                                                        {
                                                                "name": "dash-http",
                                                                "containerPort": 8080
                                                        }
                                                ],
                                                "resources": {},
                                                "imagePullPolicy": "IfNotPresent"
                                        },
                                        {
                                                "name": "grpc-proxy",
                                                "image": "pachyderm/grpc-proxy:0.4.10",
                                                "ports": [
                                                        {
                                                                "name": "grpc-proxy-http",
                                                                "containerPort": 8081
                                                        }
                                                ],
                                                "resources": {},
                                                "imagePullPolicy": "IfNotPresent"
                                        }
                                ]
                        }
                },
                "strategy": {}
        },
        "status": {}
}

{
        "kind": "Secret",
        "apiVersion": "v1",
        "metadata": {
                "name": "pachyderm-storage-secret",
                "namespace": "default",
                "creationTimestamp": null,
                "labels": {
                        "app": "pachyderm-storage-secret",
                        "suite": "pachyderm"
                }
        },
        "data": {
                "amazon-bucket": "cGFjaHlkZXJt",
                "amazon-distribution": "",
                "amazon-id": "someuser",
                "amazon-region": "dXMtZWFzdC0x",
                "amazon-secret": "randompassword",
                "amazon-token": "",
                "custom-endpoint": "MTkyLjE2OC45Mi4yNTQ6OTAwMA==",
                "max-upload-parts": "MTAwMDA=",
                "part-size": "NTI0Mjg4MA==",
                "retries": "MTA=",
                "reverse": "dHJ1ZQ==",
                "timeout": "NW0=",
                "upload-acl": "YnVja2V0LW93bmVyLWZ1bGwtY29udHJvbA=="
        }
}


```

**Comment by benwbooth** [comment]
I'm having the same issue: #4432

**Comment by suman724** [comment]
I tried version 1.9.8 as well. I disabled HTTPS on Minio. I therefore ran pachctl as below to generate the deployment manifest and make pachd work with non-secure minio.

`pachctl deploy custom --persistent-disk aws --object-store s3 any-string 10 pachyderm 'suman' 'hadoop123' '192.168.92.254:9000' --static-etcd-volume nfs-pv --isS3V2 --dry-run > pachyderm1.json
`

I am now passing isS3V2 go make non-secure connection to minio. If I do not pass --isS3V2, I ran into the same error @benwbooth mentioned on #4432 .



With that extra parameter, pachd started successfully. 

```
# kubectl get pods -l suite=pachyderm
NAME                     READY   STATUS    RESTARTS   AGE
dash-6b9cd76b4f-qdn6k    2/2     Running   0          13m
etcd-674484698f-mzd62    1/1     Running   0          13m
pachd-7fbdc9466f-br97g   1/1     Running   0          6m

# ./pachctl version
COMPONENT           VERSION
pachctl             1.9.8
pachd               1.9.8


```

So, the original problem (pachd service startup failure) does appear to be only in 1.9.9 in my environment.

**Comment by benwbooth** [comment]
@suman724 have you tried to execute a pipeline? I'm getting this error #4466 when trying to run a pipeline. It looks like pachyderm in V2 mode is still not compatible with rook/ceph S3 object stores.

**Comment by brycemcanally** [comment]
Closing since this issue is closely related to #4432. Feel free to reopen with logs from a release >=1.9.12.
