### ISSUE TITLE
context deadline timeout  is not affected by TIMEOUT envir

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#4527]
From the `--timeout` flag of `pachctl deploy custom`, I assume that setting `TIMEOUT` envir in `pachd` pod should override the default value (`5m`).
However when I tried this:
```
Containers:
  pachd:
    Image:          pachyderm/pachd:1.9.10
...
Environment:
      TIMEOUT:                                        1m
...
```
, I still have to wait 5 minutes before getting my deadline exceeded error (which I get from `pachctl create repo`).

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.16.3
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.9.10
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): minikube

**Comment by marcadella** [comment]
The log from `pachd` pod may be useful:
```
2020-01-24T14:37:00Z INFO pfs.API.CreateRepo {"request":{"repo":{"name":"inputs"},"update":true}} 

<5 minutes later:>

panic: failed to initialize pach client: context deadline exceeded
goroutine 149 [running]:
github.com/pachyderm/pachyderm/src/server/pkg/serviceenv.(*ServiceEnv).GetPachClient(0xc000228c30, 0x2a81560, 0xc000054098, 0x0)
        /pachyderm/src/server/pkg/serviceenv/service_env.go:171 +0x11a
github.com/pachyderm/pachyderm/src/server/pkg/metrics.(*Reporter).reportClusterMetrics(0xc00077a660)
        /pachyderm/src/server/pkg/metrics/metrics.go:140 +0xbd
created by github.com/pachyderm/pachyderm/src/server/pkg/metrics.NewReporter
        /pachyderm/src/server/pkg/metrics/metrics.go:36 +0x29c
```

**Comment by marcadella** [comment]
Having upgraded to 1.9.11, I got more info about why pachd is unhappy: `error setting up Internal Pachd GRPC Server: error setting up Block API GRPC Server: unable to write to object storage: Get http://metakube-minio:9000/metakube/?location=: dial tcp 10.110.180.231:9000: connect: connection refused`.

**Comment by marcadella** [comment]
Closing this issue since start-up timeout is different from `--timeout`. Moreover 1.9.11 is able to crash straight away instead of hanging around for 5 long minutes.
