### ISSUE TITLE
Panic in s3Gateway

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#4739]
```
goroutine 183 [running]:
github.com/pachyderm/pachyderm/src/server/pps/server.(*apiServer).ServeSidecarS3G(0xc0001d2360)
        /pachyderm/src/server/pps/server/s3g_sidecar.go:56 +0x420
created by github.com/pachyderm/pachyderm/src/server/pps/server.NewSidecarAPIServer
        /pachyderm/src/server/pps/server/server.go:97 +0x23e
```

**Comment by ysimonson** [comment]
This is triggered if there's no spec commit when starting the s3g sidecar, implying PPS is in some bad state

**Comment by jdoliner** [comment]
Yeah this cropped up when deploying custom images. So I think it might have had to do with updating kubernetes resources but not having them get recreated by pachd so not having the right env vars.

I'm going to just leave this open as a beacon in case we find other repros of this we want to fix. But if we don't see this again for a few months we should close.
