### ISSUE TITLE
Test flake from TestS3SkippedDatums/S3Inputs

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#4803]
```
--- FAIL: TestS3SkippedDatums (177.27s)
    --- FAIL: TestS3SkippedDatums/S3Inputs (70.92s)
        s3g_sidecar_test.go:653: Not equal: "foo" (expected)
                    != "bar" (actual)
        s3g_sidecar_test.go:653: current stack:
            goroutine 48 [running]:
            runtime/debug.Stack(0xc00023af00, 0x223ab2b, 0x31)
            	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/runtime/debug/stack.go:24 +0x9d
            github.com/pachyderm/pachyderm/src/client/pkg/require.fatal(0x2597ae0, 0xc00023af00, 0x0, 0x0, 0x0, 0x223ab2b, 0x31, 0xc0005ba380, 0x2, 0x2)
            	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:444 +0xbf
            github.com/pachyderm/pachyderm/src/client/pkg/require.Equal(0x2597ae0, 0xc00023af00, 0x1e42820, 0xc000270600, 0x1e42820, 0x24dcd10, 0x0, 0x0, 0x0)
            	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:54 +0x3cc
            github.com/pachyderm/pachyderm/src/server/pps/server.TestS3SkippedDatums.func1(0xc00023af00)
            	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pps/server/s3g_sidecar_test.go:653 +0x312f
            testing.tRunner(0xc00023af00, 0xc00051eea0)
            	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/testing/testing.go:909 +0xc9
            created by testing.(*T).Run
            	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/testing/testing.go:960 +0x350
```

**Comment by msteffen** [comment]
Another flake:
```
--- FAIL: TestS3SkippedDatums (251.20s)
    --- FAIL: TestS3SkippedDatums/S3Inputs (151.44s)
        s3g_sidecar_test.go:653: Not equal: "foo" (expected)
                    != "bar" (actual)
        s3g_sidecar_test.go:653: current stack:
            goroutine 31 [running]:
            runtime/debug.Stack(0xc0003d0d00, 0x22e14c2, 0x31)
            	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/runtime/debug/stack.go:24 +0x9d
            github.com/pachyderm/pachyderm/src/client/pkg/require.fatal(0x26548c0, 0xc0003d0d00, 0x0, 0x0, 0x0, 0x22e14c2, 0x31, 0xc0014c3c80, 0x2, 0x2)
            	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:523 +0xbf
            github.com/pachyderm/pachyderm/src/client/pkg/require.Equal(0x26548c0, 0xc0003d0d00, 0x1ed23e0, 0xc0014dccb0, 0x1ed23e0, 0x25960f0, 0x0, 0x0, 0x0)
            	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:54 +0x3cc
            github.com/pachyderm/pachyderm/src/server/pps/server.TestS3SkippedDatums.func1(0xc0003d0d00)
            	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pps/server/s3g_sidecar_test.go:653 +0x2def
            testing.tRunner(0xc0003d0d00, 0xc00059c900)
            	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/testing/testing.go:909 +0xc9
            created by testing.(*T).Run
            	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/testing/testing.go:960 +0x350
    --- PASS: TestS3SkippedDatums/S3Output (99.65s)
```
