### ISSUE TITLE
pachd error setting up Block API GRPC Server: time: invalid duration

### ISSUE THREAD

**Issue by andy-han** [pachyderm/pachyderm#4808]
**What happened?**: pachd pod errors on startup. Final log statement: `error setting up Internal Pachd GRPC Server: error setting up Block API GRPC Server: time: invalid duration`

**What you expected to happen?**: pachd pod to be in running state

**How to reproduce it (as minimally and precisely as possible)?**: using the [pachyderm helm chart](https://github.com/helm/charts/tree/master/stable/pachyderm), etcd pod spins up as expected in running state, pachd pod continuously crashes

**Anything else we need to know?**: logs:
`goroutine 104 [chan receive]:
github.com/pachyderm/pachyderm/src/client/pkg/shard.(*sharder).RegisterFrontends.func3(0xc0007782b0, 0xc0000e1620)
        /pachyderm/src/client/pkg/shard/sharder.go:124 +0x64
created by github.com/pachyderm/pachyderm/src/client/pkg/shard.(*sharder).RegisterFrontends
        /pachyderm/src/client/pkg/shard/sharder.go:122 +0x243

goroutine 24 [runnable]:
github.com/pachyderm/pachyderm/src/client/pkg/shard.(*sharder).Register.func2(0xc000460260, 0xc0000fa410, 0xc000326640, 0x11, 0xc00074a0f0, 0x1, 0x1, 0xc000054240, 0xc000054360, 0xc000460244, ...)
        /pachyderm/src/client/pkg/shard/sharder.go:81
created by github.com/pachyderm/pachyderm/src/client/pkg/shard.(*sharder).Register
        /pachyderm/src/client/pkg/shard/sharder.go:81 +0x217

goroutine 25 [runnable]:
github.com/pachyderm/pachyderm/src/client/pkg/shard.(*sharder).Register.func3(0xc000460260, 0xc000054360)
        /pachyderm/src/client/pkg/shard/sharder.go:90
created by github.com/pachyderm/pachyderm/src/client/pkg/shard.(*sharder).Register
        /pachyderm/src/client/pkg/shard/sharder.go:90 +0x243
error setting up Internal Pachd GRPC Server: error setting up Block API GRPC Server: time: invalid duration`

**Environment?**:
- Kubernetes version (use `kubectl version`): 
`Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b8860f", GitCommit:"b8860f6c40640897e52c143f1b9f011a503d6e46", GitTreeState:"clean", BuildDate:"2019-12-13T00:18:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}`
- Pachyderm CLI and pachd server version (use `pachctl version`): tested on multiple versions. pachd pod fails on versions 1.10.0> but works on versions <1.9.12
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): aws
- OS (e.g. from /etc/os-release): centos
- Others:

**Comment by jdoliner** [comment]
Hi @andy-han sorry you're hitting this, would you mind doing a `kubectl describe deploy/pachd` and posting the results here. That should give us an idea of what this invalid duration is.

You'll probably be able to get around this by doing a `pachctl deploy` instead of using the helm chart, totally understand if helm is more comfortable for you and you'd prefer to stick to that, we should be able to find a way to get it working. `pachctl deploy` is the much more tested way of deploying and the one that we officially support, the helm chart is community created.

Also if you'd prefer to get lower latency support we have a users slack channel that we're quite active in, if not we're happy to keep supporting you in this issue.

**Comment by ysimonson** [comment]
Also, bear in mind that there's a few issues with helm deployments since they haven't been updated in some time:

* https://github.com/pachyderm/pachyderm/issues/3729
* https://github.com/pachyderm/pachyderm/issues/3594
* https://github.com/pachyderm/pachyderm/issues/3440

**Comment by andy-han** [comment]
Ok if anyone somehow stumbles upon this... I believe it IS an issue with the helm chart. If you were to deploy pachyderm using `pachctl deploy amazon...` you would generate a "pachyderm-storage-secret" that looks something like this:
```
apiVersion: v1
data:
  amazon-bucket: <<BASE64 encoded STUFF>>
  amazon-distribution: ""
  amazon-region: <<BASE64 encoded STUFF>>
  disable-ssl: <<BASE64 encoded STUFF>>
  max-upload-parts: <<BASE64 encoded STUFF>>
  no-verify-ssl: <<BASE64 encoded STUFF>>
  part-size: <<BASE64 encoded STUFF>>
  retries: <<BASE64 encoded STUFF>>
  reverse: <<BASE64 encoded STUFF>>
  timeout: NW0=   // ! THIS WAS IT !
  upload-acl: <<BASE64 encoded STUFF>>
kind: Secret
metadata:
...
```

However, out of the box, the helm chart didn't give me all of those fields in data. My specific error was showing up when I didn't have `timeout` set to 5m. Hope this helps...
