### ISSUE TITLE
S3 gateway crashes gsutil when listing contents of a bucket

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#4858]
**What happened?**:

I configured gsutil to work with the S3 gateway using a boto3 config (see below).  The configuration I detail below allows gsutil to correctly access  GCS buckets using the gs:// prefix with an [OAuth 2 User Account](https://cloud.google.com/storage/docs/gsutil/addlhelp/CredentialTypesSupportingVariousUseCases) and S3 Gateway buckets using the s3:// prefix.

I can list buckets using this command:
```
gsutil ls  s3://
```

However, any attempt to list the contents of a bucket, using the `-r` flag, results in a gsutil crash, shown below:
```
$  gsutil ls -r s3://master.train/

Traceback (most recent call last):
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/gsutil/gsutil", line 21, in <module>
    gsutil.RunMain()
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/gsutil/gsutil.py", line 124, in RunMain
    sys.exit(gslib.__main__.main())
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 433, in main
    user_project=user_project)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 628, in _RunNamedCommandAndHandleExceptions
    user_project=user_project)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/gsutil/gslib/command_runner.py", line 411, in RunNamedCommand
    return_code = command_inst.RunCommand()
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/gsutil/gslib/commands/ls.py", line 641, in RunCommand
    listing_helper.ExpandUrlAndPrint(storage_url))
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/gsutil/gslib/utils/ls_helper.py", line 369, in ExpandUrlAndPrint
    print_initial_newline=False)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/gsutil/gslib/utils/ls_helper.py", line 443, in _RecurseExpandUrlAndPrint
    bucket_listing_fields=self.bucket_listing_fields):
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/gsutil/gslib/wildcard_iterator.py", line 498, in IterAll
    expand_top_level_buckets=expand_top_level_buckets):
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/gsutil/gslib/wildcard_iterator.py", line 174, in __iter__
    fields=bucket_listing_fields):
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/gsutil/gslib/boto_translation.py", line 434, in ListObjects
    for key in objects_iter:
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/gsutil/gslib/vendored/boto/boto/s3/bucketlistresultset.py", line 34, in bucket_lister
    encoding_type=encoding_type)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/gsutil/gslib/vendored/boto/boto/s3/bucket.py", line 477, in get_all_keys
    '', headers, **params)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/gsutil/gslib/vendored/boto/boto/s3/bucket.py", line 403, in _get_all
    query_args=query_args)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/gsutil/gslib/vendored/boto/boto/s3/connection.py", line 684, in make_request
    retry_handler=retry_handler
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/gsutil/gslib/vendored/boto/boto/connection.py", line 1074, in make_request
    retry_handler=retry_handler)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/gsutil/gslib/vendored/boto/boto/connection.py", line 1033, in _mexe
    raise ex
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```
**What you expected to happen?**:
I expected it to list  the contents of the bucket.

Similarly configured aws-cli or mc works properly.  

**How to reproduce it (as minimally and precisely as possible)?**:

1. Enable authentication on your pachyderm cluster `pachctl auth enable` after adding an enterprise key.
2. Generate a token to use with the S3 gateway `pachctl auth get-auth-token`

The next two steps are [documented in the gcloud docs](https://cloud.google.com/storage/docs/gsutil/commands/config#description).

3.  Install gsutil standalone or disable gcloud credential-passing to gsutil 
```
gcloud config set pass_credentials_to_gsutil false
```
4. Set up gsutil configuration
```
gsutil config
```
5. This will create a `~/.boto` file.  In that file, around line 42, there are settings for adding HMAC credentials for s3:// urls.  Add the token you generated and configure s3_host and s3_port.  Here are example settings for docker-desktop pachyderm cluster with auth enabled and forwarding to the default ports:
```
# To add HMAC aws credentials for "s3://" URIs, edit and uncomment the
# following two lines:
aws_access_key_id = bafb90ef09d443a4ac5398e97efdc5cf
aws_secret_access_key = bafb90ef09d443a4ac5398e97efdc5cf
# The ability to specify an alternate storage host and port
# is primarily for cloud storage service developers.
# Setting a non-default gs_host only works if prefer_api=xml.
s3_host = localhost
s3_port = 30600
# In some cases, (e.g. VPC requests) the "host" HTTP header should
# be different than the host used in the request URL.
#s3_host_header = <alternate storage host header>
```
6. If you have not added SSL certificates, you'll need to add the following in the `[boto3]` section
```
is_secure = False
```

If configuration worked properly, if you do a 
```
gsutil ls gs://
```
you should see a list of your buckets in gcs.

Doing a 
```
gsutil ls s3://
```
Will show a list of the branches/repos in your pachyderm cluster.

The crash occurs when attempting to list the contents of any of those buckets.

**Anything else we need to know?**:

**Environment?**: 
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-10T21:53:51Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Pachyderm CLI and pachd server version (use `pachctl version`):
```
COMPONENT           VERSION             
pachctl             1.10.3              
pachd               1.10.3              
```
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:
- gsutil version: 4.49

**Comment by pappasilenus** [comment]
replacing "localhost" with "127.0.0.1" doesn't fix this.

**Comment by pappasilenus** [comment]
Update: 

I discovered that gsutil uses the virtual addressing style, and that we expect path addressing.  (see https://docs.aws.amazon.com/cli/latest/topic/s3-config.html#addressing-style for an explanation of the difference between the two.)

running gsutil above with "-DD" will show details of how it's trying to access the buckets.

gsutil seems to ignore the environment variable settings for pointing it at a different configuration file.

**Comment by pappasilenus** [comment]
Logged a bug with gsutil. https://github.com/GoogleCloudPlatform/gsutil/issues/1001
