### ISSUE TITLE
Test failure TestExtractRestoreFailedJobs

### ISSUE THREAD

**Issue by nitinjainsj** [pachyderm/pachyderm#4892]
Potentially a flaky test in CI. Capturing here for the record. This on master on 5/15/2020

pachd launch took 14 seconds
+break
++pachctl config get active-context
++minikube ip
+pachctl config update context default --pachd-address=10.30.1.15:30650
+go clean -testcache
+case "${BUCKET}" in
+make test-admin
go test -v -count=1 ./src/server/admin/server -timeout 3600s
=== RUN   TestExtractRestoreNoObjects
--- PASS: TestExtractRestoreNoObjects (62.06s)
=== RUN   TestExtractRestoreObjects
--- PASS: TestExtractRestoreObjects (64.53s)
=== RUN   TestExtractRestoreFailedJobs
--- FAIL: TestExtractRestoreFailedJobs (108.64s)
    admin_test.go:444: 0 Successful jobs, and 1 failed jobs
    admin_test.go:444: Not equal: 1 (expected)
                != 0 (actual)
    admin_test.go:444: current stack:
        goroutine 130 [running]:
        runtime/debug.Stack(0xc0002bd000, 0x1f920f5, 0x31)
        	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/runtime/debug/stack.go:24 +0x9d
        github.com/pachyderm/pachyderm/src/client/pkg/require.fatal(0x22aab40, 0xc0002bd000, 0xc01ae9e090, 0x3, 0x3, 0x1f920f5, 0x31, 0xc01927e4c0, 0x2, 0x2)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:523 +0xbf
        github.com/pachyderm/pachyderm/src/client/pkg/require.Equal(0x22aab40, 0xc0002bd000, 0x1c1b980, 0x21fed58, 0x1c1b980, 0x32805a0, 0xc01ae9e090, 0x3, 0x3)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:54 +0x3cc
        github.com/pachyderm/pachyderm/src/server/admin/server.TestExtractRestoreFailedJobs.func1(0x0, 0x0)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/admin/server/admin_test.go:444 +0x3bd
        github.com/pachyderm/pachyderm/src/client/pkg/require.NoErrorWithinTRetry.func1(0xc0004e1a10, 0xc018a7aaa0, 0xc000405f60, 0xc01aa9c000)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:424 +0x31
        created by github.com/pachyderm/pachyderm/src/client/pkg/require.NoErrorWithinTRetry
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:422 +0xe1
    admin_test.go:427: operation did not finish within 1m30s - last error: <nil>
    admin_test.go:427: current stack:
        goroutine 101 [running]:
        runtime/debug.Stack(0xc0002bd000, 0x1f98b56, 0x33)
        	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/runtime/debug/stack.go:24 +0x9d
        github.com/pachyderm/pachyderm/src/client/pkg/require.fatal(0x22aab40, 0xc0002bd000, 0x0, 0x0, 0x0, 0x1f98b56, 0x33, 0xc00027c040, 0x2, 0x2)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:523 +0xbf
        github.com/pachyderm/pachyderm/src/client/pkg/require.NoErrorWithinTRetry(0x22aab40, 0xc0002bd000, 0x14f46b0400, 0xc018a7aaa0, 0x0, 0x0, 0x0)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:434 +0x2b4
        github.com/pachyderm/pachyderm/src/server/admin/server.TestExtractRestoreFailedJobs(0xc0002bd000)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/admin/server/admin_test.go:427 +0xb1c
        testing.tRunner(0xc0002bd000, 0x200ffb0)
        	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/testing/testing.go:909 +0xc9
        created by testing.(*T).Run
        	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/testing/testing.go:960 +0x350
=== RUN   TestExtractRestoreHeadlessBranches
--- PASS: TestExtractRestoreHeadlessBranches (0.14s)
=== RUN   TestExtractVersion
--- PASS: TestExtractVersion (1.21s)
=== RUN   TestMigrateFrom1_7
--- PASS: TestMigrateFrom1_7 (14.24s)
=== RUN   TestExtractRestorePipelineUpdate
--- PASS: TestExtractRestorePipelineUpdate (46.21s)
=== RUN   TestExtractRestoreDeferredProcessing
--- PASS: TestExtractRestoreDeferredProcessing (40.52s)
=== RUN   TestExtractRestoreStats
--- PASS: TestExtractRestoreStats (7.27s)
FAIL
FAIL	github.com/pachyderm/pachyderm/src/server/admin/server	344.921s
FAIL
Makefile:297: recipe for target 'test-admin' failed
make: *** [test-admin] Error 1
travis_time:end:022a864d:start=1589562831812007198,finish=1589563407919841140,duration=576107833942,event=script
[0K[31;1mThe command "etc/testing/travis.sh" exited with 2.[0m
travis_fold:start:before_cache.1
[0Ktravis_time:start:39468c77
[0K$ etc/testing/travis_cache.sh
+dirs=("${HOME}/.cache" "${HOME}/cached-deps" "${GOPATH}/pkg" "${HOME}/docker" "$(python3 -c 'import site; print(site.USER_BASE)')")
++python3 -c 'import site; print(site.USER_BASE)'
+for dir in '"${dirs[@]}"'
+[[ -d /home/travis/.cache ]]
+sudo chown -R travis:travis /home/travis/.cache
+chmod 777 -R /home/travis/.cache
+for dir in '"${dirs[@]}"'
+[[ -d /home/travis/cached-deps ]]
+sudo chown -R travis:travis /home/travis/cached-deps
+chmod 777 -R /home/travis/cached-deps
+for dir in '"${dirs[@]}"'
+[[ -d /home/travis/gopath/pkg ]]
+sudo chown -R travis:travis /home/travis/gopath/pkg
+chmod 777 -R /home/travis/gopath/pkg
+for dir in '"${dirs[@]}"'
+[[ -d /home/travis/docker ]]
+sudo chown -R travis:travis /home/travis/docker
+chmod 777 -R /home/travis/docker
+for dir in '"${dirs[@]}"'
+[[ -d /home/travis/.local ]]
+sudo chown -R travis:travis /home/travis/.local
+chmod 777 -R /home/travis/.local
travis_time:end:39468c77:start=1589563407926592320,finish=1589563408898415931,duration=971823611,event=before_cache
[0Ktravis_fold:end:before_cache.1
[0Ktravis_fold:start:before_cache.2
[0Ktravis_time:start:0509eed2
[0K$ etc/testing/travis_before_cache.sh
rm: cannot remove '/home/travis/docker/*': No such file or directory
travis_time:end:0509eed2:start=1589563408904895025,finish=1589563453677858811,duration=44772963786,event=before_cache
[0Ktravis_fold:end:before_cache.2
[0Ktravis_fold:start:cache.2
[0Kstore build cache
travis_time:start:11f5cd31
[0Ktravis_time:end:11f5cd31:start=1589563453683580158,finish=1589563453687411341,duration=3831183,event=cache
[0Ktravis_time:start:10abcafa
[0K[32;1mchanges detected (content changed, file is created, or file is deleted):\n/home/travis/.cache/go-build/03/0308cf211bcabcc89451ef9e9e0bf51431aa3c66021adbaff89f3116c285b850-a
/home/travis/.cache/go-build/04/04f305f2521ae068d7ea6a1d8650934333b2ce0ddad1366cd2aeec847d0e5f44-a
/home/travis/.cache/go-build/06/066a074c7f54bcbc50158e392ba2f4f8abf559712dae6fda67463582747dccb1-a
/home/travis/.cache/go-build/08/08a45e2d0b8dbd9732ee23144e0c792582d6fec2186be29c7de3971f13529151-a
/home/travis/.cache/go-build/09/09ff0728e73061fe1c1c0422d8c962aeda00cf86509882aba1d57f0ee41f0850-a
/home/travis/.cache/go-build/0a/0a863800673837bc5514212f811f338d0daa0438b5e518f9d184dfbd87fe5abb-d
/home/travis/.cache/go-build/0a/0acc3e6da4596e25e0dac04bee9d7779aa969776101f32bfd4a7e3bcb9084cea-a
/home/travis/.cache/go-build/0a/0adf498ccb9ed485f86ea9382c4634d653de2acce2a6429bfdca840d8add12c8-a
/home/travis/.cache/go-build/0b/0bd9035218ff2a2945b6e1408c0f0972b3ead5ba165ef9959fbf52dc7d4f246d-a
/home/travis/.cache/go-build/0b/0bdda5793473902d38e9fa2789796073aac4c764dd4c61c614a71e4712c141bb-d
/home/trav\n...[0m
[32;1mchanges detected, packing new archive[0m
[32;1muploading master/cache--linux-xenial-66faca632327ed46139288ec45ad5ea98ec90c8e3b327bcf929f15508cd4427d--go-1.13.1.tgz[0m
[32;1mcache uploaded[0m
travis_time:end:10abcafa:start=1589563453693338370,finish=1589563818019963582,duration=364326625212,event=cache
[0Ktravis_fold:end:cache.2
[0K
travis_fold:start:after_failure.1
[0Ktravis_time:start:03090daa
[0K$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
travis_time:end:03090daa:start=1589563818028083146,finish=1589563818395781846,duration=367698700,event=after_failure
[0Ktravis_fold:end:after_failure.1
[0Ktravis_fold:start:after_failure.2
[0Ktravis_time:start:05ff9f42
[0K$ kubectl get all
NAME                                                        READY   STATUS    RESTARTS   AGE
pod/dash-64c868cc8b-8q7k6                                   2/2     Running   0          13m
pod/etcd-56b496bc8-bslrb                                    1/1     Running   0          13m
pod/pachd-c9fd9d745-8mgqr                                   1/1     Running   0          13m
pod/pipeline-testextractrestorestatsa464a1b667f7-v1-9btmg   2/2     Running   0          6m49s

NAME                                                                             DESIRED   CURRENT   READY   AGE
replicationcontroller/pipeline-copy-v1                                           0         0         0       8m20s
replicationcontroller/pipeline-testextractrestoree17295581cf5-v1                 0         0         0       8m38s
replicationcontroller/pipeline-testextractrestoreobjects-p2-344bd3016ebf-v1      0         0         0       10m
replicationcontroller/pipeline-testextractrestoreobjects-p2-f04ff2842e80-v1      0         0         0       11m
replicationcontroller/pipeline-testextractrestorepipelineupdate542b395a80ed-v2   0         0         0       7m37s
replicationcontroller/pipeline-testextractrestorestatsa464a1b667f7-v1            1         1         1       6m50s

NAME                                                               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                               AGE
service/dash                                                       NodePort    10.104.177.213   <none>        8080:30080/TCP,8081:30081/TCP                                                         13m
service/etcd                                                       NodePort    10.101.207.184   <none>        2379:32379/TCP                                                                        13m
service/kubernetes                                                 ClusterIP   10.96.0.1        <none>        443/TCP                                                                               15m
service/pachd                                                      NodePort    10.102.253.106   <none>        650:30650/TCP,651:30651/TCP,652:30652/TCP,654:30654/TCP,655:30655/TCP,600:30600/TCP   13m
service/pachd-peer                                                 ClusterIP   10.97.14.41      <none>        30653/TCP                                                                             13m
service/pipeline-copy-v1                                           ClusterIP   10.110.37.209    <none>        80/TCP,9090/TCP                                                                       8m20s
service/pipeline-testextractrestoree17295581cf5-v1                 ClusterIP   10.110.44.237    <none>        80/TCP,9090/TCP                                                                       8m38s
service/pipeline-testextractrestoreobjects-p2-344bd3016ebf-v1      ClusterIP   10.96.247.224    <none>        80/TCP,9090/TCP                                                                       10m
service/pipeline-testextractrestoreobjects-p2-f04ff2842e80-v1      ClusterIP   10.96.82.82      <none>        80/TCP,9090/TCP                                                                       11m
service/pipeline-testextractrestorepipelineupdate542b395a80ed-v2   ClusterIP   10.102.108.75    <none>        80/TCP,9090/TCP                                                                       7m37s
service/pipeline-testextractrestorestatsa464a1b667f7-v1            ClusterIP   10.98.133.193    <none>        80/TCP,9090/TCP                                                                       6m50s

NAME                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/dash    1/1     1            1           13m
deployment.apps/etcd    1/1     1            1           13m
deployment.apps/pachd   1/1     1            1           13m

NAME                              DESIRED   CURRENT   READY   AGE
replicaset.apps/dash-64c868cc8b   1         1         1       13m
replicaset.apps/etcd-56b496bc8    1         1         1       13m
replicaset.apps/pachd-c9fd9d745   1         1         1       13m
travis_time:end:05ff9f42:start=1589563818402220837,finish=1589563818726930398,duration=324709561,event=after_failure
[0Ktravis_fold:end:after_failure.2
[0Ktravis_fold:start:after_failure.3
[0Ktravis_time:start:018074de
[0K$ kubectl get all --namespace kafka
No resources found.
travis_time:end:018074de:start=1589563818740765335,finish=1589563818883062817,duration=142297482,event=after_failure
[0Ktravis_fold:end:after_failure.3
[0Ktravis_fold:start:after_failure.4
[0Ktravis_time:start:18f3b00b
[0K$ kubectl describe pod -l app=pachd
Name:               pachd-c9fd9d745-8mgqr
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               minikube/10.30.1.15
Start Time:         Fri, 15 May 2020 17:17:17 +0000
Labels:             app=pachd
                    pod-template-hash=c9fd9d745
                    suite=pachyderm
Annotations:        iam.amazonaws.com/role: 
Status:             Running
IP:                 172.17.0.5
Controlled By:      ReplicaSet/pachd-c9fd9d745
Containers:
  pachd:
    Container ID:  docker://e17b31de89b50ec7a7a20bd25b8dc4bad8c79b6bc440d885039a02ca515b8950
    Image:         pachyderm/pachd:local
    Image ID:      docker://sha256:259549ea32be5874eb41a24570a62faa63b2191100210ba83095435a22af31f5
    Ports:         650/TCP, 651/TCP, 652/TCP, 653/TCP, 655/TCP, 654/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP
    Command:
      /app/pachd
    State:          Running
      Started:      Fri, 15 May 2020 17:17:19 +0000
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:      250m
      memory:   512M
    Readiness:  exec [/app/pachd --readiness] delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      PACH_ROOT:                                      /pach
      ETCD_PREFIX:                                    
      NUM_SHARDS:                                     16
      STORAGE_BACKEND:                                LOCAL
      STORAGE_HOST_PATH:                              /var/pachyderm/pachd
      WORKER_IMAGE:                                   pachyderm/worker:local
      IMAGE_PULL_SECRET:                              
      WORKER_SIDECAR_IMAGE:                           pachyderm/pachd:local
      WORKER_IMAGE_PULL_POLICY:                       IfNotPresent
      PACHD_VERSION:                                  local
      METRICS:                                        false
      LOG_LEVEL:                                      info
      BLOCK_CACHE_BYTES:                              256M
      IAM_ROLE:                                       
      NO_EXPOSE_DOCKER_SOCKET:                        false
      PACHYDERM_AUTHENTICATION_DISABLED_FOR_TESTING:  true
      PACH_NAMESPACE:                                 default (v1:metadata.namespace)
      PACHD_MEMORY_REQUEST:                           512000000 (requests.memory)
      EXPOSE_OBJECT_API:                              true
      CLUSTER_DEPLOYMENT_ID:                          80a1c5047d1a4b37ad8dc0bc9f040891
      REQUIRE_CRITICAL_SERVERS_ONLY:                  false
      GOOGLE_BUCKET:                                  <set to the key 'google-bucket' in secret 'pachyderm-storage-secret'>        Optional: true
      GOOGLE_CRED:                                    <set to the key 'google-cred' in secret 'pachyderm-storage-secret'>          Optional: true
      MICROSOFT_CONTAINER:                            <set to the key 'microsoft-container' in secret 'pachyderm-storage-secret'>  Optional: true
      MICROSOFT_ID:                                   <set to the key 'microsoft-id' in secret 'pachyderm-storage-secret'>         Optional: true
      MICROSOFT_SECRET:                               <set to the key 'microsoft-secret' in secret 'pachyderm-storage-secret'>     Optional: true
      MINIO_BUCKET:                                   <set to the key 'minio-bucket' in secret 'pachyderm-storage-secret'>         Optional: true
      MINIO_ENDPOINT:                                 <set to the key 'minio-endpoint' in secret 'pachyderm-storage-secret'>       Optional: true
      MINIO_ID:                                       <set to the key 'minio-id' in secret 'pachyderm-storage-secret'>             Optional: true
      MINIO_SECRET:                                   <set to the key 'minio-secret' in secret 'pachyderm-storage-secret'>         Optional: true
      MINIO_SECURE:                                   <set to the key 'minio-secure' in secret 'pachyderm-storage-secret'>         Optional: true
      MINIO_SIGNATURE:                                <set to the key 'minio-signature' in secret 'pachyderm-storage-secret'>      Optional: true
      AMAZON_REGION:                                  <set to the key 'amazon-region' in secret 'pachyderm-storage-secret'>        Optional: true
      AMAZON_BUCKET:                                  <set to the key 'amazon-bucket' in secret 'pachyderm-storage-secret'>        Optional: true
      AMAZON_ID:                                      <set to the key 'amazon-id' in secret 'pachyderm-storage-secret'>            Optional: true
      AMAZON_SECRET:                                  <set to the key 'amazon-secret' in secret 'pachyderm-storage-secret'>        Optional: true
      AMAZON_TOKEN:                                   <set to the key 'amazon-token' in secret 'pachyderm-storage-secret'>         Optional: true
      AMAZON_VAULT_ADDR:                              <set to the key 'amazon-vault-addr' in secret 'pachyderm-storage-secret'>    Optional: true
      AMAZON_VAULT_ROLE:                              <set to the key 'amazon-vault-role' in secret 'pachyderm-storage-secret'>    Optional: true
      AMAZON_VAULT_TOKEN:                             <set to the key 'amazon-vault-token' in secret 'pachyderm-storage-secret'>   Optional: true
      AMAZON_DISTRIBUTION:                            <set to the key 'amazon-distribution' in secret 'pachyderm-storage-secret'>  Optional: true
      CUSTOM_ENDPOINT:                                <set to the key 'custom-endpoint' in secret 'pachyderm-storage-secret'>      Optional: true
      RETRIES:                                        <set to the key 'retries' in secret 'pachyderm-storage-secret'>              Optional: true
      TIMEOUT:                                        <set to the key 'timeout' in secret 'pachyderm-storage-secret'>              Optional: true
      UPLOAD_ACL:                                     <set to the key 'upload-acl' in secret 'pachyderm-storage-secret'>           Optional: true
      REVERSE:                                        <set to the key 'reverse' in secret 'pachyderm-storage-secret'>              Optional: true
      PART_SIZE:                                      <set to the key 'part-size' in secret 'pachyderm-storage-secret'>            Optional: true
      MAX_UPLOAD_PARTS:                               <set to the key 'max-upload-parts' in secret 'pachyderm-storage-secret'>     Optional: true
      DISABLE_SSL:                                    <set to the key 'disable-ssl' in secret 'pachyderm-storage-secret'>          Optional: true
      NO_VERIFY_SSL:                                  <set to the key 'no-verify-ssl' in secret 'pachyderm-storage-secret'>        Optional: true
      STORAGE_UPLOAD_CONCURRENCY_LIMIT:               100
      STORAGE_PUT_FILE_CONCURRENCY_LIMIT:             100
    Mounts:
      /pach from pach-disk (rw)
      /pachyderm-storage-secret from pachyderm-storage-secret (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from pachyderm-token-bjr69 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  pach-disk:
    Type:          HostPath (bare host directory volume)
    Path:          /var/pachyderm/pachd
    HostPathType:  DirectoryOrCreate
  pachyderm-storage-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  pachyderm-storage-secret
    Optional:    false
  pachyderm-token-bjr69:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  pachyderm-token-bjr69
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  13m   default-scheduler  Successfully assigned default/pachd-c9fd9d745-8mgqr to minikube
  Normal  Pulled     13m   kubelet, minikube  Container image "pachyderm/pachd:local" already present on machine
  Normal  Created    13m   kubelet, minikube  Created container
  Normal  Started    13m   kubelet, minikube  Started container
travis_time:end:18f3b00b:start=1589563818889657050,finish=1589563819017936936,duration=128279886,event=after_failure
[0Ktravis_fold:end:after_failure.4
[0Ktravis_fold:start:after_failure.5
[0Ktravis_time:start:01bb2a49
[0K$ kubectl describe pod -l suite=pachyderm,app=etcd
Name:               etcd-56b496bc8-bslrb
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               minikube/10.30.1.15
Start Time:         Fri, 15 May 2020 17:17:17 +0000
Labels:             app=etcd
                    pod-template-hash=56b496bc8
                    suite=pachyderm
Annotations:        <none>
Status:             Running
IP:                 172.17.0.6
Controlled By:      ReplicaSet/etcd-56b496bc8
Containers:
  etcd:
    Container ID:  docker://10cf77f826e3aab45b97db73255f405ae6d55598738122157b1b7fa553e513de
    Image:         quay.io/coreos/etcd:v3.3.5
    Image ID:      docker-pullable://quay.io/coreos/etcd@sha256:75955f97f6b6ce1c6f363f50f99570bbbd87516b4212d0b3acdbd48039d51dbd
    Ports:         2379/TCP, 2380/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      /usr/local/bin/etcd
      --listen-client-urls=http://0.0.0.0:2379
      --advertise-client-urls=http://0.0.0.0:2379
      --data-dir=/var/data/etcd
      --auto-compaction-retention=1
      --max-txn-ops=10000
      --max-request-bytes=52428800
      --quota-backend-bytes=8589934592
    State:          Running
      Started:      Fri, 15 May 2020 17:17:25 +0000
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:        250m
      memory:     512M
    Environment:  <none>
    Mounts:
      /var/data/etcd from etcd-storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-p2hnt (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  etcd-storage:
    Type:          HostPath (bare host directory volume)
    Path:          /var/pachyderm/etcd
    HostPathType:  DirectoryOrCreate
  default-token-p2hnt:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-p2hnt
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  13m   default-scheduler  Successfully assigned default/etcd-56b496bc8-bslrb to minikube
  Normal  Pulling    13m   kubelet, minikube  pulling image "quay.io/coreos/etcd:v3.3.5"
  Normal  Pulled     12m   kubelet, minikube  Successfully pulled image "quay.io/coreos/etcd:v3.3.5"
  Normal  Created    12m   kubelet, minikube  Created container
  Normal  Started    12m   kubelet, minikube  Started container
travis_time:end:01bb2a49:start=1589563819038244404,finish=1589563819238343490,duration=200099086,event=after_failure
[0Ktravis_fold:end:after_failure.5
[0Ktravis_fold:start:after_failure.6
[0Ktravis_time:start:000748ee
[0K$ kubectl logs -l app=pachd | tail -n 100
2020-05-15T17:23:29Z INFO pfs.API.GetFile {"request":{"file":{"commit":{"repo":{"name":"__spec__"},"id":"184459c7bbdc4656810c533cdb58d3b9"},"path":"spec"}}} []
2020-05-15T17:23:29Z INFO auth.API.WhoAmI {"request":{}} []
2020-05-15T17:23:29Z INFO auth.API.WhoAmI {"request":{}} []
2020-05-15T17:23:29Z INFO pfs.BlockAPI.Obj.GetObjects {"request":{"objects":[{"hash":"921c32388e958aaceb9fa836775d2e925f4944d2b2910558cafad4257ff8d20842c70b078f6505b1090b32a7f10dcb6027a1dbac37e8737790d9672eae94650e"}],"total_size":308}} []
2020-05-15T17:23:29Z INFO pfs.BlockAPI.Obj.InspectObject {"request":{"hash":"921c32388e958aaceb9fa836775d2e925f4944d2b2910558cafad4257ff8d20842c70b078f6505b1090b32a7f10dcb6027a1dbac37e8737790d9672eae94650e"}} []
2020-05-15T17:23:29Z INFO pfs.BlockAPI.Obj.InspectObject {"duration":0.000020638,"request":{"hash":"921c32388e958aaceb9fa836775d2e925f4944d2b2910558cafad4257ff8d20842c70b078f6505b1090b32a7f10dcb6027a1dbac37e8737790d9672eae94650e"},"response":{"object":{"hash":"921c32388e958aaceb9fa836775d2e925f4944d2b2910558cafad4257ff8d20842c70b078f6505b1090b32a7f10dcb6027a1dbac37e8737790d9672eae94650e"},"block_ref":{"block":{"hash":"77c99f0c76b942c9a5366add1341a05c"},"range":{"upper":308}}}} []
2020-05-15T17:23:29Z INFO pfs.BlockAPI.Obj.GetObjects {"duration":0.000125885,"request":{"objects":[{"hash":"921c32388e958aaceb9fa836775d2e925f4944d2b2910558cafad4257ff8d20842c70b078f6505b1090b32a7f10dcb6027a1dbac37e8737790d9672eae94650e"}],"total_size":308}} []
2020-05-15T17:23:29Z INFO pfs.API.GetFile {"duration":0.006421311,"request":{"file":{"commit":{"repo":{"name":"__spec__"},"id":"184459c7bbdc4656810c533cdb58d3b9"},"path":"spec"}}} []
2020-05-15T17:23:29Z INFO PPS master: scaling up workers for "TestExtractRestoreStatsa464a1b667f7"
2020-05-15T17:23:29Z INFO PPS master: monitoring pipeline "TestExtractRestoreStatsa464a1b667f7"
travis_time:end:000748ee:start=1589563819252305962,finish=1589563819390788703,duration=138482741,event=after_failure
[0Ktravis_fold:end:after_failure.6
[0K
Done. Your build exited with 1.

**What happened?**:

**What you expected to happen?**:

**How to reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by msteffen** [comment]
I'm continuing to see this as well, though I'm not actively working on it so I've unassigned myself
