### ISSUE TITLE
TestPipelineBuildLifecycleGo flake

### ISSUE THREAD

**Issue by PFedak** [pachyderm/pachyderm#5345]
TestPipelineBuildLifecycleGo failed in https://travis-ci.com/github/pachyderm/pachyderm/jobs/399167346

```
=== RUN   TestPipelineBuildLifecycleGo
../../../../etc/testing/pipeline-build/input/111.txt: 3 B / 3 B  100.00% ? p/s 0
../../../../etc/testing/pipeline-build/input/1.txt: 1 B / 1 B [ 100.00% ? p/s 0s
../../../../etc/testing/pipeline-build/input/11.txt: 2 B / 2 B  100.00% ? p/s 0s
go.mod: 131 B / 131 B [=======================================] 100.00% ? p/s 0s
go.sum: 169 B / 169 B [=======================================] 100.00% ? p/s 0s
main.go: 795 B / 795 B [======================================] 100.00% ? p/s 0s
file /1.txt not found in repo test-pipeline-build at commit d4ec0aec17fa49248db2a5d388e5bfc1
failed to find
  "0001"
in the text:
  """
  """
```

**Comment by msteffen** [comment]
I've been seeing this flake quite a bit as well (especially in the 1.11.x branch—not sure if the underlying issue was fixed in master but not 1.11.x somehow)

**Comment by msteffen** [comment]
I'm now noticing this regularly with TestPipelineBuildLifecyclePython as well

**Comment by msteffen** [comment]
It looks like sometimes the test fails to load the source code into the `source` branch:
```
file /1.txt not found in repo test-pipeline-build at commit a010b8bfd21d4f5280628e0de454c3e0
failed to find
  "___1"
in the text:
  """

  """
--- FAIL: TestPipelineBuildLifecycleGo (46.42s)
    cmds_test.go:630: No error is expected but got exit status 1
    cmds_test.go:630: current stack:
        goroutine 14 [running]:
        runtime/debug.Stack(0x25a47a0, 0xc000480780, 0xc00038bd98)
                /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
        github.com/pachyderm/pachyderm/src/client/pkg/require.fatal(0x262e8c0, 0xc0005db500, 0x0, 0x0, 0x0, 0x2252bca, 0x1f, 0xc000209a10, 0x1, 0x1)
                /home/mjs/clients/s3g_to_kubeflow_20191212/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:534 +0xd9
        github.com/pachyderm/pachyderm/src/client/pkg/require.NoError(0x262e8c0, 0xc0005db500, 0x25a47a0, 0xc000480780, 0x0, 0x0, 0x0)
                /home/mjs/clients/s3g_to_kubeflow_20191212/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:394 +0xef
        github.com/pachyderm/pachyderm/src/server/pps/cmds.verifyPipelineBuildOutput(0xc0005db500, 0x2221841, 0x1)
                /home/mjs/clients/s3g_to_kubeflow_20191212/src/github.com/pachyderm/pachyderm/src/server/pps/cmds/cmds_test.go:733 +0xdf
        github.com/pachyderm/pachyderm/src/server/pps/cmds.testPipelineBuildLifecycle(0xc0005db500, 0x2221a70, 0x2, 0x2221a70, 0x2)
                /home/mjs/clients/s3g_to_kubeflow_20191212/src/github.com/pachyderm/pachyderm/src/server/pps/cmds/cmds_test.go:727 +0x508
        github.com/pachyderm/pachyderm/src/server/pps/cmds.TestPipelineBuildLifecycleGo(0xc0005db500)
                /home/mjs/clients/s3g_to_kubeflow_20191212/src/github.com/pachyderm/pachyderm/src/server/pps/cmds/cmds_test.go:630 +0x4e
        testing.tRunner(0xc0005db500, 0x22f8708)
                /usr/local/go/src/testing/testing.go:909 +0xc9
        created by testing.(*T).Run
                /usr/local/go/src/testing/testing.go:960 +0x350
FAIL
FAIL    github.com/pachyderm/pachyderm/src/server/pps/cmds      46.464s
FAIL
$ pachctl list pipeline
NAME                      VERSION INPUT                                                               CREATED        STATE / LAST JOB  DESCRIPTION
test-pipeline-build       3       (test-pipeline-build_build:/ ⨯ in:/* ⨯ test-pipeline-build_build:/) 16 seconds ago running / failure
test-pipeline-build_build 3       test-pipeline-build_build:/                                         16 seconds ago running / failure
$ pachctl list job
ID                               PIPELINE                  STARTED                DURATION           RESTART PROGRESS  DL UL STATE
6df32a51009248029a9925b560a39c38 test-pipeline-build       Less than a second ago Less than a second 0       0 + 0 / 0 0B 0B failure: inputs failed: build
b10b9fea053c4814a8d9712dccd3d636 test-pipeline-build_build Less than a second ago Less than a second 0       0 + 0 / 1 0B 0B failure: datum failed
b181f93528364f58ac415becb9bdcbe0 test-pipeline-build_build 1 second ago           Less than a second 0       0 + 1 / 1 0B 0B success

$ pc inspect job b10b9fea053c4814a8d9712dccd3d636
ID: b10b9fea053c4814a8d9712dccd3d636
Pipeline: test-pipeline-build_build
Started: 23 seconds ago
Duration: Less than a second
State: failure
Reason: datum failed
Processed: 0
Failed: 1
Skipped: 0
Recovered: 0
Total: 1
Data Downloaded: 0B
Data Uploaded: 0B
Download Time: Less than a second
Process Time: Less than a second
Upload Time: Less than a second
Datum Timeout: (duration: nil Duration)
Job Timeout: (duration: nil Duration)
Worker Status:
WORKER              JOB                 DATUM               STARTED             QUEUE
Restarts: 0
ParallelismSpec: constant:1
Input:
{
  "pfs": {
    "name": "source",
    "repo": "test-pipeline-build_build",
    "branch": "source",
    "commit": "7dce3c5111734ba8a585f3534e63a5e1",
    "glob": "/"
  }
}

Transform:
{
  "image": "pachyderm/go-build:1.12.0-a531c0d4b8e38271d465e41f8687eb055486d82f",
  "cmd": [
    "sh",
    "./build.sh"
  ]
}
Output Commit: c3310f7047c64575bb628269e11861da
$ pc list datum --job=b10b9fea053c4814a8d9712dccd3d636
Error: unknown flag: --job
Usage:
  pachctl list datum <job> [flags]

Flags:
  -h, --help            help for datum
  -o, --output string   Output format when --raw is set: "json" or "yaml" (default "json")
      --page int        Specify the page of results to send
      --pageSize int    Specify the number of results sent back in a single page
      --raw             Disable pretty printing; serialize data structures to an encoding such as json or yaml

Global Flags:
      --no-color   Turn off colors.
  -v, --verbose    Output verbose logs

unknown flag: --job
$ pc list datum b10b9fea053c4814a8d9712dccd3d636
ID                                                                   STATUS TIME
6e16f09447614c8034c2495eb6c8cc9c8f4673700c1d329e02ef7fb785900e38ea61 -      -
$ pc inspect datum b10b9fea053c4814a8d9712dccd3d636@6e16f09447614c8034c2495eb6c8cc9c8f4673700c1d329e02ef7fb785900e38ea61
expected 2 arguments, got 1

Usage:
  pachctl inspect datum <job> <datum> [flags]

Flags:
  -h, --help            help for datum
  -o, --output string   Output format when --raw is set: "json" or "yaml" (default "json")
      --raw             Disable pretty printing; serialize data structures to an encoding such as json or yaml

Global Flags:
      --no-color   Turn off colors.
  -v, --verbose    Output verbose logs

$ pc logs --job=b10b9fea053c4814a8d9712dccd3d636
go version go1.15.3 linux/amd64
package .: no Go files in /pfs/source
go version go1.15.3 linux/amd64
package .: no Go files in /pfs/source
go version go1.15.3 linux/amd64
package .: no Go files in /pfs/source

$ pc list commit test-pipeline-build_build
REPO                      BRANCH COMMIT                           FINISHED      SIZE     PROGRESS DESCRIPTION
test-pipeline-build_build build  c3310f7047c64575bb628269e11861da 3 minutes ago 0B       ▇▇▇▇▇▇▇▇
test-pipeline-build_build source 7dce3c5111734ba8a585f3534e63a5e1 3 minutes ago 0B       ▇▇▇▇▇▇▇▇
test-pipeline-build_build build  dadc0ff8a6894a48bf066de29bee1f19 3 minutes ago 2.137MiB ▇▇▇▇▇▇▇▇
test-pipeline-build_build build  4874e67e1c8c44ca8b54df1cd686aa3d 3 minutes ago 2.137MiB ▇▇▇▇▇▇▇▇
test-pipeline-build_build source 5c1273cbc93742c4b19d112ccfc716b6 3 minutes ago 1.069KiB ▇▇▇▇▇▇▇▇
test-pipeline-build_build build  b05a688b075e4dd5bad6b7e5cc1f413a 3 minutes ago 2.137MiB ▇▇▇▇▇▇▇▇
test-pipeline-build_build build  60fcfeead1344ff8894dd3e88ac09037 3 minutes ago 2.137MiB ▇▇▇▇▇▇▇▇
test-pipeline-build_build source d93c863795d943779f164b02eb04b5ee 4 minutes ago 1.069KiB ▇▇▇▇▇▇▇▇

$ pc list file test-pipeline-build_build@source
NAME TYPE SIZE

$ pc list file test-pipeline-build_build@source~1
NAME     TYPE SIZE
/go.mod  file 131B
/go.sum  file 169B
/main.go file 795B
```

**Comment by msteffen** [comment]
I lost my terminal session unfortunately (gnome-shell literally crashed on me :sob:) but I got another failure with this test that was actually due to an internal kubernetes error: the build pipeline failed because the PPS master wasn't able to update the RC (due to some kind of mismatched UUID, though it was k8s's UUID, not ours)

**Comment by PFedak** [comment]
If that's the "precondition failed" thing I've definitely seen it, too - that and https://github.com/kubernetes/kubernetes/issues/82130 made me think upgrading our k8s might help, but clearly there are other problems, too.

**Comment by msteffen** [comment]
That looks like the same error, but I'm actually seeing this locally using k8s 1.19.2 (which maybe means the fix in that issue didn't fix the underlying problem?).

One fix that occurs to me is to add uuid to the pipeline name in the test. That seems like cheating, but I actually think it's (mostly) fine because the way to hit this bug is to delete and recreate the same pipeline repeatedly. If a user is updating a pipeline (the normal way to change one), then the version number will increment with each update, which changes the RC name, avoiding this bug. This shouldn't generally be a problem in CI either, because we create a fresh k8s cluster before each test run.

**Comment by msteffen** [comment]
**Update**: The UUID change seems to have worked, but I'm still seeing failures due to missing source files. When I look at the PutFile logs from a successful and a failed build pipeline, they look different. Specifically, it seems like `/` is being written sometimes but not others for some reason:

**Success**
```
2020-11-06T07:20:26Z DEBUG pfs.API.PutFile writing
    to:test-pipeline-build0c1593d5bc2a_build@source:go.mod
2020-11-06T07:20:26Z DEBUG pfs.API.PutFile writing
    to:test-pipeline-build0c1593d5bc2a_build@source:go.sum
2020-11-06T07:20:26Z DEBUG pfs.API.PutFile writing
    to:test-pipeline-build0c1593d5bc2a_build@source:main.go
2020-11-06T07:20:26Z DEBUG pfs.API.PutFile wrote
    to:test-pipeline-build0c1593d5bc2a_build@source:go.mod,131b,dur:4.056403ms(32294.62b/s),err:<nil>
2020-11-06T07:20:26Z DEBUG pfs.API.PutFile wrote
    to:test-pipeline-build0c1593d5bc2a_build@source:go.sum,169b,dur:3.180402ms(53137.94b/s),err:<nil>
2020-11-06T07:20:26Z DEBUG pfs.API.PutFile wrote
    to:test-pipeline-build0c1593d5bc2a_build@source:main.go,795b,dur:2.801495ms(283777.05b/s),err:<nil>
```

**Failure**:
```
2020-11-06T07:20:37Z DEBUG pfs.API.PutFile writing
    to:test-pipeline-build0c1593d5bc2a_build@d66c1933183f45018b441607dee3cfaf:go.mod
2020-11-06T07:20:37Z DEBUG pfs.API.PutFile writing
    to:test-pipeline-build0c1593d5bc2a_build@d66c1933183f45018b441607dee3cfaf:/
2020-11-06T07:20:37Z DEBUG pfs.API.PutFile writing
    to:test-pipeline-build0c1593d5bc2a_build@d66c1933183f45018b441607dee3cfaf:go.sum
2020-11-06T07:20:37Z DEBUG pfs.API.PutFile wrote
    to:test-pipeline-build0c1593d5bc2a_build@d66c1933183f45018b441607dee3cfaf:go.mod,131b,dur:3.125898ms(41907.96b/s),err:<nil>
2020-11-06T07:20:37Z DEBUG pfs.API.PutFile writing
    to:test-pipeline-build0c1593d5bc2a_build@d66c1933183f45018b441607dee3cfaf:main.go
2020-11-06T07:20:37Z DEBUG pfs.API.PutFile wrote
    to:test-pipeline-build0c1593d5bc2a_build@d66c1933183f45018b441607dee3cfaf:go.sum,169b,dur:3.615913ms(46737.85b/s),err:<nil>
2020-11-06T07:20:37Z DEBUG pfs.API.PutFile wrote
    to:test-pipeline-build0c1593d5bc2a_build@d66c1933183f45018b441607dee3cfaf:main.go,795b,dur:2.250455ms(353261.90b/s),err:<nil>
2020-11-06T07:20:37Z DEBUG pfs.API.PutFile wrote
    to:test-pipeline-build0c1593d5bc2a_build@d66c1933183f45018b441607dee3cfaf:/,0b,dur:82.219843ms(0.00b/s),err:<nil>
```
