### ISSUE TITLE
Travis shard succeeds (in UI) despite test failing in the log

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#5348]
From the logs for https://travis-ci.com/github/pachyderm/pachyderm/jobs/399167346

It looks like a test is failing, but the test shard is green?
```
=== RUN   TestPipelineBuildLifecycleGo
../../../../etc/testing/pipeline-build/input/111.txt: 3 B / 3 B  100.00% ? p/s 0../../../../etc/testing/pipeline-build/input/1.txt: 1 B / 1 B [ 100.00% ? p/s 0s../../../../etc/testing/pipeline-build/input/11.txt: 2 B / 2 B  100.00% ? p/s 0sgo.mod: 131 B / 131 B [=======================================] 100.00% ? p/s 0sgo.sum: 169 B / 169 B [=======================================] 100.00% ? p/s 0smain.go: 795 B / 795 B [======================================] 100.00% ? p/s 0sfile /1.txt not found in repo test-pipeline-build at commit 744504017e9f4ecf92a130ff9e78e6c5
failed to find
  "0001"
in the text:
  """
  """
    cmds_test.go:586: No error is expected but got exit status 1
    cmds_test.go:586: current stack:
        goroutine 111 [running]:
        runtime/debug.Stack(0x21b9560, 0xc0005021e0, 0xc0001a5db0)
        	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/debug/stack.go:24 +0x9f
        github.com/pachyderm/pachyderm/src/client/pkg/require.fatal(0x2229b60, 0xc000492000, 0x0, 0x0, 0x0, 0x1ff1f4b, 0x1f, 0xc0003a0530, 0x1, 0x1)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:534 +0xdf
        github.com/pachyderm/pachyderm/src/client/pkg/require.NoError(0x2229b60, 0xc000492000, 0x21b9560, 0xc0005021e0, 0x0, 0x0, 0x0)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:394 +0xec
        github.com/pachyderm/pachyderm/src/server/pps/cmds.verifyPipelineBuildOutput(0xc000492000, 0x1fc6f57, 0x1)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pps/cmds/cmds_test.go:689 +0xe9
        github.com/pachyderm/pachyderm/src/server/pps/cmds.testPipelineBuildLifecycle(0xc000492000, 0x1fc7164, 0x2, 0x1fc7164, 0x2)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pps/cmds/cmds_test.go:632 +0x28d
        github.com/pachyderm/pachyderm/src/server/pps/cmds.TestPipelineBuildLifecycleGo(0xc000492000)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pps/cmds/cmds_test.go:586 +0x4e
        testing.tRunner(0xc000492000, 0x208fec8)
        	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/testing/testing.go:1127 +0xef
        created by testing.(*T).Run
        	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/testing/testing.go:1178 +0x386
--- FAIL: TestPipelineBuildLifecycleGo (5.20s)
=== RUN   TestMissingPipeline
no `pipeline` specified
--- PASS: TestMissingPipeline (0.09s)
=== RUN   TestUnnamedPipeline
no pipeline `name` specified
--- PASS: TestUnnamedPipeline (0.07s)
=== RUN   TestPipelineBuildSpout
build step-enabled pipelines do not work with spouts
--- PASS: TestPipelineBuildSpout (0.08s)
=== RUN   TestPipelineBuildMissingInput
no `input` specified
--- PASS: TestPipelineBuildMissingInput (0.07s)
=== RUN   TestPipelineBuildBadInput
build step-enabled pipelines cannot have inputs with the name 'build' or 'source', as they are reserved for build assets
build step-enabled pipelines cannot have inputs with the name 'build' or 'source', as they are reserved for build assets
--- PASS: TestPipelineBuildBadInput (0.14s)
=== RUN   TestPipelineBuildMissingPath
build path "/some/path/that/doesnt/exist" does not exist
--- PASS: TestPipelineBuildMissingPath (0.08s)
=== RUN   TestPipelineBuildRunCron
cmds.go: 50.37 KiB / 50.37 KiB [==============================] 100.00% ? p/s 0scmds_test.go: 22.76 KiB / 22.76 KiB [=========================] 100.00% ? p/s 0s--- PASS: TestPipelineBuildRunCron (0.29s)
=== RUN   TestWarningLatestTag
../../../../etc/testing/pipeline-build/input/111.txt: 3 B / 3 B  100.00% ? p/s 0../../../../etc/testing/pipeline-build/input/1.txt: 1 B / 1 B [ 100.00% ? p/s 0s../../../../etc/testing/pipeline-build/input/11.txt: 2 B / 2 B  100.00% ? p/s 0s--- PASS: TestWarningLatestTag (0.67s)
=== RUN   TestWarningEmptyTag
liveness ping Wed Oct 14 16:20:10 UTC 2020
../../../../etc/testing/pipeline-build/input/111.txt: 3 B / 3 B  100.00% ? p/s 0../../../../etc/testing/pipeline-build/input/1.txt: 1 B / 1 B [ 100.00% ? p/s 0s../../../../etc/testing/pipeline-build/input/11.txt: 2 B / 2 B  100.00% ? p/s 0s--- PASS: TestWarningEmptyTag (1.39s)
=== RUN   TestNoWarningTagSpecified
../../../../etc/testing/pipeline-build/input/111.txt: 3 B / 3 B  100.00% ? p/s 0../../../../etc/testing/pipeline-build/input/1.txt: 1 B / 1 B [ 100.00% ? p/s 0s../../../../etc/testing/pipeline-build/input/11.txt: 2 B / 2 B  100.00% ? p/s 0s--- PASS: TestNoWarningTagSpecified (0.62s)
FAIL
FAIL	github.com/pachyderm/pachyderm/src/server/pps/cmds	185.807s
FAIL
Makefile:267: recipe for target 'test-cmds' failed
make: *** [test-cmds] Error 1
+echo '=== TEST FAILED OR TIMED OUT, DUMPING DEBUG INFO ==='
```

**Comment by msteffen** [comment]
This was a misunderstanding of our Travis script on my part. It retries our whole test suite (see our use of [the travis feature travis_retry](https://docs.travis-ci.com/user/common-build-problems/#travis_retry) in our [.travis.yaml file](https://github.com/pachyderm/pachyderm/blob/971b81640b6ffd8e9a6c44c225b93a60da46e60a/.travis.yml#L59)). The failure above triggered a subsequent retry, which succeeded.
