### ISSUE TITLE
Flake in TestFlushOpenCommit on 1.11.x

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#5407]
```
--- FAIL: TestFlushOpenCommit (5.14s)
    server_test.go:3110: No error is expected but got transport is closing
    require.go:530: github.com/pachyderm/pachyderm/src/client/pkg/grpcutil.ScrubGRPC
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/grpcutil/error.go:16
    require.go:530: github.com/pachyderm/pachyderm/src/client.APIClient.FinishCommit
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pfs.go:245
    require.go:530: github.com/pachyderm/pachyderm/src/server/pfs/server/testing.TestFlushOpenCommit.func1.1
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pfs/server/testing/server_test.go:3110
    require.go:530: runtime.goexit
        	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/runtime/asm_amd64.s:1357
    server_test.go:3110: current stack:
        goroutine 3435867 [running]:
        runtime/debug.Stack(0x30e48c0, 0xc03e497960, 0xc004409ba0)
        	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/runtime/debug/stack.go:24 +0x9d
        github.com/pachyderm/pachyderm/src/client/pkg/require.fatal(0x31a30c0, 0xc00049a700, 0x0, 0x0, 0x0, 0x2c337bb, 0x1f, 0xc004729f40, 0x1, 0x1)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:534 +0xd9
        github.com/pachyderm/pachyderm/src/client/pkg/require.NoError(0x31a30c0, 0xc00049a700, 0x30e48c0, 0xc03e497960, 0x0, 0x0, 0x0)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:394 +0xef
        github.com/pachyderm/pachyderm/src/server/pfs/server/testing.TestFlushOpenCommit.func1.1(0xc00049a700, 0xc0372bd860)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pfs/server/testing/server_test.go:3110 +0x1d9
        created by github.com/pachyderm/pachyderm/src/server/pfs/server/testing.TestFlushOpenCommit.func1
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pfs/server/testing/server_test.go:3107 +0x45f
```

**Comment by msteffen** [comment]
full travis log: [20201104_travis.log](https://github.com/pachyderm/pachyderm/files/5488869/20201104_travis.log)
