### ISSUE TITLE
Auth error from testing ./src/server/pfs/cmds

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#5590]
I seem to be getting auth errors in Travis when `./src/server/pfs/cmds` runs:
```
go test -v -count=1 ./src/server/pfs/cmds -timeout 3600s
=== RUN   TestCommit
error authenticating (must log in to create a repo): no authentication token (try logging in)
    cmds_test.go:16: No error is expected but got exit status 1
    cmds_test.go:16: current stack:
        goroutine 7 [running]:
        runtime/debug.Stack(0x24cf580, 0xc000361fe0, 0xc000485e80)
        	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/debug/stack.go:24 +0x9f
        github.com/pachyderm/pachyderm/src/client/pkg/require.fatal(0x25462c0, 0xc000001b00, 0x0, 0x0, 0x0, 0x22a6a38, 0x1f, 0xc0003fef30, 0x1, 0x1)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:534 +0xdf
        github.com/pachyderm/pachyderm/src/client/pkg/require.NoError(0x25462c0, 0xc000001b00, 0x24cf580, 0xc000361fe0, 0x0, 0x0, 0x0)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:394 +0xec
        github.com/pachyderm/pachyderm/src/server/pfs/cmds.TestCommit(0xc000001b00)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pfs/cmds/cmds_test.go:16 +0x152
        testing.tRunner(0xc000001b00, 0x23431d8)
        	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/testing/testing.go:1127 +0xef
        created by testing.(*T).Run
        	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/testing/testing.go:1178 +0x386
--- FAIL: TestCommit (0.08s)
=== RUN   TestPutFileSplit
error authenticating (must log in to create a repo): no authentication token (try logging in)
    cmds_test.go:46: No error is expected but got exit status 1
    cmds_test.go:46: current stack:
        goroutine 10 [running]:
        runtime/debug.Stack(0x24cf580, 0xc000138060, 0xc000485e80)
        	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/debug/stack.go:24 +0x9f
        github.com/pachyderm/pachyderm/src/client/pkg/require.fatal(0x25462c0, 0xc000566300, 0x0, 0x0, 0x0, 0x22a6a38, 0x1f, 0xc000432000, 0x1, 0x1)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:534 +0xdf
        github.com/pachyderm/pachyderm/src/client/pkg/require.NoError(0x25462c0, 0xc000566300, 0x24cf580, 0xc000138060, 0x0, 0x0, 0x0)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:394 +0xec
        github.com/pachyderm/pachyderm/src/server/pfs/cmds.TestPutFileSplit(0xc000566300)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pfs/cmds/cmds_test.go:46 +0x152
        testing.tRunner(0xc000566300, 0x23431e8)
        	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/testing/testing.go:1127 +0xef
        created by testing.(*T).Run
        	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/testing/testing.go:1178 +0x386
--- FAIL: TestPutFileSplit (0.10s)
```

Full log: [travis_logs.txt](https://github.com/pachyderm/pachyderm/files/5785535/travis_logs.txt)

**Comment by actgardner** [comment]
It looks like another test failed and the cluster wasn't reset before the retry - if you grep for `TestCommit` you can see it initially passed in those logs:

```
go test -v -count=1 ./src/server/pfs/cmds -timeout 3600s
=== RUN   TestCommit
stdin: 14 B [    ] ? p/s stdin: 14 B [    ] ? p/s --- PASS: TestCommit (0.68s)
=== RUN   TestPutFileSplit
```

The real failure was:
```
=== RUN   TestAuthorizedPipelineBuildLifecycle
Are you sure you want to do this? (y/N): ../../../../etc/testing/pipeline-build/input/111.txt: 3 B / 3 B  100.00% ? p/s 0../../../../etc/testing/pipeline-build/input/1.txt: 1 B / 1 B [ 100.00% ? p/s 0s../../../../etc/testing/pipeline-build/input/11.txt: 2 B / 2 B  100.00% ? p/s 0sgo.mod: 131 B / 131 B [=======================================] 100.00% ? p/s 0sgo.sum: 169 B / 169 B [=======================================] 100.00% ? p/s 0smain.go: 795 B / 795 B [======================================] 100.00% ? p/s 0sliveness ping Thu Jan  7 06:31:09 UTC 2021
liveness ping Thu Jan  7 06:32:09 UTC 2021
liveness ping Thu Jan  7 06:33:09 UTC 2021
liveness ping Thu Jan  7 06:34:09 UTC 2021
liveness ping Thu Jan  7 06:35:09 UTC 2021
liveness ping Thu Jan  7 06:36:09 UTC 2021
liveness ping Thu Jan  7 06:37:09 UTC 2021
liveness ping Thu Jan  7 06:38:09 UTC 2021
liveness ping Thu Jan  7 06:39:09 UTC 2021
Makefile:261: recipe for target 'test-cmds' failed
make: *** [test-cmds] Terminated
=== TEST FAILED OR TIMED OUT, DUMPING DEBUG INFO ===
```
