### ISSUE TITLE
Deployment tests are getting stuck

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#5602]
In one test run, there were failures for LocalDeployment, MicrosoftDeployment, and Minio+AmazonDeployment:

LocalDeployment:
```
--- FAIL: TestLocalDeployment (106.82s)
    deployment_test.go:190: No error is expected but got context deadline exceeded
    deployment_test.go:190: current stack:
        goroutine 138 [running]:
        runtime/debug.Stack(0x27b08a0, 0x37a0680, 0xc00086f3b0)
        	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/debug/stack.go:24 +0x9f
        github.com/pachyderm/pachyderm/src/client/pkg/require.fatal(0x2833840, 0xc00041f380, 0x0, 0x0, 0x0, 0x24dad5a, 0x1f, 0xc000bf2be0, 0x1, 0x1)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:534 +0xdf
        github.com/pachyderm/pachyderm/src/client/pkg/require.NoError(0x2833840, 0xc00041f380, 0x27b08a0, 0x37a0680, 0x0, 0x0, 0x0)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:394 +0xec
        github.com/pachyderm/pachyderm/src/server/pkg/obj/testing.getPachClient(0xc00041f380, 0xc0004f4500, 0xc000052de0, 0x1c, 0x0)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pkg/obj/testing/deployment_test.go:190 +0xa3c
        github.com/pachyderm/pachyderm/src/server/pkg/obj/testing.withManifest(0xc00041f380, 0x0, 0x0, 0xc00086ff60)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pkg/obj/testing/deployment_test.go:250 +0x4cd
        github.com/pachyderm/pachyderm/src/server/pkg/obj/testing.TestLocalDeployment(0xc00041f380)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pkg/obj/testing/deployment_test.go:429 +0x65
        testing.tRunner(0xc00041f380, 0x259bcb0)
        	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/testing/testing.go:1127 +0xef
        created by testing.(*T).Run
        	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/testing/testing.go:1178 +0x386
time="2021-01-11T21:28:21Z" level=warning msg="DEPRECATED: Support for the S3V2 option is being deprecated. It will be removed in a future version"
time="2021-01-11T21:28:21Z" level=warning msg="DEPRECATED: Support for the S3V2 option is being deprecated. It will be removed in a future version"
time="2021-01-11T21:28:21Z" level=warning msg="DEPRECATED: Support for the S3V2 option is being deprecated. It will be removed in a future version"
time="2021-01-11T21:28:21Z" level=warning msg="DEPRECATED: Support for the S3V2 option is being deprecated. It will be removed in a future version"
FAIL
FAIL	github.com/pachyderm/pachyderm/src/server/pkg/obj/testing	251.127s
FAIL
Makefile:276: recipe for target 'test-object-clients' failed
```

MicrosoftDeployment:
```
--- FAIL: TestMicrosoftDeployment (104.12s)
    deployment_test.go:190: No error is expected but got context deadline exceeded
    deployment_test.go:190: current stack:
        goroutine 150 [running]:
        runtime/debug.Stack(0x27b08a0, 0x37a0680, 0xc00096f348)
        	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/debug/stack.go:24 +0x9f
        github.com/pachyderm/pachyderm/src/client/pkg/require.fatal(0x2833840, 0xc000543b00, 0x0, 0x0, 0x0, 0x24dad5a, 0x1f, 0xc00119a6d0, 0x1, 0x1)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:534 +0xdf
        github.com/pachyderm/pachyderm/src/client/pkg/require.NoError(0x2833840, 0xc000543b00, 0x27b08a0, 0x37a0680, 0x0, 0x0, 0x0)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:394 +0xec
        github.com/pachyderm/pachyderm/src/server/pkg/obj/testing.getPachClient(0xc000543b00, 0xc0003ac8c0, 0xc000053340, 0x1c, 0x0)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pkg/obj/testing/deployment_test.go:190 +0xa3c
        github.com/pachyderm/pachyderm/src/server/pkg/obj/testing.withManifest(0xc000543b00, 0x3, 0xc000a892f0, 0xc00096ff60)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pkg/obj/testing/deployment_test.go:250 +0x4cd
        github.com/pachyderm/pachyderm/src/server/pkg/obj/testing.TestMicrosoftDeployment(0xc000543b00)
        	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pkg/obj/testing/deployment_test.go:421 +0x2d3
        testing.tRunner(0xc000543b00, 0x259bcc0)
        	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/testing/testing.go:1127 +0xef
        created by testing.(*T).Run
        	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/testing/testing.go:1178 +0x386
time="2021-01-11T21:35:16Z" level=warning msg="DEPRECATED: Support for the S3V2 option is being deprecated. It will be removed in a future version"
time="2021-01-11T21:35:16Z" level=warning msg="DEPRECATED: Support for the S3V2 option is being deprecated. It will be removed in a future version"
time="2021-01-11T21:35:16Z" level=warning msg="DEPRECATED: Support for the S3V2 option is being deprecated. It will be removed in a future version"
time="2021-01-11T21:35:16Z" level=warning msg="DEPRECATED: Support for the S3V2 option is being deprecated. It will be removed in a future version"
FAIL
FAIL	github.com/pachyderm/pachyderm/src/server/pkg/obj/testing	244.333s
FAIL
Makefile:276: recipe for target 'test-object-clients' failed
```

AmazonDeployment:
```
--- FAIL: TestAmazonDeployment (0.00s)
    --- FAIL: TestAmazonDeployment/AmazonObjectStorage (103.45s)
        deployment_test.go:190: No error is expected but got context deadline exceeded
        deployment_test.go:190: current stack:
            goroutine 163 [running]:
            runtime/debug.Stack(0x27b08a0, 0x37a0680, 0xc000b87348)
            	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/debug/stack.go:24 +0x9f
            github.com/pachyderm/pachyderm/src/client/pkg/require.fatal(0x2833840, 0xc0004b9380, 0x0, 0x0, 0x0, 0x24dad5a, 0x1f, 0xc000bac050, 0x1, 0x1)
            	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:534 +0xdf
            github.com/pachyderm/pachyderm/src/client/pkg/require.NoError(0x2833840, 0xc0004b9380, 0x27b08a0, 0x37a0680, 0x0, 0x0, 0x0)
            	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:394 +0xec
            github.com/pachyderm/pachyderm/src/server/pkg/obj/testing.getPachClient(0xc0004b9380, 0xc0000eedc0, 0xc0008a48c0, 0x1c, 0x0)
            	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pkg/obj/testing/deployment_test.go:190 +0xa3c
            github.com/pachyderm/pachyderm/src/server/pkg/obj/testing.withManifest(0xc0004b9380, 0x1, 0xc000952930, 0xc000b87f60)
            	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pkg/obj/testing/deployment_test.go:250 +0x4cd
            github.com/pachyderm/pachyderm/src/server/pkg/obj/testing.TestAmazonDeployment.func1(0xc0004b9380)
            	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pkg/obj/testing/deployment_test.go:337 +0x125
            testing.tRunner(0xc0004b9380, 0xc000586270)
            	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/testing/testing.go:1127 +0xef
            created by testing.(*T).Run
            	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/testing/testing.go:1178 +0x386
time="2021-01-11T21:42:58Z" level=warning msg="DEPRECATED: Support for the S3V2 option is being deprecated. It will be removed in a future version"
time="2021-01-11T21:42:58Z" level=warning msg="DEPRECATED: Support for the S3V2 option is being deprecated. It will be removed in a future version"
time="2021-01-11T21:42:58Z" level=warning msg="DEPRECATED: Support for the S3V2 option is being deprecated. It will be removed in a future version"
time="2021-01-11T21:42:58Z" level=warning msg="DEPRECATED: Support for the S3V2 option is being deprecated. It will be removed in a future version"
Failed to connect to pachd: context deadline exceeded
Used host:port: 10.30.2.20:31975
All nodes addresses:
 [0]: [{InternalIP 10.30.2.20} {Hostname travis-job-1b64d8a3-0859-4f54-ac4b-c2fe3c5a49d3}]
Pod logs:
2021-01-11T21:41:34Z INFO no Jaeger collector found (JAEGER_COLLECTOR_SERVICE_HOST not set)
2021-01-11T21:41:34Z WARNING TLS disabled: could not stat public cert at /pachd-tls-cert/tls.crt: stat /pachd-tls-cert/tls.crt: no such file or directory
2021-01-11T21:41:34Z INFO started setting up External Pachd GRPC Server
2021-01-11T21:41:34Z INFO started setting up PFS API GRPC Server
2021-01-11T21:41:34Z WARNING DEPRECATED: Support for the S3V2 option is being deprecated. It will be removed in a future version
--- FAIL: TestMinioDeployment (0.00s)
    --- FAIL: TestMinioDeployment/GoogleObjectStorage (0.00s)
        --- FAIL: TestMinioDeployment/GoogleObjectStorage/S3v4 (102.98s)
            deployment_test.go:190: No error is expected but got context deadline exceeded
            deployment_test.go:190: current stack:
                goroutine 333 [running]:
                runtime/debug.Stack(0x27b08a0, 0x37a0680, 0xc001247340)
                	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/debug/stack.go:24 +0x9f
                github.com/pachyderm/pachyderm/src/client/pkg/require.fatal(0x2833840, 0xc0008a7980, 0x0, 0x0, 0x0, 0x24dad5a, 0x1f, 0xc000656da0, 0x1, 0x1)
                	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:534 +0xdf
                github.com/pachyderm/pachyderm/src/client/pkg/require.NoError(0x2833840, 0xc0008a7980, 0x27b08a0, 0x37a0680, 0x0, 0x0, 0x0)
                	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/client/pkg/require/require.go:394 +0xec
                github.com/pachyderm/pachyderm/src/server/pkg/obj/testing.getPachClient(0xc0008a7980, 0xc000937540, 0xc0006d2c40, 0x1c, 0x0)
                	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pkg/obj/testing/deployment_test.go:190 +0xa3c
                github.com/pachyderm/pachyderm/src/server/pkg/obj/testing.withManifest(0xc0008a7980, 0x4, 0xc000834cc0, 0xc001247f60)
                	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pkg/obj/testing/deployment_test.go:250 +0x4cd
                github.com/pachyderm/pachyderm/src/server/pkg/obj/testing.TestMinioDeployment.func1.2(0xc0008a7980)
                	/home/travis/gopath/src/github.com/pachyderm/pachyderm/src/server/pkg/obj/testing/deployment_test.go:379 +0x4b3
                testing.tRunner(0xc0008a7980, 0xc0004ae230)
                	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/testing/testing.go:1127 +0xef
                created by testing.(*T).Run
                	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/testing/testing.go:1178 +0x386
FAIL
FAIL	github.com/pachyderm/pachyderm/src/server/pkg/obj/testing	269.044s
FAIL
Makefile:276: recipe for target 'test-object-clients' failed
make: *** [test-object-clients] Error 1
=== TEST FAILED OR TIMED OUT, DUMPING DEBUG INFO ===
```

Full Travis logs: [travis_logs.txt](https://github.com/pachyderm/pachyderm/files/5806446/travis_logs.txt)

**Comment by Tryneus** [comment]
I couldn't reproduce exactly this issue, but note that in the pod logs before each failure, server initialization never got past the `PFS API` server step - I suspect there is something there that is flaky or racy.  Another possibility is that the previous run crashed before accepting clients, and the new one took too long to come up (but was in the `PFS API` server setup when the test timed out).

I _did_, however, find this crash on one of the `pachd` pods, which _could_ be related:
```
2021-01-13T06:09:37Z INFO no Jaeger collector found (JAEGER_COLLECTOR_SERVICE_HOST not set)
2021-01-13T06:16:03Z WARNING TLS disabled: could not stat public cert at /pachd-tls-cert/tls.crt: stat /pachd-tls-cert/tls.crt: no such file or directory
2021-01-13T06:16:03Z INFO started setting up External Pachd GRPC Server
2021-01-13T06:16:03Z INFO started setting up PFS API GRPC Server
2021-01-13T06:16:03Z INFO finished setting up PFS API GRPC Server
2021-01-13T06:16:03Z INFO started setting up PPS API GRPC Server
panic: failed to initialize pach client: context deadline exceeded

goroutine 204 [running]:
github.com/pachyderm/pachyderm/src/server/pkg/serviceenv.(*ServiceEnv).GetPachClient(0xc0002e7200, 0x2a062e0, 0xc000138018, 0x46fa46)
        /app/src/server/pkg/serviceenv/service_env.go:214 +0x10d
github.com/pachyderm/pachyderm/src/server/pfs/server.newAPIServer.func1(0xc000526ae0)
        /app/src/server/pfs/server/api_server.go:56 +0x47
created by github.com/pachyderm/pachyderm/src/server/pfs/server.newAPIServer
        /app/src/server/pfs/server/api_server.go:56 +0x125
```
