### ISSUE TITLE
Rename/move/reflink support for a file

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#573]
When running a tensor flow pipeline, I'm outputting the model file in one pipeline (to pfs) so that I can load it in the following pipeline. However, it seems that the underlying python code that is writing the file creates a temp file, then renames it to the file in question. We don't seem to support the renaming function.

(On tensor_flow branch @ 429899778dce4e71bf6a501469f33a589bea6716)

``` shell
pachyderm$ watch "pachctl list-job"
pachyderm$ pachctl get-logs 25932baf338b212d4d81aa2b582c42d1
0 | 2016-06-22T18:54:22Z ERROR fuse.DirectoryLookup {"directory":{"file":{"commit":{"repo":{"name":"train"},"id":"bcc0e173d8344ce4a9a0f4e2134e65a5"}},"repoAlias":"out","write":true},"name":"model-results","err":"no such file or directory"}
0 | 2016-06-22T18:54:24Z ERROR fuse.DirectoryLookup {"directory":{"file":{"commit":{"repo":{"name":"train"},"id":"bcc0e173d8344ce4a9a0f4e2134e65a5"}},"repoAlias":"out","write":true},"name":"ptb.ckpt.tempstate16287961941828394479","err":"no such file or directory"}
0 | 2016-06-22T18:54:24Z ERROR fuse.DirectoryLookup {"directory":{"file":{"commit":{"repo":{"name":"train"},"id":"bcc0e173d8344ce4a9a0f4e2134e65a5"}},"repoAlias":"out","write":true},"name":"ptb.ckpt","err":"no such file or directory"}
0 | E tensorflow/core/util/tensor_slice_writer.cc:121] Failed to rename file /pfs/out/ptb.ckpt.tempstate16287961941828394479 to /pfs/out/ptb.ckpt
0 | Traceback (most recent call last):
0 |   File "ptb_word_lm.py", line 428, in <module>
0 |     tf.app.run()
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
0 |     sys.exit(main(sys.argv))
0 |   File "ptb_word_lm.py", line 319, in main
0 |     train(train_data, valid_data, test_data)
0 |   File "ptb_word_lm.py", line 351, in train
0 |     m.saver.save(session, os.path.join(FLAGS.model_path_prefix, "ptb.ckpt"))
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1037, in save
0 |     {self.saver_def.filename_tensor_name: checkpoint_file})
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 340, in run
0 |     run_metadata_ptr)
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 564, in _run
0 |     feed_dict_string, options, run_metadata)
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 637, in _do_run
0 |     target_list, options, run_metadata)
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 659, in _do_call
0 |     e.code)
0 | tensorflow.python.framework.errors.UnknownError: /pfs/out/ptb.ckpt.tempstate16287961941828394479; Input/output error
0 |      [[Node: model/save/save = SaveSlices[T=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_model/save/Const_0, model/save/save/tensor_names, model/save/save/shapes_and_slices, model/RNN/MultiRNNCell/Cell0/BasicLSTMCell/Linear/Bias, model/RNN/MultiRNNCell/Cell0/BasicLSTMCell/Linear/Matrix, model/embedding, model/softmax_b, model/softmax_w)]]
0 | Caused by op u'model/save/save', defined at:
0 |   File "ptb_word_lm.py", line 428, in <module>
0 |     tf.app.run()
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
0 |     sys.exit(main(sys.argv))
0 |   File "ptb_word_lm.py", line 319, in main
0 |     train(train_data, valid_data, test_data)
0 |   File "ptb_word_lm.py", line 334, in train
0 |     m = PTBModel(is_training=True, config=config)
0 |   File "ptb_word_lm.py", line 142, in __init__
0 |     self.saver = tf.train.Saver(tf.all_variables())
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 832, in __init__
0 |     restore_sequentially=restore_sequentially)
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 500, in build
0 |     save_tensor = self._AddSaveOps(filename_tensor, vars_to_save)
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 197, in _AddSaveOps
0 |     save = self.save_op(filename_tensor, vars_to_save)
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 149, in save_op
0 |     tensor_slices=[vs.slice_spec for vs in vars_to_save])
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/io_ops.py", line 172, in _save
0 |     tensors, name=name)
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 341, in _save_slices
0 |     name=name)
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 661, in apply_op
0 |     op_def=op_def)
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2154, in create_op
0 |     original_op=self._default_original_op, op_def=op_def)
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1154, in __init__
0 |     self._traceback = _extract_stack()
0 | 
0 | Error from exec: exit status 1
```

**Comment by sjezewski** [comment]
Discussed the design for this w @jdoliner  -- Here's where we landed:

## Constraints

1) fuse (the client in this case) needs the move operation to be atomic
2) there may be multiple `pps` containers doing the move, so we need to make sure concurrent requests to move are atomic within our API

## Design

1) `pfs.InternalApiServer` will add support for `DeleteFile` returning the list of blockrefs from the file
    - This allows us to grab the blockrefs, and delete atomically wrt `pfs.ApiServer`

2) `pfs.InternalApiServer` will add support for `PutFile` (or a variant) to accept blockrefs instead of bytes

3) `pfs.ApiServer` will expose a new `MoveFile()` method, which will
    - call `pfs.InternalApi.DeleteFile` and grab the blockrefs, then
    - call `pfs.InternalApi.PutFile` w these blockrefs
    - doing both these calls should guarantee the move is atomic wrt the (fuse) client

To be clear, the new `DiffInfo`s `Append` will have a key for the new filepath, and the value will be all of the cumulative blockrefs from the old file path. This basically squashes the history of the old file into a single commit for the new file.

**Comment by soshiant1992** [comment]
my tensorflow code works fine just when i try to save the model i get this err

E tensorflow/core/util/tensor_slice_writer.cc:121] Failed to rename file /home/xxxxxx/pytest/.tempstate16554456158648005478 to /home/xxxxxx/pytest/
E tensorflow/core/client/tensor_c_api.cc:485] /home/xxxxxx/pytest/.tempstate16554456158648005478

**Comment by sjezewski** [comment]
Ah, this is a known issue. Sorry you ran into this.

Right now our FUSE later doesn't have rename support. We should be able to address this soon (after the Pfs refactor lands).

But for now as a workaround I'll refer you to the transform supplied with the example. It does a few peculiar things to workaround this issue. Basically it makes sure to run the model w inputs that are copied from the Fuse mount and copies the results back to the output mount. This gets around the python program trying to rename things within Fuse.

**Comment by jdoliner** [comment]
Scheduling this for 1.3.

**Comment by sjezewski** [comment]
Bumping this to 1.4

Also since our FUSE usage pattern has changed quite a bit, we may want to re-evaluate which FUSE features we want to spend time on / support.

**Comment by sjezewski** [comment]
We no longer need to handle FUSE support for anything running in PPS
