### ISSUE TITLE
pachctl mount throws "panic: using reserved ID 1 for inode number" exception under linux

### ISSUE THREAD

**Issue by izapolsk** [pachyderm/pachyderm#5734]
When I try to mount a repo to local fs, I get exception like below.

```
(.venv) ➜  tmp  pachctl mount -r pull-data@master:/ /home/ez/tmp/mountpoint1
2021/02/23 12:25:13 using reserved ID 1 for inode number
panic: using reserved ID 1 for inode number

goroutine 55 [running]:
log.Panicf(0x2c015b1, 0x25, 0xc000a79b70, 0x1, 0x1)
        /usr/local/go/src/log/log.go:358 +0xc5
github.com/hanwen/go-fuse/v2/fs.(*rawBridge).newInodeUnlocked(0xc000930100, 0x2f2ed20, 0xc00084ca10, 0xc0000043ff, 0x1, 0x1, 0x2878400, 0x0)
        /Users/nitin/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.0.2/fs/bridge.go:60 +0xf4
github.com/hanwen/go-fuse/v2/fs.(*rawBridge).newInode(0xc000930100, 0x2f7d320, 0xc00034b9a0, 0x2f2ed20, 0xc00084ca10, 0x43ff, 0x1, 0x1, 0x0, 0x2)
        /Users/nitin/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.0.2/fs/bridge.go:106 +0x74
github.com/hanwen/go-fuse/v2/fs.(*Inode).newInode(...)
        /Users/nitin/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.0.2/fs/inode.go:349
github.com/hanwen/go-fuse/v2/fs.(*Inode).NewInode(...)
        /Users/nitin/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.0.2/fs/inode.go:345
github.com/pachyderm/pachyderm/src/server/pfs/fuse.(*loopbackNode).Lookup(0xc0007fc410, 0x2f7d320, 0xc00034b9a0, 0xc0002b1168, 0x2, 0xc00001e0a0, 0x0, 0x0)
        src/server/pfs/fuse/loopback.go:127 +0x24b
github.com/hanwen/go-fuse/v2/fs.(*rawBridge).lookup(0xc000930100, 0xc00034b9a0, 0xc0007fc410, 0xc0002b1168, 0x2, 0xc00001e0a0, 0x0, 0x0)
        /Users/nitin/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.0.2/fs/bridge.go:253 +0x204
github.com/hanwen/go-fuse/v2/fs.(*rawBridge).ReadDirPlus(0xc000930100, 0xc000064d20, 0xc000766cd8, 0xc0002bd980, 0x0)
        /Users/nitin/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.0.2/fs/bridge.go:883 +0x245
github.com/hanwen/go-fuse/v2/fuse.doReadDirPlus(0xc000699600, 0xc000766b40)
        /Users/nitin/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.0.2/fuse/opcode.go:175 +0xfc
github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc000699600, 0xc000766b40, 0xc000000000)
        /Users/nitin/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.0.2/fuse/server.go:470 +0x3c7
github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc000699600, 0xc000736001)
        /Users/nitin/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.0.2/fuse/server.go:437 +0x198
created by github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest
        /Users/nitin/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.0.2/fuse/server.go:304 +0x41d
```

**Environment**:
- Kubernetes version:
 ```
(.venv) ➜  tmp kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-dispatcher", GitCommit:"fd22db44e150011eccc8729db223945384460143", GitTreeState:"clean", BuildDate:"2020-07-24T07:27:52Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Pachyderm CLI and pachd server version (use `pachctl version`):
```
(.venv) ➜  tmp pachctl version
COMPONENT           VERSION
pachctl             1.12.3
pachd               1.12.3
```

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
on prem k8s

- OS (e.g. from /etc/os-release):
```
(.venv) ➜  tmp cat /etc/os-release
NAME=Fedora
VERSION="33 (Thirty Three)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora 33 (Thirty Three)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f33/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=33
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=33
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
```
- Others:
  Please  let me know if you need additional information.

**Comment by jdoliner** [comment]
Sorry you're hitting this. I think it's probably somewhat platform specific, this works fine for me on Ubuntu. I'm hoping the fix for this is as simple as starting our inode indexes at a higher value.

**Comment by echohack** [comment]
Hi @izapolsk Can you run `df -Th` and share with us the output? That might be helpful in reproducing your situation.

**Comment by izapolsk** [comment]
Hi @echohack, of course. 
here you go

```
➜  ~ df -TH
df: /home/ez/tmp/mountpoint: Transport endpoint is not connected
df: /home/ez/tmp/mountpoint1: Transport endpoint is not connected
Filesystem     Type      Size  Used Avail Use% Mounted on
devtmpfs       devtmpfs  8.4G     0  8.4G   0% /dev
tmpfs          tmpfs     8.4G  165M  8.2G   2% /dev/shm
tmpfs          tmpfs     3.4G  2.4M  3.4G   1% /run
tmpfs          tmpfs     4.2M     0  4.2M   0% /sys/fs/cgroup
/dev/sda2      xfs       108G  100G  8.4G  93% /
tmpfs          tmpfs     8.4G  185M  8.2G   3% /tmp
/dev/sda4      xfs       262G  161G  102G  62% /home
/dev/loop0     squashfs   59M   59M     0 100% /var/lib/snapd/snap/core18/1885
/dev/loop2     squashfs   32M   32M     0 100% /var/lib/snapd/snap/snapd/8790
/dev/loop1     squashfs  3.1M  3.1M     0 100% /var/lib/snapd/snap/yq/736
/dev/sda5      xfs       108G   44G   65G  41% /home/ez/Відео/more_space
/dev/sda1      vfat      521M   73M  448M  14% /boot/efi
tmpfs          tmpfs     1.7G  230k  1.7G   1% /run/user/1000
```

Please note that above mountpoints with endpoint errors are created by pachctl

**Comment by echohack** [comment]
@izapolsk Thanks for bringing this to our attention. We're looking at a few possible options for a fix. One possibility is that this is a bug regarding the fuse library we use:

https://github.com/hanwen/go-fuse/commit/1d0096e57910b8277fd8862b5f0932c04d41857b#diff-1521152f1fc3600273bda897c6[…]fc9cbe24046838f043a8040f0d67L259

I'll keep you updated as we look into the subject further. Thanks again!

**Comment by echohack** [comment]
Hi @izapolsk 

We're expecting this issue is fixed based on the above PR ^

I am going to close this issue now, If you encounter it again, please open a new issue and feel free to reference this one.

**Comment by izapolsk** [comment]
Hi @echohack, thanks.

btw, does it require updating server side ? I tried updating only client side and it didn't work.

**Comment by echohack** [comment]
@izapolsk Yes this requires updating to 1.12.5. Specifically, all your worker nodes will need to be updated, as well as pachd.
