### ISSUE TITLE
Tensor Flow doesn't like reading from a FUSE mount

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#577]
Came across this while trying to read a model from a file.
- Mounting locally (on my mac) and pointing the script there it worked fine
- Looking at checksums of the file on my mount and on the pipeline ... the file definitely matched / wasn't corrupted

Guessing they tried to seek when reading the file. Interesting that this only came up on linux ... possibly first time ever mac fuse worked over linux fuse?

The error reported by tensor flow is:

(repro steps below)

``` shell
pachyderm$ pc get-logs 7c4fb4444b77d6eefa7a70577e136c09
0 | 2016-06-22T23:44:54Z ERROR fuse.DirectoryLookup {"directory":{"file":{"commit":{"repo":{"name":"generate"},"id":"1e387765f17342baa171e3969169892c"}},"repoAlias":"out","write":true},"name":"input-data-provided","err":"no such file or directory"}
0 | 2016-06-22T23:44:54Z ERROR fuse.DirectoryLookup {"directory":{"file":{"commit":{"repo":{"name":"generate"},"id":"1e387765f17342baa171e3969169892c"}},"repoAlias":"out","write":true},"name":"ckpt-checksum","err":"no such file or directory"}
0 | 2016-06-22T23:44:54Z ERROR fuse.DirectoryLookup {"directory":{"file":{"commit":{"repo":{"name":"generate"},"id":"1e387765f17342baa171e3969169892c"}},"repoAlias":"out","write":true},"name":"generate-results","err":"no such file or directory"}
0 | W tensorflow/core/util/tensor_slice_reader.cc:93] Could not open /pfs/train/ptb.ckpt: Invalid argument: /pfs/train/ptb.ckpt: perhaps your file is in a different file format and you need to use a different restore operator?
0 | W tensorflow/core/util/tensor_slice_reader.cc:93] Could not open /pfs/train/ptb.ckpt: Invalid argument: /pfs/train/ptb.ckpt: perhaps your file is in a different file format and you need to use a different restore operator?
0 | W tensorflow/core/util/tensor_slice_reader.cc:93] Could not open /pfs/train/ptb.ckpt: Invalid argument: /pfs/train/ptb.ckpt: perhaps your file is in a different file format and you need to use a different restore operator?
0 | W tensorflow/core/framework/op_kernel.cc:900] Data loss: Unable to open table file /pfs/train/ptb.ckpt: Invalid argument: /pfs/train/ptb.ckpt: perhaps your file is in a different file format and you need to use a different restore operator?
0 | W tensorflow/core/util/tensor_slice_reader.cc:93] Could not open /pfs/train/ptb.ckpt: Invalid argument: /pfs/train/ptb.ckpt: perhaps your file is in a different file format and you need to use a different restore operator?
0 | W tensorflow/core/framework/op_kernel.cc:900] Data loss: Unable to open table file /pfs/train/ptb.ckpt: Invalid argument: /pfs/train/ptb.ckpt: perhaps your file is in a different file format and you need to use a different restore operator?
0 | W tensorflow/core/util/tensor_slice_reader.cc:93] Could not open /pfs/train/ptb.ckpt: Invalid argument: /pfs/train/ptb.ckpt: perhaps your file is in a different file format and you need to use a different restore operator?
0 | W tensorflow/core/util/tensor_slice_reader.cc:93] Could not open /pfs/train/ptb.ckpt: Invalid argument: /pfs/train/ptb.ckpt: perhaps your file is in a different file format and you need to use a different restore operator?
0 | W tensorflow/core/framework/op_kernel.cc:900] Data loss: Unable to open table file /pfs/train/ptb.ckpt: Invalid argument: /pfs/train/ptb.ckpt: perhaps your file is in a different file format and you need to use a different restore operator?
0 | W tensorflow/core/util/tensor_slice_reader.cc:93] Could not open /pfs/train/ptb.ckpt: Invalid argument: /pfs/train/ptb.ckpt: perhaps your file is in a different file format and you need to use a different restore operator?
0 | W tensorflow/core/util/tensor_slice_reader.cc:93] Could not open /pfs/train/ptb.ckpt: Invalid argument: /pfs/train/ptb.ckpt: perhaps your file is in a different file format and you need to use a different restore operator?
0 | W tensorflow/core/framework/op_kernel.cc:900] Data loss: Unable to open table file /pfs/train/ptb.ckpt: Invalid argument: /pfs/train/ptb.ckpt: perhaps your file is in a different file format and you need to use a different restore operator?
0 | W tensorflow/core/util/tensor_slice_reader.cc:93] Could not open /pfs/train/ptb.ckpt: Invalid argument: /pfs/train/ptb.ckpt: perhaps your file is in a different file format and you need to use a different restore operator?
0 | W tensorflow/core/util/tensor_slice_reader.cc:93] Could not open /pfs/train/ptb.ckpt: Invalid argument: /pfs/train/ptb.ckpt: perhaps your file is in a different file format and you need to use a different restore operator?
0 | W tensorflow/core/framework/op_kernel.cc:900] Data loss: Unable to open table file /pfs/train/ptb.ckpt: Invalid argument: /pfs/train/ptb.ckpt: perhaps your file is in a different file format and you need to use a different restore operator?
0 | Traceback (most recent call last):
0 |   File "ptb_word_lm.py", line 440, in <module>
0 |     tf.app.run()
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
0 |     sys.exit(main(sys.argv))
0 |   File "ptb_word_lm.py", line 322, in main
0 |     generate(word_to_id, id_to_word)
0 |   File "ptb_word_lm.py", line 380, in generate
0 |     m.saver.restore(session, os.path.join(FLAGS.model_path_prefix, "ptb.ckpt"))
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1090, in restore
0 |     {self.saver_def.filename_tensor_name: save_path})
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 340, in run
0 |     run_metadata_ptr)
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 564, in _run
0 |     feed_dict_string, options, run_metadata)
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 637, in _do_run
0 |     target_list, options, run_metadata)
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 659, in _do_call
0 |     e.code)
0 | tensorflow.python.framework.errors.DataLossError: Unable to open table file /pfs/train/ptb.ckpt: Invalid argument: /pfs/train/ptb.ckpt: perhaps your file is in a different file format and you need to use a different restore operator?
0 |      [[Node: model/save/restore_slice = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_model/save/Const_0, model/save/restore_slice/tensor_name, model/save/restore_slice/shape_and_slice)]]
0 | Caused by op u'model/save/restore_slice', defined at:
0 |   File "ptb_word_lm.py", line 440, in <module>
0 |     tf.app.run()
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
0 |     sys.exit(main(sys.argv))
0 |   File "ptb_word_lm.py", line 322, in main
0 |     generate(word_to_id, id_to_word)
0 |   File "ptb_word_lm.py", line 376, in generate
0 |     m = PTBModel(is_training=False, config=config)
0 |   File "ptb_word_lm.py", line 143, in __init__
0 |     self.saver = tf.train.Saver(tf.all_variables())
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 832, in __init__
0 |     restore_sequentially=restore_sequentially)
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 502, in build
0 |     filename_tensor, vars_to_save, restore_sequentially, reshape)
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 256, in _AddRestoreOps
0 |     values = self.restore_op(filename_tensor, vs, preferred_shard)
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 171, in restore_op
0 |     preferred_shard=preferred_shard)
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/io_ops.py", line 196, in _restore_slice
0 |     preferred_shard, name=name)
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 271, in _restore_slice
0 |     preferred_shard=preferred_shard, name=name)
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
0 |     op_def=op_def)
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2154, in create_op
0 |     original_op=self._default_original_op, op_def=op_def)
0 |   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1154, in __init__
0 |     self._traceback = _extract_stack()
0 | 
0 | Error from exec: exit status 1
```

To reproduce, checkout `8c26e0ca4298cfe72a14f4af559d14f638465181`, and run:

``` shell
cd examples/tensor_flow
make input-data; make run
```

The second job (the `generate` pipeline will fail. If you look at that jobs logs you'll see the above error.

**Comment by sjezewski** [comment]
If our guess is right and its a seek issue, this will be addressed by #529

**Comment by sjezewski** [comment]
BTW - The workaround is to copy the files out of the mount before reading them. This works fine.

**Comment by sjezewski** [comment]
We no longer user FUSE in PPS
