### ISSUE TITLE
pollPipelinePods fails on first run of pachd in 2.0 alpha

### ISSUE THREAD

**Issue by actgardner** [pachyderm/pachyderm#5891]
**What happened?**:

Starting pachd with a fresh etcd and postgres, the pachd pod hangs and crashes on the first run, then restarts:

```
panic: pollPipelinePods blocked for over a minute after cancellation; restarting container
goroutine 93 [running]:
github.com/pachyderm/pachyderm/v2/src/server/pps/server.(*ppsMaster).startMonitorThread.func2()
	/app/src/server/pps/server/monitor.go:172 +0x16e
github.com/pachyderm/pachyderm/v2/src/server/pps/server.(*ppsMaster).cancelPipelinePodsPoller(0xc00059de50)
	/app/src/server/pps/server/poller.go:48 +0x8b
github.com/pachyderm/pachyderm/v2/src/server/pps/server.(*ppsMaster).run(0xc00059de50)
	/app/src/server/pps/server/master.go:176 +0x41b
github.com/pachyderm/pachyderm/v2/src/server/pps/server.(*apiServer).master.func1(0x0, 0x0)
	/app/src/server/pps/server/master.go:123 +0x1b9
github.com/pachyderm/pachyderm/v2/src/internal/backoff.RetryUntilCancel(0x2b5fd60, 0xc0000580c8, 0xc000389fa0, 0x2b204a0, 0xc0002f1020, 0x28af618, 0x2, 0x1)
	/app/src/internal/backoff/retry.go:129 +0x56
github.com/pachyderm/pachyderm/v2/src/internal/backoff.RetryNotify(...)
	/app/src/internal/backoff/retry.go:118
github.com/pachyderm/pachyderm/v2/src/server/pps/server.(*apiServer).master(0xc000329440)
	/app/src/server/pps/server/master.go:112 +0x2bd
created by github.com/pachyderm/pachyderm/v2/src/server/pps/server.NewAPIServer
	/app/src/server/pps/server/server.go:69 +0x3ed
```

There's also some logs about migrations not being done yet, but it's not clear this is a contributing factor:
```
2021-03-24T15:40:45Z ERROR gc: pq: relation "storage.tracker_objects" does not exist
2021-03-24T15:40:55Z ERROR gc: pq: relation "storage.tracker_objects" does not exist
2021-03-24T15:41:05Z ERROR gc: pq: relation "storage.tracker_objects" does not exist
2021-03-24T15:41:15Z ERROR gc: pq: relation "storage.tracker_objects" does not exist
```

**What you expected to happen?**:

**How to reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by jdoliner** [comment]
@actgardner was this fixed or did the fix for this only apply to 1.x series?

**Comment by actgardner** [comment]
The fix I made was in 1.x, it looks like monitorPipeline has changed pretty substantially in 2.0
