### ISSUE TITLE
SegFault in TestFlush

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#5960]
Full test logs: [circle_output.txt](https://github.com/pachyderm/pachyderm/files/6281699/circle_output.txt)
Full circleCI debug output: [circle_debug.txt](https://github.com/pachyderm/pachyderm/files/6281701/circle_debug.txt)

```
Apr 08 20:05:57 === CONT  TestFlush
Apr 08 20:05:57     testdb.go:29: database test_49b858994e705941 successfully created
Apr 08 20:05:57 panic: runtime error: invalid memory address or nil pointer dereference
Apr 08 20:05:57 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1bee601]
Apr 08 20:05:57 
Apr 08 20:05:57 goroutine 442282 [running]:
Apr 08 20:05:57 github.com/coreos/bbolt.(*Tx).Bucket(...)
Apr 08 20:05:57 	/root/go/pkg/mod/github.com/coreos/bbolt@v1.3.3/tx.go:101
Apr 08 20:05:57 github.com/coreos/etcd/mvcc/backend.(*readTx).UnsafeRange(0xc024150960, 0x38d235c, 0x3, 0x3, 0xc0269739c0, 0x11, 0x12, 0x0, 0x0, 0x0, ...)
Apr 08 20:05:57 	/root/go/pkg/mod/github.com/coreos/etcd@v3.3.13+incompatible/mvcc/backend/read_tx.go:75 +0x641
Apr 08 20:05:57 github.com/coreos/etcd/mvcc.(*storeTxnRead).rangeKeys(0xc02c924060, 0xc028b76000, 0x2e, 0x30, 0x0, 0x0, 0x0, 0x14, 0x0, 0x0, ...)
Apr 08 20:05:57 	/root/go/pkg/mod/github.com/coreos/etcd@v3.3.13+incompatible/mvcc/kvstore_txn.go:140 +0x29c
Apr 08 20:05:57 github.com/coreos/etcd/mvcc.(*storeTxnRead).Range(0xc02c924060, 0xc028b76000, 0x2e, 0x30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x100000000000000, ...)
Apr 08 20:05:57 	/root/go/pkg/mod/github.com/coreos/etcd@v3.3.13+incompatible/mvcc/kvstore_txn.go:45 +0xaf
Apr 08 20:05:57 github.com/coreos/etcd/mvcc.(*metricsTxnWrite).Range(0xc02c924090, 0xc028b76000, 0x2e, 0x30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x520000, ...)
Apr 08 20:05:57 	/root/go/pkg/mod/github.com/coreos/etcd@v3.3.13+incompatible/mvcc/metrics_txn.go:38 +0xaf
Apr 08 20:05:57 github.com/coreos/etcd/etcdserver.(*applierV3backend).Range(0xc0273cf840, 0x0, 0x0, 0xc026977a40, 0x0, 0x0, 0x0)
Apr 08 20:05:57 	/root/go/pkg/mod/github.com/coreos/etcd@v3.3.13+incompatible/etcdserver/apply.go:269 +0x163
Apr 08 20:05:57 github.com/coreos/etcd/etcdserver.(*EtcdServer).Range.func3()
Apr 08 20:05:57 	/root/go/pkg/mod/github.com/coreos/etcd@v3.3.13+incompatible/etcdserver/v3_server.go:103 +0x62
Apr 08 20:05:57 github.com/coreos/etcd/etcdserver.(*EtcdServer).doSerialize(0xc0004dea00, 0x29b58c0, 0xc02c3dd4a0, 0xc015b33690, 0xc015b336a8, 0x2976c60, 0xc00015f200)
Apr 08 20:05:57 	/root/go/pkg/mod/github.com/coreos/etcd@v3.3.13+incompatible/etcdserver/v3_server.go:542 +0xf4
Apr 08 20:05:57 github.com/coreos/etcd/etcdserver.(*EtcdServer).Range(0xc0004dea00, 0x29b58c0, 0xc02c3dd4a0, 0xc026977a40, 0x0, 0x0, 0x0)
Apr 08 20:05:57 	/root/go/pkg/mod/github.com/coreos/etcd@v3.3.13+incompatible/etcdserver/v3_server.go:104 +0x198
Apr 08 20:05:57 github.com/coreos/etcd/etcdserver/api/v3rpc.(*kvServer).Range(0xc0222e75c0, 0x29b58c0, 0xc02c3dd4a0, 0xc026977a40, 0x23a0740, 0x0, 0x29be540)
Apr 08 20:05:57 	/root/go/pkg/mod/github.com/coreos/etcd@v3.3.13+incompatible/etcdserver/api/v3rpc/key.go:52 +0x79
Apr 08 20:05:57 github.com/coreos/etcd/etcdserver/etcdserverpb._KV_Range_Handler.func1(0x29b58c0, 0xc02c3dd4a0, 0x2571dc0, 0xc026977a40, 0x16, 0xc026ab2e60, 0x1, 0x10100c02ec67888)
Apr 08 20:05:57 	/root/go/pkg/mod/github.com/coreos/etcd@v3.3.13+incompatible/etcdserver/etcdserverpb/rpc.pb.go:3309 +0x89
Apr 08 20:05:57 github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x29b58c0, 0xc02c3dd4a0, 0x2571dc0, 0xc026977a40, 0xc0168f2d00, 0xc0168f2d20, 0xc0007862c0, 0x39c3870, 0x2422880, 0xc02c3f4f30)
Apr 08 20:05:57 	/root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.1-0.20191002090509-6af20e3a5340/server_metrics.go:108 +0xad
Apr 08 20:05:57 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x29b58c0, 0xc02c3dd4a0, 0x2571dc0, 0xc026977a40, 0x39c5ca0, 0xc028b76000, 0xc02ec679b0, 0x1b272cd)
Apr 08 20:05:57 	/root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/chain.go:25 +0x63
Apr 08 20:05:57 github.com/coreos/etcd/etcdserver/api/v3rpc.newUnaryInterceptor.func1(0x29b58c0, 0xc02c3dd4a0, 0x2571dc0, 0xc026977a40, 0xc0168f2d00, 0xc0168f2d40, 0x49b1c6, 0x606f6225, 0x152131cd, 0x8c784b1de0)
Apr 08 20:05:57 	/root/go/pkg/mod/github.com/coreos/etcd@v3.3.13+incompatible/etcdserver/api/v3rpc/interceptor.go:59 +0xca
Apr 08 20:05:57 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x29b58c0, 0xc02c3dd4a0, 0x2571dc0, 0xc026977a40, 0x7faa4eed2fd8, 0xc02ec67a18, 0x5b8dde, 0xc026977a40)
Apr 08 20:05:57 	/root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/chain.go:25 +0x63
Apr 08 20:05:57 github.com/coreos/etcd/etcdserver/api/v3rpc.newLogUnaryInterceptor.func1(0x29b58c0, 0xc02c3dd4a0, 0x2571dc0, 0xc026977a40, 0xc0168f2d00, 0xc0168f2d60, 0x0, 0x0, 0x0, 0x0)
Apr 08 20:05:57 	/root/go/pkg/mod/github.com/coreos/etcd@v3.3.13+incompatible/etcdserver/api/v3rpc/interceptor.go:66 +0xd1
Apr 08 20:05:57 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x29b58c0, 0xc02c3dd4a0, 0x2571dc0, 0xc026977a40, 0xc02865c100, 0x0, 0xc02ec67b30, 0x410018)
Apr 08 20:05:57 	/root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/chain.go:25 +0x63
Apr 08 20:05:57 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x29b58c0, 0xc02c3dd4a0, 0x2571dc0, 0xc026977a40, 0xc0168f2d00, 0xc0168f2d20, 0xc02ec67ba0, 0x51fba6, 0x2477600, 0xc02c3dd4a0)
Apr 08 20:05:57 	/root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/chain.go:34 +0xd7
Apr 08 20:05:57 github.com/coreos/etcd/etcdserver/etcdserverpb._KV_Range_Handler(0x23a0740, 0xc0222e7600, 0x29b58c0, 0xc02c3dd4a0, 0xc0333df200, 0xc0309e4a20, 0x29b58c0, 0xc02c3dd4a0, 0xc028627fb0, 0x30)
Apr 08 20:05:57 	/root/go/pkg/mod/github.com/coreos/etcd@v3.3.13+incompatible/etcdserver/etcdserverpb/rpc.pb.go:3311 +0x150
Apr 08 20:05:57 google.golang.org/grpc.(*Server).processUnaryRPC(0xc000698680, 0x29d4960, 0xc026633980, 0xc02865c100, 0xc0309e4ba0, 0x396ed60, 0x0, 0x0, 0x0)
Apr 08 20:05:57 	/root/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1082 +0x522
Apr 08 20:05:57 google.golang.org/grpc.(*Server).handleStream(0xc000698680, 0x29d4960, 0xc026633980, 0xc02865c100, 0x0)
Apr 08 20:05:57 	/root/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1405 +0xcc5
Apr 08 20:05:57 google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc02e9d5430, 0xc000698680, 0x29d4960, 0xc026633980, 0xc02865c100)
Apr 08 20:05:57 	/root/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xa5
Apr 08 20:05:57 created by google.golang.org/grpc.(*Server).serveStreams.func1
Apr 08 20:05:57 	/root/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xa5
Apr 08 20:05:57 FAIL	github.com/pachyderm/pachyderm/v2/src/server/pfs/server/testing	61.117s
Apr 08 20:05:57 FAIL
Apr 08 20:05:57 make: *** [Makefile:269: test-pfs-server] Error 1
Apr 08 20:05:57 
Apr 08 20:05:57 real	6m4.088s
Apr 08 20:05:57 user	0m0.022s
Apr 08 20:05:57 sys	0m0.005s

Exited with code exit status 2
CircleCI received exit code 2
```

**Comment by jdoliner** [comment]
@brycemcanally this looks like a segfault that's coming from Bolt. I remember hitting a lot of issues like this when we first added bolt and fixing a bunch of them. Do you have any memory of what we wound up changing to stop the segfaults?

**Comment by jdoliner** [comment]
Also @brycemcanally and @brendoncarroll correct me if I'm wrong but Bolt is going to be fully removed in 2.0 so unless we see this issue affecting users we can probably punt on it until then.

**Comment by brycemcanally** [comment]
This is etcd's bbolt, not ours. Also, this is running on 2.0. We should probably upgrade etcd before the 2.0 GA.

**Comment by pappasilenus** [comment]
<div>Agent Jan Schwoebel linked Freshdesk ticket <a href="https://pachyderm-support.freshdesk.com/a/tickets/212">212</a> for this issue.</div>

**Comment by pappasilenus** [comment]
<div>Agent Jan Schwoebel unlinked Freshdesk ticket <a href="https://pachyderm-support.freshdesk.com/a/tickets/212">212</a> from this issue.</div>
