### ISSUE TITLE
segfault from `DeleteRepo{all: true}`

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#6156]
This appeared while testing python-pachyderm against pachd v2.0.0-alpha.12

```
2021-05-20T16:20:01Z INFO pfs.API.DeleteRepo {"request":{"all":true}} []
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e7830e]

goroutine 4862 [running]:
github.com/pachyderm/pachyderm/v2/src/internal/collection.runSTM.func1.1(0xc000d6f5c0)
	/app/src/internal/collection/transaction.go:101 +0xa5
panic(0x2406ee0, 0x3b7d330)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/pachyderm/pachyderm/v2/src/server/pfs/server.(*validatedAPIServer).DeleteRepoInTransaction(0xc00009aa40, 0xc000d77c70, 0xc000df85a0, 0xc000df85a0, 0x30)
	/app/src/server/pfs/server/val_server.go:35 +0x4e
github.com/pachyderm/pachyderm/v2/src/internal/transactionenv.(*directTransaction).DeleteRepo(0xc00011a5d0, 0xc000d9ddd0, 0x1e76a01, 0xc00011a5d0)
	/app/src/internal/transactionenv/env.go:251 +0x79
github.com/pachyderm/pachyderm/v2/src/server/pfs/server.(*apiServer).DeleteRepo.func3(0x2b81dc0, 0xc00011a5d0, 0xc000d77c70, 0x2b1fae0)
	/app/src/server/pfs/server/api_server.go:138 +0x3a
github.com/pachyderm/pachyderm/v2/src/internal/transactionenv.(*TransactionEnv).WithTransaction.func1(0xc000d77c70, 0xc000d77c70, 0x2b1fae0)
	/app/src/internal/transactionenv/env.go:388 +0x6b
github.com/pachyderm/pachyderm/v2/src/internal/transactionenv.(*TransactionEnv).WithWriteContext.func1(0x2b832c0, 0xc00059f100, 0xc0009bef90, 0xc0009befa8)
	/app/src/internal/transactionenv/env.go:408 +0x113
github.com/pachyderm/pachyderm/v2/src/internal/collection.runSTM.func1(0xc000d6f5c0, 0x2b832c0, 0xc00059f100, 0xc000df83c0, 0x40e300)
	/app/src/internal/collection/transaction.go:109 +0x95
created by github.com/pachyderm/pachyderm/v2/src/internal/collection.runSTM
	/app/src/internal/collection/transaction.go:95 +0x86
```

**Comment by brycemcanally** [comment]
A workaround for this should be in the most recent alpha, which just skips the auth check. We need to decide on what the auth should be for this functionality before GA. I added a 2.0 required TODO for that.

**Comment by brycemcanally** [comment]
Fixed by https://github.com/pachyderm/pachyderm/pull/6171
