### ISSUE TITLE
Pipeline Unexpectedly Failing and Never Recovers (2.0.0-alpha.18)

### ISSUE THREAD

**Issue by dgeorg42** [pachyderm/pachyderm#6205]
I was committing files to a directory in a repo 20,000 files at a time. I have a pipeline that processes all of the files in the directory as a single datum.  So the first run of the pipeline has 1 datum of 20,000 files, the next run has 1 datum of 40,000 files, etc.  At first, everything runs fine. Then, as you can see below, we get to a point where the job never completes (it's been running for almost an hour), but keeps restarting (17 times and counting):
```
ID                               PIPELINE           STARTED           DURATION           RESTART PROGRESS  DL       UL       STATE   
**009a9ad06d20491fbca26d7b433a41c2 benchmarking       52 minutes ago    -                  17      0 + 0 / 0 0B       0B       running** 
e83f4123b489486793bf2d5d1316cdf7 benchmarking       56 minutes ago    2 minutes          0       1 + 0 / 1 795.9MiB 795.9MiB success 
d152b47af14b4a93b1c70f4b54e03781 benchmarking       59 minutes ago    About a minute     0       1 + 0 / 1 663.1MiB 663.1MiB success 
6e0b72ed5298478caeed2db8a011bdd5 benchmarking       About an hour ago 2 minutes          0       1 + 0 / 1 530.3MiB 530.3MiB success 
e012e91ab1f34879a98dd4555cbad6a6 benchmarking       About an hour ago About a minute     0       1 + 0 / 1 397.9MiB 397.9MiB success 
290b237cdbc14fabb5e51ec8eeaea975 benchmarking       About an hour ago 35 seconds         0       1 + 0 / 1 265.2MiB 265.2MiB success 
e8ad7a41bcc6428b999880bd5132d082 benchmarking       About an hour ago 16 seconds         0       1 + 0 / 1 132.7MiB 132.7MiB success 
```

`kubectl get pods` shows that the pipeline pod has restarted twice as well:
```
pipeline-benchmarking-v1-drdq6         2/2     Running   2          112m
```

Looking at the log for the previous restart of the pod, we see the following errors:
```
{"pipelineName":"benchmarking","pipelineJobId":"6e0b72ed5298478caeed2db8a011bdd5","workerId":"pipeline-benchmarking-v1-drdq6","master":true,"ts":"2021-05-27T19:00:40.655511163Z","message":"errored processing job running: rpc error: code = Unknown desc = cannot write path (/meta/82711208bac024944ea98cd6b8ab98a4a03cdc60247f8ae2294e0af87f2dd35f/meta) after (/pfs/82711208bac024944ea98cd6b8ab98a4a03cdc60247f8ae2294e0af87f2dd35f/source/main.py)"}
{"pipelineName":"benchmarking","pipelineJobId":"6e0b72ed5298478caeed2db8a011bdd5","workerId":"pipeline-benchmarking-v1-drdq6","master":true,"ts":"2021-05-27T19:00:40.655605563Z","message":"processJob error: rpc error: code = Unknown desc = cannot write path (/meta/82711208bac024944ea98cd6b8ab98a4a03cdc60247f8ae2294e0af87f2dd35f/meta) after (/pfs/82711208bac024944ea98cd6b8ab98a4a03cdc60247f8ae2294e0af87f2dd35f/source/main.py), retrying in 468.857094ms"}
{"pipelineName":"benchmarking","pipelineJobId":"6e0b72ed5298478caeed2db8a011bdd5","workerId":"pipeline-benchmarking-v1-drdq6","master":true,"ts":"2021-05-27T19:00:40.708704998Z","message":"error in superviseJob: rpc error: code = Unavailable desc = transport is closing, retrying in 462.318748ms"}
{"pipelineName":"benchmarking","workerId":"pipeline-benchmarking-v1-drdq6","master":true,"ts":"2021-05-27T19:00:40.708705924Z","message":"errored transform spawner process: transport is closing"}
{"pipelineName":"benchmarking","pipelineJobId":"6e0b72ed5298478caeed2db8a011bdd5","workerId":"pipeline-benchmarking-v1-drdq6","master":true,"ts":"2021-05-27T19:00:40.708704998Z","message":"error in superviseJob: rpc error: code = Unavailable desc = transport is closing, retrying in 462.318748ms"}
**{"pipelineName":"benchmarking","workerId":"pipeline-benchmarking-v1-drdq6","master":true,"ts":"2021-05-27T19:00:40.710069096Z","message":"master: error running the master process, retrying in 11.868230729s: transport is closing"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x1b957c1]**

goroutine 1973 [running]:
github.com/pachyderm/pachyderm/v2/src/server/worker/pipeline/transform.(*registry).superviseJob(0xc0000e2d20, 0xc000962140, 0x0, 0x0)
	/app/src/server/worker/pipeline/transform/registry.go:372 +0xe1
github.com/pachyderm/pachyderm/v2/src/server/worker/pipeline/transform.(*registry).startPipelineJob.func3.2(0xc000455e80, 0xc000455e60)
	/app/src/server/worker/pipeline/transform/registry.go:292 +0x33
github.com/pachyderm/pachyderm/v2/src/internal/backoff.RetryUntilCancel(0x22f7980, 0xc001104570, 0xc000455f38, 0x22c7390, 0xc000b82b40, 0xc000455f28, 0xc0006ebfa0, 0xa)
	/app/src/internal/backoff/retry.go:129 +0x56
github.com/pachyderm/pachyderm/v2/src/server/worker/pipeline/transform.(*registry).startPipelineJob.func3(0x0, 0x0)
	/app/src/server/worker/pipeline/transform/registry.go:291 +0x169
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00014f590, 0xc0006dbcc0)
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
```

And looking at the current log, we can see that there are a lot of errors like the following, saying that the job is erroring out because it "cannot write path":
```
{"pipelineName":"benchmarking","pipelineJobId":"009a9ad06d20491fbca26d7b433a41c2","workerId":"pipeline-benchmarking-v1-drdq6","master":true,"ts":"2021-05-27T20:14:49.092662695Z","message":"errored processing job running: rpc error: code = Unknown desc = cannot write path (/pfs/82711208bac024944ea98cd6b8ab98a4a03cdc60247f8ae2294e0af87f2dd35f/out/044844.jpg) after (/pfs/82711208bac024944ea98cd6b8ab98a4a03cdc60247f8ae2294e0af87f2dd35f/source/main.py)"}
```

**Comment by nitinjainsj** [comment]
We would want to do this test post the global ID code changes & autoscaling changes.

**Comment by brendoncarroll** [comment]
That error appears to be from the `fileset.Writer`.  `/out` comes after `/source` lexicographically and you can't write to a single fileset out of lexicographical order.  This is usually avoided by buffering paths in the `fileset.UnorderedWriter`.  And that is what is used when PPS or the user uploads data.  For some reason, it looks like we aren't using the UnorderedWriter

**Comment by brycemcanally** [comment]
This should be fixed in the most recent alpha.

**Comment by dgeorg42** [comment]
Just a confirmation that I'm not seeing this as I test Beta 1.
