### ISSUE TITLE
Pachd crashes with a database error even though there isn't a database error.

### ISSUE THREAD

**Issue by jrockway** [pachyderm/pachyderm#6597]
pachd beta3 started up ok, talking to a pgbouncer, but then crashed.  pgbouncer was available at the point of connection trouble, but it's unclear to me if the first lines of successful migrations were through pgbouncer or not.

```
$ kubectl logs pachd-649b55d679-8fqkc --previous
2021-07-23T04:31:00Z INFO maxprocs: Honoring GOMAXPROCS="3" as set in environment
2021-07-23T04:31:00Z INFO no Jaeger collector found (JAEGER_COLLECTOR_SERVICE_HOST not set)
2021-07-23T04:31:02Z WARNING {"error":{"ExistingCollector":{},"NewCollector":{}}} problem registering database statistics collector
2021-07-23T04:31:04Z WARNING {"error":{"ExistingCollector":{},"NewCollector":{}}} problem registering database statistics collector
2021-07-23T04:31:06Z WARNING {"error":{"ExistingCollector":{},"NewCollector":{}}} problem registering database statistics collector
2021-07-23T04:31:08Z WARNING {"error":{"ExistingCollector":{},"NewCollector":{}}} problem registering database statistics collector
2021-07-23T04:31:10Z WARNING {"error":{"ExistingCollector":{},"NewCollector":{}}} problem registering database statistics collector
2021-07-23T04:31:10Z INFO migration 0 already applied
2021-07-23T04:31:10Z INFO migration 1 already applied
2021-07-23T04:31:10Z INFO migration 2 already applied
2021-07-23T04:31:10Z INFO migration 3 already applied
2021-07-23T04:31:10Z INFO migration 4 already applied
2021-07-23T04:31:10Z INFO migration 5 already applied
2021-07-23T04:31:10Z INFO migration 6 already applied
2021-07-23T04:31:10Z INFO migration 7 already applied
2021-07-23T04:31:10Z INFO migration 8 already applied
2021-07-23T04:31:10Z INFO migration 9 already applied
2021-07-23T04:31:10Z INFO migration 10 already applied
2021-07-23T04:31:10Z INFO migration 11 already applied
2021-07-23T04:31:10Z INFO migration 12 already applied
2021-07-23T04:31:10Z INFO migration 13 already applied
2021-07-23T04:31:10Z INFO migration 14 already applied
2021-07-23T04:31:10Z INFO migration 15 already applied
2021-07-23T04:31:10Z INFO migration 16 already applied
2021-07-23T04:31:10Z INFO migration 17 already applied
2021-07-23T04:31:10Z INFO migration 18 already applied
2021-07-23T04:31:10Z INFO migration 19 already applied
2021-07-23T04:31:10Z INFO migration 20 already applied
2021-07-23T04:31:10Z INFO started setting up External Pachd GRPC Server
2021-07-23T04:31:10Z INFO started setting up PFS API GRPC Server
2021-07-23T04:31:10Z INFO finished setting up PFS API GRPC Server
2021-07-23T04:31:10Z INFO started setting up PPS API GRPC Server
2021-07-23T04:31:10Z INFO validating kubernetes access returned no errors
2021-07-23T04:31:10Z INFO finished setting up PPS API GRPC Server
2021-07-23T04:31:10Z INFO started setting up Identity API GRPC Server
2021-07-23T04:31:10Z INFO finished setting up Identity API GRPC Server
2021-07-23T04:31:10Z INFO finished setting up External Pachd GRPC Server
panic: failed to perform migrations: creating migration table: dial tcp 10.156.48.225:5432: connect: connection refused

goroutine 1 [running]:
github.com/pachyderm/pachyderm/v2/src/internal/serviceenv.(*NonblockingServiceEnv).GetDexDB(0xc0002c8200, 0xc, 0x1)
        /Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/internal/serviceenv/service_env.go:468 +0xb3
github.com/pachyderm/pachyderm/v2/src/server/identity/server.NewIdentityServer(0x2ba8e18, 0xc0002c8200, 0xc0006c7a01, 0x1, 0x1)
        /Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/server/identity/server/api_server.go:53 +0x8d
main.doFullMode.func3.3(0xc0001a2070, 0x27ce2dc)
        /Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/server/cmd/pachd/main.go:618 +0x48
main.logGRPCServerSetup(0x279760f, 0xc, 0xc0006c7b48, 0x0, 0x0)
        /Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/server/cmd/pachd/main.go:901 +0xfa
main.doFullMode.func3(0xc0001a2070, 0x27ce2dc)
        /Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/server/cmd/pachd/main.go:617 +0x205
main.logGRPCServerSetup(0x279b55c, 0xe, 0xc00073fe40, 0x0, 0x0)
        /Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/server/cmd/pachd/main.go:901 +0xfa
main.doFullMode(0x22b0080, 0xc0001eee00, 0x0, 0x0)
        /Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/server/cmd/pachd/main.go:588 +0x750
github.com/pachyderm/pachyderm/v2/src/internal/cmdutil.Main(0x28af9b0, 0x22b0080, 0xc0001eee00, 0x0, 0x0, 0x0)
        /Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/internal/cmdutil/env.go:33 +0x86
main.main()
        /Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/server/cmd/pachd/main.go:80 +0x26c
```

10.156.48.225 is pg-bouncer.default.svc.cluster.local.

pgbouncer logs say:

```
2021-07-23 04:31:01.474 UTC [1] LOG kernel file descriptor limit: 1048576 (hard: 1048576); max_client_conn: 1000, max expected fd use: 1012
2021-07-23 04:31:01.474 UTC [1] LOG listening on 0.0.0.0:5432
2021-07-23 04:31:01.474 UTC [1] LOG process up: PgBouncer 1.15.0, libevent 2.1.12-stable (epoll), adns: udns 0.4, tls: OpenSSL 1.1.1k  25 Mar 2021
2021-07-23 04:31:10.718 UTC [1] LOG C-0x7fea50aab0e0: (nodb)/(nouser)@10.160.0.32:59096 registered new auto-database: db=pachyderm
2021-07-23 04:31:10.718 UTC [1] LOG C-0x7fea50aab0e0: pachyderm/postgres@10.160.0.32:59096 login attempt: db=pachyderm user=postgres tls=no
2021-07-23 04:31:10.719 UTC [1] LOG S-0x7fea50aa4100: pachyderm/postgres@10.156.53.166:5432 new connection to server (from 10.160.0.33:51268)
2021-07-23 04:31:10.864 UTC [1] LOG C-0x7fea50aab0e0: pachyderm/postgres@10.160.0.32:59096 closing because: client unexpected eof (age=0s)
2021-07-23 04:31:11.939 UTC [1] LOG C-0x7fea50aab0e0: (nodb)/(nouser)@10.160.0.32:59134 registered new auto-database: db=dex
2021-07-23 04:31:11.939 UTC [1] LOG C-0x7fea50aab0e0: dex/postgres@10.160.0.32:59134 login attempt: db=dex user=postgres tls=no
2021-07-23 04:31:11.939 UTC [1] LOG C-0x7fea50aab310: pachyderm/postgres@10.160.0.32:59132 login attempt: db=pachyderm user=postgres tls=no
2021-07-23 04:31:11.940 UTC [1] LOG S-0x7fea50aa4330: dex/postgres@10.156.53.166:5432 new connection to server (from 10.160.0.33:51312)
2021-07-23 04:31:12.140 UTC [1] LOG C-0x7fea50aab540: pachyderm/postgres@10.160.0.32:59152 login attempt: db=pachyderm user=postgres tls=no
2021-07-23 04:31:12.141 UTC [1] LOG S-0x7fea50aa4560: pachyderm/postgres@10.156.53.166:5432 new connection to server (from 10.160.0.33:51324)
2021-07-23 04:31:32.841 UTC [1] LOG C-0x7fea50aab770: pachyderm/postgres@10.160.0.32:59354 login attempt: db=pachyderm user=postgres tls=no
2021-07-23 04:31:32.842 UTC [1] LOG S-0x7fea50aa4790: pachyderm/postgres@10.156.53.166:5432 new connection to server (from 10.160.0.33:51526)
2021-07-23 04:31:32.859 UTC [1] LOG C-0x7fea50aab770: pachyderm/postgres@10.160.0.32:59354 closing because: client close request (age=0s)
2021-07-23 04:32:01.475 UTC [1] LOG stats: 1 xacts/s, 3 queries/s, in 199 B/s, out 204 B/s, xact 3086 us, query 1046 us, wait 1088 us
```

The relevant line, I think, is "client unexpected eof"... leads me to believe it was connected and then crashed, so "connection refused" seems weird on a subsequent dial.

10.160.0.32 is pod:pachd.  10.156.43.166 is svc:cloudsql-auth-proxy.  10.160.0.33 is pod:pg-bouncer.  

Yes, pg-bouncer must have started later than pachd in order to get a 1-higher IP address, so maybe it simply wasn't ready when we checked.  Unclear.

In case I mis-mapped IP addresses... have the whole dump ;)

services:

```
$ kubectl get svc -o wide
NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                                            AGE     SELECTOR
cloudsql-auth-proxy    ClusterIP      10.156.53.166   <none>          5432/TCP                                           3m47s   app=cloudsql-auth-proxy,suite=pachyderm
dash                   ClusterIP      10.156.53.180   <none>          4000/TCP                                           3m47s   app=dash,suite=pachyderm
etcd                   ClusterIP      10.156.60.142   <none>          2379/TCP                                           3m47s   app=etcd
etcd-headless          ClusterIP      None            <none>          2380/TCP                                           3m47s   app=etcd
kubernetes             ClusterIP      10.156.48.1     <none>          443/TCP                                            8m41s   <none>
loki                   ClusterIP      10.156.51.222   <none>          3100/TCP                                           3m55s   app=loki,release=loki
loki-headless          ClusterIP      None            <none>          3100/TCP                                           3m55s   app=loki,release=loki
pachd                  ClusterIP      10.156.58.5     <none>          30650/TCP,30657/TCP,30658/TCP,30600/TCP,1656/TCP   3m47s   app=pachd
pachd-lb               LoadBalancer   10.156.60.13    34.68.168.218   31400:31588/TCP,30652:30459/TCP,30600:30615/TCP    3m47s   app=pachd
pachd-peer             ClusterIP      10.156.61.218   <none>          30653/TCP                                          3m47s   app=pachd
pg-bouncer             ClusterIP      10.156.48.225   <none>          5432/TCP                                           2m32s   app=pg-bouncer,suite=pachyderm
release-name-traefik   LoadBalancer   10.156.53.62    34.68.168.218   80:30686/TCP,443:32025/TCP                         5m17s   app=traefik,release=release-name
```

pods:
```
$ kubectl get pods -o wide
NAME                                   READY   STATUS    RESTARTS   AGE     IP            NODE                                          NOMINATED NODE   READINESS GATES
cloudsql-auth-proxy-86cc7c49-xjjnh     1/1     Running   0          3m36s   10.160.0.17   gke-hub-c0-wb1f00tc6r-default-3f254aa9-hx9n   <none>           <none>
dash-5f674686cf-7zts6                  1/1     Running   0          3m36s   10.160.0.16   gke-hub-c0-wb1f00tc6r-default-3f254aa9-hx9n   <none>           <none>
etcd-0                                 1/1     Running   0          3m35s   10.160.0.21   gke-hub-c0-wb1f00tc6r-default-3f254aa9-hx9n   <none>           <none>
loki-0                                 1/1     Running   0          3m44s   10.160.0.22   gke-hub-c0-wb1f00tc6r-default-3f254aa9-hx9n   <none>           <none>
loki-promtail-9zsrg                    1/1     Running   0          3m44s   10.160.0.13   gke-hub-c0-wb1f00tc6r-default-3f254aa9-hx9n   <none>           <none>
pachd-649b55d679-8fqkc                 1/1     Running   1          2m20s   10.160.0.32   gke-hub-c0-wb1f00tc6r-default-3f254aa9-hx9n   <none>           <none>
pg-bouncer-854d44b44b-pcgww            1/1     Running   0          2m20s   10.160.0.33   gke-hub-c0-wb1f00tc6r-default-3f254aa9-hx9n   <none>           <none>
release-name-traefik-ccf789bbf-6qxvb   1/1     Running   0          5m5s    10.160.0.9    gke-hub-c0-wb1f00tc6r-default-3f254aa9-hx9n   <none>           <none>
```

**Comment by jrockway** [comment]
I have less confidence in the reproducibility of this issue.  I carefully sequenced the rollout of pgbouncer to be ready before pachd was upgraded, and there were no problems this time, example maybe a long delay between "finished setting up internal grpc server" and "PPS master: launching master process".

```
2021-07-23T04:54:02Z INFO finished setting up Internal Pachd GRPC Server
2021-07-23T04:54:18Z INFO PPS master: launching master process
```

**Comment by jdoliner** [comment]
@brendoncarroll would probably be a good one to take a look at this since he's been working with pgbouncer. I put this in the Need Info / Retest column since it's not clear we have a consistent repro for this. @jrockway if you can find a consistent repro for it that'd be great but if it won't repro then we probably don't need to be as worried about it.
