### ISSUE TITLE
pachd Failing with Segmentation Faults

### ISSUE THREAD

**Issue by dgeorg42** [pachyderm/pachyderm#6641]
This morning, as part of looking at #6640, I tried creating one of the customer pipelines I was testing with called "cron_daily". This failed in the same way as the pipeline I initially tried creating yesterday. I then decided to try to uninstall and reinstall Pachyderm to see if that had any effect on the issue.  When I did, however, I forgot to delete the `cron_daily` pipeline first. So, after reinstall, that pipeline tried to start and failed in the same way again.  However, there was also a new problem that surfaced, specifically `pachd` started failing and restarting as well, with segmentation faults.
```
2021-07-29T15:17:50Z INFO PPS master: launching master process
2021-07-29T15:17:50Z INFO PPS master: processing event for "cron_daily"
2021-07-29T15:17:50Z INFO pfs.API.GetFileTAR {"request":{"file":{"commit":{"branch":{"repo":{"name":"cron_daily","type":"spec"},"name":"master"},"id":"971ea721430d4cb3b18cad1ab58e4994"},"path":"spec"}}} 
2021-07-29T15:17:50Z INFO pfs.API.gopanic {"duration":0.000184446,"request":{"file":{"commit":{"branch":{"repo":{"name":"cron_daily","type":"spec"},"name":"master"},"id":"971ea721430d4cb3b18cad1ab58e4994"},"path":"spec"}}} 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x1d2af4d]

goroutine 172 [running]:
github.com/pachyderm/pachyderm/v2/src/internal/transactionenv.(*TransactionEnv).WithReadContext(0xc00062d940, 0x2b81340, 0xc0004653b0, 0xc0007af190, 0xc0006d3370, 0x1)
	/Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/internal/transactionenv/env.go:328 +0x2d
github.com/pachyderm/pachyderm/v2/src/server/pfs/server.(*driver).inspectCommit(0xc000631880, 0x2b81340, 0xc0004653b0, 0xc000391600, 0xc000000001, 0x1, 0x1, 0x0)
	/Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/server/pfs/server/driver.go:893 +0x1c5
github.com/pachyderm/pachyderm/v2/src/server/pfs/server.(*driver).openCommit(0xc000631880, 0x2b81340, 0xc0004653b0, 0xc000391600, 0xc000755a90, 0x2, 0x2, 0x2f, 0x3, 0x18, ...)
	/Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/server/pfs/server/driver_file.go:132 +0x166
github.com/pachyderm/pachyderm/v2/src/server/pfs/server.(*driver).getFile(0xc000631880, 0x2b81340, 0xc0004653b0, 0xc0002dd3b0, 0x7, 0x1, 0x0, 0x4140bd)
	/Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/server/pfs/server/driver_file.go:186 +0x18d
github.com/pachyderm/pachyderm/v2/src/server/pfs/server.(*apiServer).GetFileTAR.func3(0xc00071cc30, 0x0, 0x0)
	/Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/server/pfs/server/api_server.go:502 +0x90
github.com/pachyderm/pachyderm/v2/src/internal/storage/metrics.ReportRequestWithThroughput.func1(0xc038cf87898cfc04, 0xefde386)
	/Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/internal/storage/metrics/metrics.go:68 +0x4d
github.com/pachyderm/pachyderm/v2/src/internal/storage/metrics.ReportRequest(0xc0007af5c0, 0xc0007af5a0, 0x1, 0x1, 0x0, 0x0)
	/Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/internal/storage/metrics/metrics.go:54 +0x170
github.com/pachyderm/pachyderm/v2/src/internal/storage/metrics.ReportRequestWithThroughput(0xc0007af658, 0xefc9a1a, 0x3c14d00)
	/Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/internal/storage/metrics/metrics.go:67 +0x170
github.com/pachyderm/pachyderm/v2/src/server/pfs/server.(*apiServer).GetFileTAR(0xc000445d10, 0xc000391dc0, 0x2b975e8, 0xc0003915c0, 0x0, 0x0)
	/Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/server/pfs/server/api_server.go:500 +0x165
github.com/pachyderm/pachyderm/v2/src/server/pfs/server.(*validatedAPIServer).GetFileTAR(0xc00000ddb8, 0xc000391dc0, 0x2b975e8, 0xc0003915c0, 0x241d360, 0x3c44cf8)
	/Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/server/pfs/server/val_server.go:179 +0x7a
github.com/pachyderm/pachyderm/v2/src/internal.GetPipelineDetails(0x2b81340, 0xc0004653b0, 0x7f44b9cac958, 0xc00000ddb8, 0xc00038c3f0, 0x0, 0x0)
	/Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/internal/internal.go:81 +0x168
github.com/pachyderm/pachyderm/v2/src/server/pps/server.(*ppsMaster).newPipelineOp(0xc0006a4420, 0x2b81298, 0xc000530680, 0xc00064bf00, 0xa, 0x0, 0x0, 0x0)
	/Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/server/pps/server/pipeline_controller.go:142 +0x496
github.com/pachyderm/pachyderm/v2/src/server/pps/server.(*ppsMaster).step(0xc0006a4420, 0xc00064bf00, 0xa, 0x0, 0x0, 0x0, 0x0)
	/Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/server/pps/server/pipeline_controller.go:98 +0x38c
github.com/pachyderm/pachyderm/v2/src/server/pps/server.(*ppsMaster).attemptStep.func1(0xc0003f7b60, 0x4eb946)
	/Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/server/pps/server/master.go:187 +0x52
github.com/pachyderm/pachyderm/v2/src/internal/backoff.RetryUntilCancel(0x2b812d0, 0xc000058120, 0xc0007afc30, 0x2b4a7e0, 0xc0003f7b60, 0xc0007afc48, 0x1, 0x2)
	/Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/internal/backoff/retry.go:129 +0x56
github.com/pachyderm/pachyderm/v2/src/internal/backoff.RetryNotify(...)
	/Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/internal/backoff/retry.go:118
github.com/pachyderm/pachyderm/v2/src/server/pps/server.(*ppsMaster).attemptStep(0xc0006a4420, 0x2b81298, 0xc000198c00, 0xc000465170, 0x2, 0xc0005ad001)
	/Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/server/pps/server/master.go:185 +0x12f
github.com/pachyderm/pachyderm/v2/src/server/pps/server.(*ppsMaster).run(0xc0006a4420)
	/Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/server/pps/server/master.go:159 +0x352
github.com/pachyderm/pachyderm/v2/src/server/pps/server.(*apiServer).master.func1(0x0, 0x0)
	/Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/server/pps/server/master.go:120 +0x19e
github.com/pachyderm/pachyderm/v2/src/internal/backoff.RetryUntilCancel(0x2b812d0, 0xc000058120, 0xc0007aff88, 0x2b4a7e0, 0xc0006a4480, 0x28b2af8, 0x0, 0x0)
	/Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/internal/backoff/retry.go:129 +0x56
github.com/pachyderm/pachyderm/v2/src/internal/backoff.RetryNotify(...)
	/Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/internal/backoff/retry.go:118
github.com/pachyderm/pachyderm/v2/src/server/pps/server.(*apiServer).master(0xc000694000)
	/Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/server/pps/server/master.go:109 +0x25f
created by github.com/pachyderm/pachyderm/v2/src/server/pps/server.NewAPIServer
	/Users/avigil/Pachyderm/Pachyderm_releases/pachyderm/src/server/pps/server/server.go:44 +0x8ee
```

[AB#15](https://dev.azure.com/PachydermCompany/92b98a32-88e5-46cb-a28f-5d064712e03b/_workitems/edit/15)

**Comment by jdoliner** [comment]
@PFedak would you mind taking a look at this?

**Comment by jdoliner** [comment]
@brycemcanally @brendoncarroll is it possible this is going to be fixed by some of the connection changes you're making?

**Comment by brendoncarroll** [comment]
It looks like the serviceEnv in the TransactionEnv is not getting initialized?

**Comment by dgeorg42** [comment]
I have not been able to reproduce this in Beta 5. Closing.
